inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4AFXQACGVuY2hhbnRzdAALcmVwYWlyLWNvc3R0AAZEYW1hZ2V1cQB+AAYAAAAFcQB+ABl0\r\
  \nAApVTlNQRUNJRklDc3EAfgADdXEAfgAGAAAABHQACURJR19TUEVFRHQAB01FTkRJTkd0AApTSUxL\r\
  \nX1RPVUNIdAAKRFVSQUJJTElUWXVxAH4ABgAAAARzcQB+AA4AAAAFc3EAfgAOAAAAAXEAfgBDc3EA\r\
  \nfgAOAAAAA3EAfgBEc3EAfgAOAAAA63NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+\r\
  \nAAp0AAZhbW91bnRxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NL\r\
  \nRVRzcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4A\r\
  \nBgAAAANxAH4AGXQACEZJUkVXT1JLcQB+AENzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AElxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnRxAH4ATHEAfgBNc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AUXVxAH4ABgAAAANxAH4AGXEAfgBTcQB+AENz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAGRUxZVFJBc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4ANnEA\r\
  \nfgA3cQB+ADh1cQB+AAYAAAAFcQB+ABlxAH4AOnNxAH4AA3VxAH4ABgAAAAJxAH4APnEAfgBAdXEA\r\
  \nfgAGAAAAAnEAfgBDcQB+AERxAH4ARHNxAH4ADgAAABBzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AElxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnRxAH4ATHNxAH4A\r\
  \nDgAAAAtzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgBRdXEAfgAGAAAAA3EAfgAZ\r\
  \ncQB+AFNxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ASXVxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRIRVJSQUNLc3EAfgAOAAAAO3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtE\r\
  \nSUFNT05EX0hPRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADZxAH4AOHVxAH4A\r\
  \nBgAAAARxAH4AGXEAfgA6c3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlN\r\
  \nYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAFxAH4APXVxAH4ABgAA\r\
  \nAAFzcQB+AA4AAAAEc3EAfgAOAAAA4XNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ASXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1HT0xERU5fQ0FSUk9Uc3EAfgAOAAAA\r\
  \nP3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ASXVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnRxAH4AenNxAH4ADgAAAA1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFU1RPTkVzcQB+AA4AAAAIc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBJdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQABERJUlRzcQB+AA4AAAACc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx\r\
  \nAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AApTUElERVJfRVlFc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAdGVVJOQUNF\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgARc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAX\r\
  \ndXEAfgAGAAAABHEAfgAZcQB+ABp0AJJ7InRleHQiOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2tw\r\
  \nYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNl\r\
  \nLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAfcQB+ACB1cQB+AAYAAAADcQB+ACJ0ACRlZDU3\r\
  \nZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcQB+ACQAAAABdwQAAAABc3EAfgAmP0AA\r\
  \nAAAAAAx3CAAAABAAAAACcQB+ACl0AAh0ZXh0dXJlc3EAfgArdAC0ZXlKMFpYaDBkWEpsY3lJNmV5\r\
  \nSlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1W\r\
  \nMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6\r\
  \nTnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBJdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQABVRPUkNIc3EAfgAOAAAAPHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ASXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTVFJJTkdxAH4ApnBwcHBwcHBwcHBw\r\
  \ncHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AEl1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxxAH4AanNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAIU1BZR0xBU1NzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAFQVJST1dzcQB+AA4AAAA1c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVx\r\
  \nAH4ACHEAfgAVcQB+ADZxAH4AN3EAfgA4dXEAfgAGAAAABXEAfgAZcQB+ADpzcQB+AAN1cQB+AAYA\r\
  \nAAADdAAOQVJST1dfSU5GSU5JVEV0AAxBUlJPV19EQU1BR0VxAH4AQHVxAH4ABgAAAANxAH4AQ3EA\r\
  \nfgBCcQB+AERxAH4AQ3NxAH4ADgAAAKxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4ANnEAfgA3dXEAfgAGAAAABHEAfgAZcQB+ADpz\r\
  \ncQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTcQB+AD50AA1EQU1B\r\
  \nR0VfVU5ERUFEdAANU1dFRVBJTkdfRURHRXEAfgBAdXEAfgAGAAAABnEAfgCmcQB+AERxAH4AQ3EA\r\
  \nfgBCcQB+AERxAH4ARHEAfgBEc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgBJcQB+AAt1cQB+AAYAAAAFcQB+AA1zcQB+AA4AAA50cQB+AExxAH4ATXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHEAfgAVcQB+AFF1cQB+AAYAAAADcQB+ABlxAH4AU3EAfgBDc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZx\r\
  \nAH4AN3EAfgA4dXEAfgAGAAAABXEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhf\r\
  \nU1RSSURFUnEAfgA+dAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+AEB1cQB+AAYAAAAEcQB+\r\
  \nAERxAH4AQ3EAfgCKcQB+AERzcQB+AA4AAAAPc3EAfgAOAAAADHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABJORVRIRVJJ\r\
  \nVEVfTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+ADdxAH4A\r\
  \nOHVxAH4ABgAAAAVxAH4AGXEAfgEac3EAfgADdXEAfgAGAAAAA3EAfgA+cQB+AR5xAH4AQHVxAH4A\r\
  \nBgAAAANxAH4AQ3EAfgCKcQB+AERzcQB+AA4AAAAHc3EAfgAOAAAACnNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABRORVRI\r\
  \nRVJJVEVfQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4A\r\
  \nN3EAfgA4dXEAfgAGAAAABXEAfgAZcQB+ARpzcQB+AAN1cQB+AAYAAAADcQB+AD5xAH4BHnEAfgBA\r\
  \ndXEAfgAGAAAAA3EAfgBDcQB+AIpxAH4ARHEAfgEvcQB+AKZzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQTkVUSEVSSVRF\r\
  \nX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4AN3EAfgA4dXEA\r\
  \nfgAGAAAABXEAfgAZcQB+ARpzcQB+AAN1cQB+AAYAAAAEcQB+AD5xAH4BHnQABk9YWUdFTnEAfgBA\r\
  \ndXEAfgAGAAAABHEAfgBDcQB+AIpxAH4ARHEAfgBEcQB+ASBxAH4BIXNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTSElF\r\
  \nTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgA4dAANYmxvY2tNYXRlcmlhbHVx\r\
  \nAH4ABgAAAARxAH4AGXQAC1RJTEVfRU5USVRZc3EAfgAOAAAAW3EAfgFR\r\n"
xp: 1275.0
health: 7.735433101654053
hunger: 17
saturation: 0.0
location:
  world: world
  x: 11066.6
  y: 128.0
  z: 2364.3
logType: JOIN
version: v1_20_R3
