inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4AFXQACGVuY2hhbnRzdAALcmVwYWlyLWNvc3R0AAZEYW1hZ2V1cQB+AAYAAAAFcQB+ABl0\r\
  \nAApVTlNQRUNJRklDc3EAfgADdXEAfgAGAAAABHQACURJR19TUEVFRHQAB01FTkRJTkd0AApTSUxL\r\
  \nX1RPVUNIdAAKRFVSQUJJTElUWXVxAH4ABgAAAARzcQB+AA4AAAAFc3EAfgAOAAAAAXEAfgBDc3EA\r\
  \nfgAOAAAAA3EAfgBEc3EAfgAOAAAA63NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+\r\
  \nAAp0AAZhbW91bnRxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NL\r\
  \nRVRzcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4A\r\
  \nBgAAAANxAH4AGXQACEZJUkVXT1JLcQB+AENzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AElxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnRxAH4ATHNxAH4ADgAAADVz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgBRdXEAfgAGAAAAA3EAfgAZcQB+AFNx\r\
  \nAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAZFTFlUUkFzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEA\r\
  \nfgA2cQB+ADdxAH4AOHVxAH4ABgAAAAVxAH4AGXEAfgA6c3EAfgADdXEAfgAGAAAAAnEAfgA+cQB+\r\
  \nAEB1cQB+AAYAAAACcQB+AENxAH4ARHEAfgBEc3EAfgAOAAAAOnBzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKTkVUSEVS\r\
  \nUkFDS3EAfgBrc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQAC0RJQU1PTkRfSE9Fc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+ABVxAH4ANnEAfgA4dXEAfgAGAAAABHEAfgAZcQB+ADpzcgA3Y29tLmdvb2dsZS5jb21t\r\
  \nb24uY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgAD\r\
  \ndXEAfgAGAAAAAXEAfgA9dXEAfgAGAAAAAXNxAH4ADgAAAARzcQB+AA4AAADhc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBJdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nDUdPTERFTl9DQVJST1RzcQB+AA4AAAA7c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgBJdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBxc3EAfgAOAAAADXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ASXVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAVTVE9ORXNxAH4ADgAAAAhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAERElSVHNxAH4ADgAAAAJzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAClNQ\r\
  \nSURFUl9FWUVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHQAB0ZVUk5BQ0VzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAknsidGV4dCI6IiIs\r\
  \nImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpm\r\
  \nYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6Inll\r\
  \nbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AB9xAH4A\r\
  \nIHVxAH4ABgAAAANxAH4AInQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3Nx\r\
  \nAH4AJAAAAAF3BAAAAAFzcQB+ACY/QAAAAAAADHcIAAAAEAAAAAJxAH4AKXQACHRleHR1cmVzcQB+\r\
  \nACt0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgw\r\
  \nZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhO\r\
  \nREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlU\r\
  \nUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA8c3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBJdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nBlNUUklOR3EAfgCcc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAA\r\
  \nAANxAH4ADXNxAH4ADgAADnR0AAxST1RURU5fRkxFU0hwcHBwcHBwcHBwcHBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AEl1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAL\r\
  \nRU5ERVJfUEVBUkxzcQB+AA4AAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhTUFlHTEFTU3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4ASXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVBUlJPV3EA\r\
  \nfgBZc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZx\r\
  \nAH4AN3EAfgA4dXEAfgAGAAAABXEAfgAZcQB+ADpzcQB+AAN1cQB+AAYAAAADdAAOQVJST1dfSU5G\r\
  \nSU5JVEV0AAxBUlJPV19EQU1BR0VxAH4AQHVxAH4ABgAAAANxAH4AQ3EAfgBCcQB+AERxAH4AQ3Nx\r\
  \nAH4ADgAAAKxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ABVxAH4ANnEAfgA3dXEAfgAGAAAABHEAfgAZcQB+ADpzcQB+AAN1cQB+AAYAAAAG\r\
  \ndAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTcQB+AD50AA1EQU1BR0VfVU5ERUFEdAANU1dF\r\
  \nRVBJTkdfRURHRXEAfgBAdXEAfgAGAAAABnEAfgCccQB+AERxAH4AQ3EAfgBCcQB+AERxAH4ARHEA\r\
  \nfgBEc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEAfgBJcQB+AAt1cQB+AAYA\r\
  \nAAAFcQB+AA1zcQB+AA4AAA50cQB+AExxAH4ATXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAVcQB+AFF1cQB+AAYAAAADcQB+ABlxAH4AU3EAfgBDc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9C\r\
  \nT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4AN3EAfgA4dXEAfgAG\r\
  \nAAAABXEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RSSURFUnEAfgA+dAAY\r\
  \nUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+AEB1cQB+AAYAAAAEcQB+AERxAH4AQ3EAfgCAcQB+\r\
  \nAERzcQB+AA4AAAAPc3EAfgAOAAAAFnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABJORVRIRVJJVEVfTEVHR0lOR1NzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+ADdxAH4AOHVxAH4ABgAAAAVxAH4A\r\
  \nGXEAfgEWc3EAfgADdXEAfgAGAAAAA3EAfgA+cQB+ARpxAH4AQHVxAH4ABgAAAANxAH4AQ3EAfgCA\r\
  \ncQB+AERzcQB+AA4AAAAHc3EAfgAOAAAADnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABRORVRIRVJJVEVfQ0hFU1RQTEFU\r\
  \nRXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4AN3EAfgA4dXEAfgAGAAAA\r\
  \nBXEAfgAZcQB+ARZzcQB+AAN1cQB+AAYAAAADcQB+AD5xAH4BGnEAfgBAdXEAfgAGAAAAA3EAfgBD\r\
  \ncQB+AIBxAH4ARHEAfgErc3EAfgAOAAAACnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4ANnEAfgA3dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nARZzcQB+AAN1cQB+AAYAAAAEcQB+AD5xAH4BGnQABk9YWUdFTnEAfgBAdXEAfgAGAAAABHEAfgBD\r\
  \ncQB+AIBxAH4ARHEAfgBEcQB+ARxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AOHQADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABl0AAtUSUxF\r\
  \nX0VOVElUWXNxAH4ADgAAAFtxAH4BTg==\r\n"
xp: 1275.0
health: 26.0
hunger: 20
saturation: 14.400001
location:
  world: world
  x: 11758.0
  y: 66.0
  z: -2423.6
logType: JOIN
version: v1_20_R3
