inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JD\r\
  \nSHNxAH4ADgAAAD5zcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+ADxxAH4A\r\
  \nC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRzcQB+AA4AAAAKc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4AGXQACEZJ\r\
  \nUkVXT1JLcQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAac3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAdcQB+ADN0AApTSUxLX1RPVUNIcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4A\r\
  \nOHEAfgA4cQB+ACJxAH4AInNxAH4ADgAAAOhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AFNzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4AHXEAfgAecQB+ADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAicQB+ADhxAH4AInNx\r\
  \nAH4ADgAAAMxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAMUk9UVEVOX0ZMRVNIcQB+ACJzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGQ0FSUk9U\r\
  \nc3EAfgAOAAAAPXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3QA\r\
  \nBExVQ0t0AARMVVJFcQB+AB91cQB+AAYAAAADcQB+ACJxAH4AInEAfgAicQB+ADhzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAERElSVHEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0VOREVSX1BFQVJMc3EAfgAOAAAAEHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRx\r\
  \nAH4AP3NxAH4ADgAAABxwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAKXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdP\r\
  \nQUtfTE9Hc3EAfgAOAAAAE3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAJR1VOUE9XREVScQB+ACJwc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAdGVVJO\r\
  \nQUNFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHEAfgCsc3EAfgAOAAAAQHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NxAH4A\r\
  \nN3Bwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQABUNIRVNUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABV0AAxk\r\
  \naXNwbGF5LW5hbWV0ABJQdWJsaWNCdWtraXRWYWx1ZXN0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAA\r\
  \nBXEAfgAZdAALVElMRV9FTlRJVFl0ACF7InRleHQiOiIiLCJleHRyYSI6WyJpdGVtc1BhY2siXX10\r\
  \nADp7CiAgICAiZmlzaHJld2FyZHM6ZXhhbXBsZWl0ZW1zcGFjayI6ICJFeGFtcGxlSXRlbXNQYWNr\r\
  \nIgp9cQB+AMRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXQABUFSTU9Sc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAzdAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+AB91cQB+AAYA\r\
  \nAAADcQB+ADhzcQB+AA4AAAAEcQB+ACJzcQB+AA4AAAAHc3EAfgAOAAAADXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQ\r\
  \nTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+AMh0AAtza3VsbC1v\r\
  \nd25lcnVxAH4ABgAAAARxAH4AGXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4A\r\
  \nF3EAfgDKdXEAfgAGAAAABHEAfgAZcQB+AMxzcQB+AA4AAABbcQB+AQRzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGQlVD\r\
  \nS0VUcQB+ADdzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHQAD0ZMSU5UX0FORF9TVEVFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMR0xBU1NfQk9UVExFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAX\r\
  \ndXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAADdAAOQVJST1dfSU5GSU5JVEV0AAxB\r\
  \nUlJPV19EQU1BR0VxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgAhcQB+ACJxAH4AOHNxAH4ADgAAAHZw\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgA/c3EAfgAOAAAAKnBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX0JPT1RTc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4A2XNxAH4AA3VxAH4ABgAAAAR0AA1ERVBUSF9TVFJJREVScQB+ADNxAH4A3HEAfgAfdXEA\r\
  \nfgAGAAAABHEAfgAicQB+ADhxAH4A3nEAfgAic3EAfgAOAAAAD3EAfgAic3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5F\r\
  \nVEhFUklURV9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4A\r\
  \nLXVxAH4ABgAAAARxAH4AGXEAfgDZc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+ANxxAH4AH3VxAH4A\r\
  \nBgAAAANxAH4AOHEAfgDecQB+ACJxAH4A33NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZFTFlUUkFzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAac3EA\r\
  \nfgADdXEAfgAGAAAAAnEAfgAzcQB+AB91cQB+AAYAAAACcQB+ADhxAH4AInEAfgAicQB+ACFzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgDZc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+ANxx\r\
  \nAH4AH3VxAH4ABgAAAANxAH4AOHEAfgDecQB+ACJxAH4A33A=\r\n"
xp: 1547.0
health: 23.018508911132812
hunger: 17
saturation: 0.0
location:
  world: world
  x: 12624.4
  y: 74.0
  z: -105.4
logType: JOIN
version: v1_20_R3
