inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAM9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0cQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4AGnNxAH4AA3VxAH4ABgAAAAZ0AAlLTk9DS0JBQ0t0AA9MT09UX0JPTlVTX01PQlN0AAdN\r\
  \nRU5ESU5HdAANREFNQUdFX1VOREVBRHQADVNXRUVQSU5HX0VER0VxAH4AH3VxAH4ABgAAAAZzcQB+\r\
  \nAA4AAAACcQB+ACJzcQB+AA4AAAABcQB+ACFxAH4AInEAfgAicQB+ACJxAH4AInNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKTkVUSEVSUkFDS3NxAH4ADgAAADpzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU1BPTkdFc3EAfgAOAAAALnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0ABFORVRIRVJJVEVfUElDS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEA\r\
  \nfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAB1xAH4AM3QAClNJTEtfVE9VQ0hxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgA4cQB+ADhxAH4AInEA\r\
  \nfgAic3EAfgAOAAAA/XNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1HT0xERU5fQ0FSUk9Uc3EAfgAOAAAAB3NxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAhPQUtfRE9PUnNxAH4ADgAAACdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA0c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0\r\
  \nAARCRUxMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4A\r\
  \nDXNxAH4ADgAADnR0AAtMQVZBX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtFTkRFUl9QRUFSTHNxAH4ADgAA\r\
  \nABBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAI\r\
  \ncQB+ABVxAH4AF3VxAH4ABgAAAANxAH4AGXEAfgAac3EAfgAOAAAAD3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVD\r\
  \nS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAFHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdPQUtfTE9Hc3EAfgAO\r\
  \nAAAAGXBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAALU0VBX0xBTlRFUk5zcQB+AA4AAAAocHNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZT\r\
  \nSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAXdAANYmxvY2tNYXRlcmlh\r\
  \nbHVxAH4ABgAAAARxAH4AGXQAC1RJTEVfRU5USVRZc3EAfgAOAAAAW3EAfgCqc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nDU5FVEhFUklURV9BWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1x\r\
  \nAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3EAfgAdcQB+AFRxAH4AH3Vx\r\
  \nAH4ABgAAAANxAH4AIXEAfgA4cQB+ACJxAH4AInNxAH4ADgAAAIFwc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBqc3EA\r\
  \nfgAOAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4AanEAfgDFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBqcQB+AMVzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRpc3BsYXkt\r\
  \nbmFtZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAZdAAFU0tVTEx0AJJ7InRleHQiOiIiLCJl\r\
  \neHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFs\r\
  \nc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxs\r\
  \nb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlk\r\
  \ndAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0z\r\
  \nYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkA\r\
  \nBHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoA\r\
  \nC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9y\r\
  \nSQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1\r\
  \nZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBk\r\
  \nWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5E\r\
  \nRmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRR\r\
  \neVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANCT1dzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nAAhxAH4AFXEAfgAXdXEAfgAGAAAAA3EAfgAZcQB+ABpzcQB+AA4AAAEBc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAtNSUxLX0JV\r\
  \nQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1z\r\
  \ncQB+AA4AAA50cQB+AIRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AE1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEA\r\
  \nfgAecQB+ADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAicQB+ADhxAH4AInNxAH4ADgAAAMxzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50cQB+APRzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4A\r\
  \nF3VxAH4ABgAAAAVxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3QADkFSUk9XX0lORklOSVRFdAAM\r\
  \nQVJST1dfREFNQUdFcQB+AB91cQB+AAYAAAADcQB+ADhxAH4AIXEAfgAicQB+ADhzcQB+AA4AAAB2\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEAfgA8cQB+AAt1cQB+AAYAAAAF\r\
  \ncQB+AA1zcQB+AA4AAA50dAAPRklSRVdPUktfUk9DS0VUc3EAfgAOAAAAN3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHEAfgAVdAAFcG93ZXJ1cQB+AAYAAAADcQB+ABl0AAhGSVJFV09SS3EAfgA4\r\
  \ncHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAZFTFlUUkFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAW\r\
  \ncQB+AC11cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAJxAH4AM3EAfgAfdXEAfgAG\r\
  \nAAAAAnEAfgA4cQB+ACJxAH4AInNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ORVRIRVJJVEVfQk9PVFNzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXQABUFS\r\
  \nTU9Sc3EAfgADdXEAfgAGAAAABHQADURFUFRIX1NUUklERVJxAH4AM3QAGFBST1RFQ1RJT05fRU5W\r\
  \nSVJPTk1FTlRBTHEAfgAfdXEAfgAGAAAABHEAfgAicQB+ADhzcQB+AA4AAAAEcQB+ACJxAH4AiXNx\r\
  \nAH4ADgAAABpzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4BRXNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4AM3EAfgFJcQB+AB91cQB+AAYAAAADcQB+ADhxAH4BS3EAfgAicQB+AF1zcQB+\r\
  \nAA4AAAAvc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAFE5FVEhFUklURV9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4BRXNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4AM3EAfgFJcQB+AB91cQB+AAYAAAADcQB+ADhxAH4BS3EAfgAicQB+AF1zcQB+\r\
  \nAA4AAAAbc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAEE5FVEhFUklURV9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAF\r\
  \ncQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgFFc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAzcQB+AUlxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgFLcQB+ACJxAH4AXXNxAH4ADgAA\r\
  \nABhw\r\n"
xp: 1698.0
health: 25.90267562866211
hunger: 17
saturation: 0.0
location:
  world: world_nether
  x: 1634.8
  y: 48.0
  z: -4573.9
logType: JOIN
version: v1_20_R3
