inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAAEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAknsidGV4dCI6\r\
  \nIiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGlj\r\
  \nIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6\r\
  \nInllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5p\r\
  \ncXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03\r\
  \nMDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2Gd\r\
  \nAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7\r\
  \nAgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRG\r\
  \nYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QA\r\
  \nBXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkw\r\
  \nWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZ\r\
  \nV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05X\r\
  \nRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQAEERJQU1PTkRfTEVHR0lOR1NzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AF3QACGVuY2hhbnRzdXEAfgAGAAAAA3EAfgAbdAAFQVJN\r\
  \nT1JzcQB+AAN1cQB+AAYAAAACdAANQklORElOR19DVVJTRXQACkRVUkFCSUxJVFl1cQB+AAYAAAAC\r\
  \nc3EAfgAPAAAAAXNxAH4ADwAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAORU5DSEFOVEVEX0JPT0tzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAADcQB+AAhxAH4AF3QAD3N0b3JlZC1lbmNoYW50c3VxAH4ABgAAAANxAH4AG3QA\r\
  \nCUVOQ0hBTlRFRHNyADdjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNl\r\
  \ncmlhbGl6ZWRGb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+AAYAAAABdAAVUFJPVEVDVElPTl9FWFBM\r\
  \nT1NJT05TdXEAfgAGAAAAAXEAfgATc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AARMRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABlBPVElPTnNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAXdAALcG90aW9uLXR5cGV1cQB+AAYAAAADcQB+ABtx\r\
  \nAH4AXnQAHW1pbmVjcmFmdDpzdHJvbmdfcmVnZW5lcmF0aW9uc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHEAfgBec3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABdxAH4AYnVxAH4ABgAAAANxAH4AG3EAfgBedAAdbWlu\r\
  \nZWNyYWZ0OnN0cm9uZ19yZWdlbmVyYXRpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAKTkVUSEVSUkFDS3NxAH4ADwAA\r\
  \nAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+\r\
  \nAA5zcQB+AA8AAA50dAALRElBTU9ORF9IT0VzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nF3EAfgA4dAAGRGFtYWdldXEAfgAGAAAABHEAfgAbdAAKVU5TUEVDSUZJQ3NxAH4ATnVxAH4ABgAA\r\
  \nAAF0AAlESUdfU1BFRUR1cQB+AAYAAAABcQB+ABNzcQB+AA8AAADfc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAVCUkVBRHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4A\r\
  \nDwAADnRxAH4AdHNxAH4ADwAAAA1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAEQk9PS3NxAH4ADwAAABxzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50\r\
  \ndAAOQU1FVEhZU1RfU0hBUkRxAH4AE3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARDT0FMc3EAfgAPAAAAEHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAH\r\
  \nRlVSTkFDRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAA\r\
  \nAARxAH4ADnNxAH4ADwAADnRxAH4AEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+\r\
  \nABhxAH4AGXVxAH4ABgAAAARxAH4AG3EAfgAcdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AIXEAfgAidXEAfgAGAAAAA3EAfgAk\r\
  \ndAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3EAfgAmAAAAAXcEAAAAAXNx\r\
  \nAH4AKD9AAAAAAAAMdwgAAAAQAAAAAnEAfgArdAAIdGV4dHVyZXNxAH4ALXQAtGV5SjBaWGgwZFhK\r\
  \nbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0po\r\
  \nWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1RnNE9HUTJa\r\
  \nREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgA\r\
  \neHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDnNxAH4ADwAADnR0AAVUT1JDSHEAfgATc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQAEUVYUEVSSUVOQ0VfQk9UVExFcQB+\r\
  \nAEFzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EA\r\
  \nfgAPAAAOdHQABlNBRERMRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nDHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4AF3EAfgB/dAANYmxvY2tNYXRlcmlhbHVxAH4ABgAAAARxAH4AG3QAC1RJTEVfRU5U\r\
  \nSVRZc3EAfgAPAAAAW3EAfgDXcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==\r\n"
xp: 1268.0
health: 26.0
hunger: 20
saturation: 2.0
location:
  world: world
  x: 11425.4
  y: 64.0
  z: 211.1
logType: JOIN
version: v1_20_R3
