inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAADc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAFnsidGV4dCI6\r\
  \nIsKnZUJhY2twYWNrIn1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnBy\r\
  \nb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpl\r\
  \neHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nl\r\
  \nc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRo\r\
  \ncmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRl\r\
  \neUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5\r\
  \nNXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRN\r\
  \nek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5q\r\
  \nT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA5zcQB+AA8AAA50dAAKT0FLX1BMQU5LU3NxAH4ADwAAACVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAF\r\
  \nQlJFQURzcQB+AA8AAAA9c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAM\r\
  \ndXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQAD0RJQU1PTkRfUElDS0FYRXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHEAfgAXdAAGRGFtYWdldXEAfgAGAAAAA3EAfgAbdAAKVU5TUEVDSUZJQ3Nx\r\
  \nAH4ADwAAAAJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYA\r\
  \nAAAEcQB+AA5zcQB+AA8AAA50dAAMSVJPTl9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EA\r\
  \nfgAIcQB+ABdxAH4ARnVxAH4ABgAAAANxAH4AG3EAfgBIc3EAfgAPAAAAH3BwcHBzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAPAAAOdHQACE9B\r\
  \nS19CT0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAA\r\
  \nBHEAfgAOc3EAfgAPAAAOdHQACElST05fQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nABdxAH4ARnVxAH4ABgAAAANxAH4AG3EAfgBIc3EAfgAPAAAAK3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAZDQVJST1Rx\r\
  \nAH4APHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARx\r\
  \nAH4ADnNxAH4ADwAADnR0AAtJUk9OX1NIT1ZFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAXcQB+AEZ1cQB+AAYAAAADcQB+ABtxAH4ASHNxAH4ADwAAAA1zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFQVJST1dx\r\
  \nAH4AE3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADnNxAH4ADwAADnR0AApJUk9OX0lOR09Uc3EAfgAPAAAABHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AApJUk9OX1NX\r\
  \nT1JEc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABdxAH4ARnVxAH4ABgAAAANxAH4AG3EA\r\
  \nfgBIc3EAfgAPAAAAJ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARCRUVGc3EAfgAPAAAAFHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARDT0FM\r\
  \nc3EAfgAPAAAAEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADnNxAH4ADwAADnR0AApTVUdBUl9DQU5Fc3EAfgAPAAAACnBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAM\r\
  \nUk9UVEVOX0ZMRVNIcQB+AINzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAEQk9ORXEAfgCDcHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAdMRUFU\r\
  \nSEVScQB+AKNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA5zcQB+AA8AAA50dAAFQVBQTEVxAH4AE3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAGU1RSSU5HcQB+AINz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5z\r\
  \ncQB+AA8AAA50dAAHRElBTU9ORHNxAH4ADwAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFU1RJQ0txAH4AyHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4A\r\
  \nDwAADnR0AARCT09Lc3EAfgAPAAAAHnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAHTEVDVEVSTnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAGU0FERExFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAx1cQB+AAYAAAAFcQB+AA5z\r\
  \ncQB+AA8AAA50cQB+ANRxAH4ASXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAXcQB+ABh0\r\
  \nABFjdXN0b20tbW9kZWwtZGF0YXQAElB1YmxpY0J1a2tpdFZhbHVlc3VxAH4ABgAAAAVxAH4AG3EA\r\
  \nfgBIdABHeyJpdGFsaWMiOmZhbHNlLCJ0cmFuc2xhdGUiOiJ2YW5lX2VuY2hhbnRtZW50cy5pdGVt\r\
  \nX2FuY2llbnRfdG9tZS5uYW1lIn1zcQB+AA8AdwAAdABqewogICAgInZhbmU6Y3VzdG9tX2l0ZW1f\r\
  \naWRlbnRpZmllciI6ICJ2YW5lX2VuY2hhbnRtZW50czphbmNpZW50X3RvbWUiLAogICAgInZhbmU6\r\
  \nY3VzdG9tX2l0ZW1fdmVyc2lvbiI6IDEKfXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AApHUklORFNUT05FcQB+AElzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAPAAAO\r\
  \ndHQADUJSRVdJTkdfU1RBTkRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEA\r\
  \nfgAGAAAAA3EAfgAOc3EAfgAPAAAOdHEAfgBacHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA1JUk9OX0xFR0dJTkdTc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABdxAH4ARnVxAH4ABgAAAANxAH4AG3QABUFSTU9S\r\
  \nc3EAfgAPAAAAF3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4A\r\
  \nBgAAAARxAH4ADnNxAH4ADwAADnR0ABJMRUFUSEVSX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4AF3QACGVuY2hhbnRzcQB+AEZ1cQB+AAYAAAAEcQB+ABt0AA9DT0xPUkFC\r\
  \nTEVfQVJNT1JzcQB+AAN1cQB+AAYAAAACdAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMdAAKRFVS\r\
  \nQUJJTElUWXVxAH4ABgAAAAJxAH4ASXEAfgBJc3EAfgAPAAAALnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAtJUk9OX0hF\r\
  \nTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAXcQB+AEZ1cQB+AAYAAAADcQB+ABtx\r\
  \nAH4BC3NxAH4ADwAAABpzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAG\r\
  \nAAAAA3EAfgAOc3EAfgAPAAAOdHQAEFRPVEVNX09GX1VORFlJTkc=\r\n"
xp: 85.0
health: 20.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 16174.3
  y: 64.0
  z: -707.4
logType: QUIT
version: v1_20_R3
