inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAISVJPTl9BWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQA\r\
  \nBkRhbWFnZXVxAH4ABgAAAANxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AA4AAACfc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAZTVFJJTkdzcQB+AA4AAAAyc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNIRUFSU3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAVcQB+ADZ1cQB+AAYAAAADcQB+ABlxAH4AOHNxAH4ADgAAACBwcHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAxJUk9OX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgA2\r\
  \ndXEAfgAGAAAAA3EAfgAZcQB+ADhzcQB+AA4AAABqc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA9dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEFdISVRFX1RFUlJBQ09U\r\
  \nVEFzcQB+AA4AAAAEcHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYA\r\
  \nAAADcQB+AA1zcQB+AA4AAA50dAARQ0FSVE9HUkFQSFlfVEFCTEVzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAJSEFZX0JM\r\
  \nT0NLc3EAfgAOAAAACnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APXVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHEAfgBrc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA9dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUJSRUFEc3EA\r\
  \nfgAOAAAAOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APXVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAVBUlJPV3NxAH4ADgAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKSVJPTl9JTkdP\r\
  \nVHEAfgBec3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA9dXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAC1dIRUFUX1NFRURTc3EAfgAOAAAAAnNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4APXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVTVElD\r\
  \nS3NxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAEQ09BTHNxAH4ADgAAABJzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFUE9QUFlx\r\
  \nAH4AjHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1z\r\
  \ncQB+AA4AAA50dAAKWUVMTE9XX0JFRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtJUk9OX1NIT1ZFTHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ADZ1cQB+AAYAAAADcQB+ABlxAH4AOHNxAH4ADgAAAClz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAERElSVHNxAH4ADgAAAAlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGQlVDS0VUcQB+AIxzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAHTEVBVEhFUnNxAH4ADgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEA\r\
  \nfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAC0NPQkJMRVNUT05Fc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklS\r\
  \nT05fU1dPUkRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgA2dXEAfgAGAAAAA3EA\r\
  \nfgAZcQB+ADhzcQB+AA4AAAAqc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0RJQU1PTkRfUElDS0FYRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ADZ1cQB+AAYAAAADcQB+ABlxAH4AOHNxAH4ADgAAAKBz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAHRElBTU9ORHNxAH4ADgAAABZwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA9dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJPT0tzcQB+AA4AAAAe\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4A\r\
  \nDgAADnR0AAdMRUNURVJOcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1\r\
  \ncQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAKT0FLX1BMQU5LU3BzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANSVJPTl9M\r\
  \nRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ADZ1cQB+AAYAAAADcQB+\r\
  \nABl0AAVBUk1PUnNxAH4ADgAAACRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAASTEVBVEhFUl9DSEVTVFBMQVRFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABV0AAhlbmNoYW50c3EAfgA2dXEAfgAGAAAABHEAfgAZ\r\
  \ndAAPQ09MT1JBQkxFX0FSTU9Sc3EAfgADdXEAfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJPTk1F\r\
  \nTlRBTHQACkRVUkFCSUxJVFl1cQB+AAYAAAACcQB+AIxxAH4AjHNxAH4ADgAAADVzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAALSVJPTl9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgA2dXEAfgAG\r\
  \nAAAAA3EAfgAZcQB+AQZzcQB+AA4AAAAncA==\r\n"
xp: 245.0
health: 20.0
hunger: 15
saturation: 0.0
location:
  world: world
  x: 16167.3
  y: 65.0
  z: -702.0
logType: QUIT
version: v1_20_R3
