inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50dXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQABlNUUklOR3NxAH4ADgAAADJzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hFQVJTc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAZEYW1hZ2V1cQB+AAYAAAADcQB+ABl0AApV\r\
  \nTlNQRUNJRklDc3EAfgAOAAAAKHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQV0hJVEVfVEVSUkFDT1RUQXNxAH4A\r\
  \nDgAAAAdwc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4A\r\
  \nDXNxAH4ADgAADnR0ABFDQVJUT0dSQVBIWV9UQUJMRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAlIQVlfQkxPQ0tzcQB+\r\
  \nAA4AAAAKc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQABVRPUkNIcQB+AFVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQlJFQURzcQB+AA4AAAA4\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAA3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApJUk9OX0lOR09Uc3EAfgAO\r\
  \nAAAABHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtXSEVBVF9TRUVEU3NxAH4ADgAAAAJzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFU1RJQ0tx\r\
  \nAH4ASHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AARDT0FMc3EAfgAOAAAAEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVQT1BQWXEAfgB3c3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAA\r\
  \nDnR0AApZRUxMT1dfQkVEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0lST05fU0hPVkVMc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+ABVxAH4APnVxAH4ABgAAAANxAH4AGXEAfgBAc3EAfgAOAAAAKXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AARESVJUc3EAfgAOAAAACXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAhJUk9OX0FYRXNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAVcQB+AD51cQB+AAYAAAADcQB+ABlxAH4AQHNxAH4ADgAAAKFzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAHTEVBVEhFUnNxAH4ADgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEA\r\
  \nfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAC0NPQkJMRVNUT05Fc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklS\r\
  \nT05fU1dPUkRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgA+dXEAfgAGAAAAA3EA\r\
  \nfgAZcQB+AEBzcQB+AA4AAAAqc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0RJQU1PTkRfUElDS0FYRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AD51cQB+AAYAAAADcQB+ABlxAH4AQHNxAH4ADgAAAKBz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAHRElBTU9ORHNxAH4ADgAAABZwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJPT0tzcQB+AA4AAAAe\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4A\r\
  \nDgAADnR0AAdMRUNURVJOc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAw\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkJVQ0tFVHEAfgB3c3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADElST05f\r\
  \nUElDS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AD51cQB+AAYAAAADcQB+\r\
  \nABlxAH4AQHNxAH4ADgAAAG9zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEA\r\
  \nfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADE9BS19UUkFQRE9PUnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAFTEVWRVJzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nCk9BS19QTEFOS1Nwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUlST05fTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AFXEAfgA+dXEAfgAGAAAAA3EAfgAZdAAFQVJNT1JzcQB+AA4AAAAkc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAEkxFQVRIRVJfQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ndAAIZW5jaGFudHNxAH4APnVxAH4ABgAAAARxAH4AGXQAD0NPTE9SQUJMRV9BUk1PUnNxAH4AA3Vx\r\
  \nAH4ABgAAAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUx0AApEVVJBQklMSVRZdXEAfgAGAAAA\r\
  \nAnEAfgB3cQB+AHdzcQB+AA4AAAA1c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0lST05fSEVMTUVUc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4APnVxAH4ABgAAAANxAH4AGXEAfgESc3EAfgAOAAAAJ3A=\r\
  \n"
xp: 251.0
health: 20.0
hunger: 15
saturation: 0.0
location:
  world: world
  x: 16167.2
  y: 64.0
  z: -701.5
logType: QUIT
version: v1_20_R3
