inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAABA3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAAGHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEcQB+\r\
  \nABh0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1\r\
  \nc2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRo\r\
  \ncm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXll\r\
  \nclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51\r\
  \ndGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwu\r\
  \nTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hN\r\
  \nYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAA\r\
  \nAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpw\r\
  \nN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIx\r\
  \nY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZ\r\
  \nbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhPQUtfQk9B\r\
  \nVHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAORElBTU9ORF9TSE9WRUxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABhxAH4AGXNxAH4AA3VxAH4ABgAAAAJxAH4AK3QA\r\
  \nD1ZBTklTSElOR19DVVJTRXVxAH4ABgAAAAJxAH4ALXEAfgAvc3EAfgAOAAAAbHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FU\r\
  \nRVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4ADgAAADdzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AG51cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElB\r\
  \nTU9ORHNxAH4ADgAAAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AG51\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKR0xBU1NfUEFORXEAfgB5c3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADU5F\r\
  \nVEhFUklURV9BWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAkdAALcmVwYWly\r\
  \nLWNvc3RxAH4AFnVxAH4ABgAAAAVxAH4AGHEAfgAZc3EAfgADdXEAfgAGAAAAA3EAfgAodAAKU0lM\r\
  \nS19UT1VDSHEAfgArdXEAfgAGAAAAA3NxAH4ADgAAAAVxAH4AL3EAfgAtcQB+AC1zcQB+AA4AAACE\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBudXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQABEJFRUZzcQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgBudXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NFQV9MQU5URVJOc3EAfgAO\r\
  \nAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAZQT1RJT05zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQA\r\
  \nC3BvdGlvbi10eXBldXEAfgAGAAAAA3EAfgAYcQB+AKR0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92\r\
  \naXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50cQB+AKRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCo\r\
  \ndXEAfgAGAAAAA3EAfgAYcQB+AKR0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AKRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCodXEAfgAGAAAAA3EA\r\
  \nfgAYcQB+AKR0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AG51cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJ1zcQB+\r\
  \nAA4AAAAec3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBudXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQABERJUlRxAH4AnnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AbnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZDQVJST1RxAH4AnnNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AbnVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnRxAH4A0HEAfgCec3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBu\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgDQcQB+AJ5zcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AG51cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+ANBzcQB+AA4A\r\
  \nAAAtcHBwcHBwcHBwcHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHQABUFSTU9Sc3EAfgADdXEA\r\
  \nfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHEAfgArdXEAfgAGAAAAAnNxAH4ADgAA\r\
  \nAARxAH4ALXNxAH4ADgAAAHlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANSVJPTl9MRUdHSU5HU3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgDrc3IAN2NvbS5n\r\
  \nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAA\r\
  \nAAIAAHhxAH4AA3VxAH4ABgAAAAFxAH4AK3VxAH4ABgAAAAFxAH4ALXNxAH4ADgAAAHpzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAPSVJPTl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4A\r\
  \nJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+AOtzcQB+AAN1cQB+AAYAAAACcQB+AO5xAH4AK3VxAH4A\r\
  \nBgAAAAJxAH4A8HEAfgAtc3EAfgAOAAAAe3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABh0\r\
  \nAAtUSUxFX0VOVElUWXNxAH4ADgAAABRxAH4BFA==\r\n"
xp: 777.0
health: 24.0
hunger: 20
saturation: 2.6000001
location:
  world: world
  x: 11413.4
  y: 65.0
  z: 210.3
logType: QUIT
version: v1_20_R3
