inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nA3QAAj09dAABdnQABHR5cGV1cQB+AAYAAAADdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0\r\
  \nYWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcu\r\
  \nTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AApXT09ERU5fQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADHNxAH4ADQAADnR0AAVMRVZFUnNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAA50dAAI\r\
  \nUkVQRUFURVJzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgAMc3EAfgANAAAOdHQACk9BS19QTEFOS1NzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nCXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgANAAAOdHQADFNUT05FX0JVVFRPTnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAA50dAAGUElT\r\
  \nVE9Oc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADHNx\r\
  \nAH4ADQAADnR0AAhPQlNFUlZFUnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0\r\
  \nAAZhbW91bnR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAMUE9XRVJFRF9SQUlMc3EAfgANAAAA\r\
  \nAnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+\r\
  \nAA0AAA50dAANU1RJQ0tZX1BJU1RPTnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAAp0AARtZXRhdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3du\r\
  \nZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0\r\
  \nZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJs\r\
  \naW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQi\r\
  \nOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0\r\
  \naWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0x\r\
  \nZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAA\r\
  \nAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3Jk\r\
  \nZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hv\r\
  \nbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpY\r\
  \naDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1\r\
  \nbFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0\r\
  \nT0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlm\r\
  \nWDA9eAB4cHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AEZ1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAKSVJPTl9CT09UU3Nx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgBNdAAIZW5jaGFudHN0AAZEYW1hZ2V1cQB+AAYA\r\
  \nAAAEcQB+AFF0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5U\r\
  \nQUx0AApEVVJBQklMSVRZdXEAfgAGAAAAAnNxAH4ADQAAAARzcQB+AA0AAAADc3EAfgANAAAAMnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ARnVxAH4ABgAAAARxAH4ADHNx\r\
  \nAH4ADQAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AE1x\r\
  \nAH4AbnEAfgBvdXEAfgAGAAAABHEAfgBRcQB+AHFzcgA3Y29tLmdvb2dsZS5jb21tb24uY29sbGVj\r\
  \ndC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgADdXEAfgAGAAAA\r\
  \nAXEAfgB1dXEAfgAGAAAAAXEAfgB4c3EAfgANAAAAOXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4ARnVxAH4ABgAAAARxAH4ADHNxAH4ADQAADnR0AA9JUk9OX0NIRVNUUExB\r\
  \nVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ATXEAfgBucQB+AG91cQB+AAYAAAAEcQB+\r\
  \nAFFxAH4AcXNxAH4AA3VxAH4ABgAAAAJxAH4AdHEAfgB1dXEAfgAGAAAAAnEAfgB3cQB+AHhxAH4A\r\
  \niHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ARnVxAH4ABgAAAARxAH4A\r\
  \nDHNxAH4ADQAADnR0AAtJUk9OX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgBN\r\
  \ncQB+AG5xAH4Ab3VxAH4ABgAAAARxAH4AUXEAfgBxc3EAfgCEdXEAfgAGAAAAAXEAfgB0dXEAfgAG\r\
  \nAAAAAXEAfgB3c3EAfgANAAAAT3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1\r\
  \ncQB+AAYAAAADcQB+AAxzcQB+AA0AAA50dAAGU0hJRUxE\r\n"
xp: 477.0
health: 20.0
hunger: 20
saturation: 2.6000001
location:
  world: world
  x: 11416.1
  y: 64.0
  z: 218.0
logType: QUIT
version: v1_20_R3
