inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nA3QAAj09dAABdnQABHR5cGV1cQB+AAYAAAADdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0\r\
  \nYWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcu\r\
  \nTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAhPQUtfRE9PUnNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AAp0AARtZXRhdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQADkRJQU1PTkRf\r\
  \nU0hPVkVMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAIZW5jaGFudHN0\r\
  \nAAZEYW1hZ2V1cQB+AAYAAAAEdAAISXRlbU1ldGF0AApVTlNQRUNJRklDc3EAfgADdXEAfgAGAAAA\r\
  \nAnQACkRVUkFCSUxJVFl0AA9WQU5JU0hJTkdfQ1VSU0V1cQB+AAYAAAACc3EAfgANAAAAA3NxAH4A\r\
  \nDQAAAAFzcQB+AA0AAABsc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
  \nBgAAAANxAH4ADHNxAH4ADQAADnR0AAxXQVRFUl9CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50dXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQABkNBUlJP\r\
  \nVHNxAH4ADQAAABhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABR1cQB+\r\
  \nAAYAAAAEcQB+AAxzcQB+AA0AAA50dAAPRElBTU9ORF9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABtxAH4AHHEAfgAddXEAfgAGAAAABHEAfgAfcQB+ACBzcQB+AAN1cQB+AAYA\r\
  \nAAAEdAAJRElHX1NQRUVEdAARTE9PVF9CT05VU19CTE9DS1N0AAdNRU5ESU5HcQB+ACN1cQB+AAYA\r\
  \nAAAEcQB+ACZzcQB+AA0AAAACcQB+ACdxAH4AJnNxAH4ADQAAABBzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAALRElBTU9O\r\
  \nRF9BWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AG3EAfgAddXEAfgAGAAAAA3EAfgAf\r\
  \ncQB+ACBzcQB+AA0AAAGXc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAy\r\
  \ndXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQABERJUlRzcQB+AA0AAAAEc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAUdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQAC1BM\r\
  \nQVlFUl9IRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABt0AAxkaXNwbGF5LW5hbWV0\r\
  \nAAtza3VsbC1vd25lcnVxAH4ABgAAAARxAH4AH3QABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEi\r\
  \nOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1\r\
  \nbmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93Iiwi\r\
  \nYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnBy\r\
  \nb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpl\r\
  \neHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nl\r\
  \nc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRo\r\
  \ncmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRl\r\
  \neUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5\r\
  \nNXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRN\r\
  \nek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5q\r\
  \nT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADJ1cQB+\r\
  \nAAYAAAAEcQB+AAxzcQB+AA0AAA50dAAHRElBTU9ORHNxAH4ADQAAAAlzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADJ1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAKR0xB\r\
  \nU1NfUEFORXNxAH4ADQAAAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nABR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAANTkVUSEVSSVRFX0FYRXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAAVxAH4ACHEAfgAbcQB+ABx0AAtyZXBhaXItY29zdHEAfgAddXEAfgAGAAAABXEAfgAf\r\
  \ncQB+ACBzcQB+AAN1cQB+AAYAAAADcQB+AEN0AApTSUxLX1RPVUNIcQB+ACN1cQB+AAYAAAADc3EA\r\
  \nfgANAAAABXEAfgAncQB+ACZxAH4AJnNxAH4ADQAAAIRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADJ1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAEQkVFRnNxAH4ADQAA\r\
  \nABJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADJ1cQB+AAYAAAAEcQB+\r\
  \nAAxzcQB+AA0AAA50dAALU0VBX0xBTlRFUk5zcQB+AA0AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgAydXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQABVRPUkNIc3EA\r\
  \nfgANAAAAOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMnVxAH4ABgAA\r\
  \nAARxAH4ADHNxAH4ADQAADnR0AApPQUtfUExBTktTc3EAfgANAAAAC3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAA50dAAIT0FLX0JPQVRz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgAN\r\
  \nAAAOdHQABVNUSUNLc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAydXEA\r\
  \nfgAGAAAABHEAfgAMc3EAfgANAAAOdHEAfgClc3EAfgANAAAAFnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AMnVxAH4ABgAAAARxAH4ADHNxAH4ADQAADnRxAH4ANXEAfgCm\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAydXEAfgAGAAAABHEAfgAM\r\
  \nc3EAfgANAAAOdHEAfgA1cQB+AKZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ADJ1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50cQB+ADVxAH4ApnNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMnVxAH4ABgAAAARxAH4ADHNxAH4ADQAADnR0AARDT0FM\r\
  \ncQB+AEhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAM\r\
  \nc3EAfgANAAAOdHEAfgAuc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAy\r\
  \ndXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQAC09BS19TQVBMSU5HcQB+AEdzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADJ1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAH\r\
  \nT0FLX0xPR3NxAH4ADQAAABVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADJxAH4AFHVxAH4ABgAAAAVxAH4ADHNxAH4ADQAADnR0AAxXSElURV9CQU5ORVJxAH4AR3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAbcQB+AGR0AAlJdGVtRmxhZ3N0AAhwYXR0ZXJuc3Vx\r\
  \nAH4ABgAAAAVxAH4AH3QABkJBTk5FUnQAPXsidHJhbnNsYXRlIjoiYmxvY2subWluZWNyYWZ0Lm9t\r\
  \naW5vdXNfYmFubmVyIiwiY29sb3IiOiJnb2xkIn1zcQB+AHEAAAABdwQAAAABdAATSElERV9QT1RJ\r\
  \nT05fRUZGRUNUU3hzcgA2Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVMaXN0JFNl\r\
  \ncmlhbGl6ZWRGb3JtAAAAAAAAAAACAAFbAAhlbGVtZW50c3QAE1tMamF2YS9sYW5nL09iamVjdDt4\r\
  \ncHVxAH4ABgAAAAhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAVjb2xvcnQAB3BhdHRlcm51\r\
  \ncQB+AAYAAAADdAAHUGF0dGVybnQABENZQU50AAJtcnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgEFcQB+AQZ1cQB+AAYAAAADcQB+AQh0AApMSUdIVF9HUkFZdAACYnNzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAhxAH4BBXEAfgEGdXEAfgAGAAAAA3EAfgEIdAAER1JBWXQAAmNzc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AQVxAH4BBnVxAH4ABgAAAANxAH4BCHEAfgEPdAACYm9z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4BBXEAfgEGdXEAfgAGAAAAA3EAfgEIdAAFQkxB\r\
  \nQ0t0AAJtc3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgEFcQB+AQZ1cQB+AAYAAAADcQB+\r\
  \nAQhxAH4BD3QAAmhoc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AQVxAH4BBnVxAH4ABgAA\r\
  \nAANxAH4BCHEAfgEPdAACbWNzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4BBXEAfgEGdXEA\r\
  \nfgAGAAAAA3EAfgEIcQB+ASBxAH4BG3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAA50dAAMR0xBU1NfQk9UVExFc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAUdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQACENS\r\
  \nT1NTQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABtxAH4AHXQAB2NoYXJnZWR1cQB+\r\
  \nAAYAAAAEcQB+AB9xAH4BO3NxAH4ADQAAAXRzcgARamF2YS5sYW5nLkJvb2xlYW7NIHKA1Zz67gIA\r\
  \nAVoABXZhbHVleHAAcHBwcHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ABR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAbcQB+ABxxAH4AHXVxAH4ABgAAAARxAH4AH3QABUFSTU9Sc3EAfgAD\r\
  \ndXEAfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHEAfgAjdXEAfgAGAAAAAnEAfgBa\r\
  \ncQB+ACZzcQB+AA0AAACCc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAU\r\
  \ndXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQADUlST05fTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4AG3EAfgAccQB+AB11cQB+AAYAAAAEcQB+AB9xAH4BTnNyADdjb20uZ29v\r\
  \nZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAAAAAC\r\
  \nAAB4cQB+AAN1cQB+AAYAAAABcQB+ACN1cQB+AAYAAAABcQB+ACZzcQB+AA0AAACAc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAUdXEAfgAGAAAABHEAfgAMc3EAfgANAAAO\r\
  \ndHQAD0lST05fQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAbcQB+ABxx\r\
  \nAH4AHXVxAH4ABgAAAARxAH4AH3EAfgFOc3EAfgADdXEAfgAGAAAAAnEAfgFRcQB+ACN1cQB+AAYA\r\
  \nAAACcQB+AFpxAH4AJnNxAH4ADQAAAIhwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgAUdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAbcQB+AB10AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAfdAAL\r\
  \nVElMRV9FTlRJVFlzcQB+AA0AAAAUcQB+AXY=\r\n"
xp: 849.0
health: 20.39693260192871
hunger: 20
saturation: 9.536743E-7
location:
  world: world
  x: 11419.6
  y: 64.0
  z: 210.3
logType: QUIT
version: v1_20_R3
