inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nA3QAAj09dAABdnQABHR5cGV1cQB+AAYAAAADdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0\r\
  \nYWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcu\r\
  \nTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAxXQVRFUl9CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAFcQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50dAAEbWV0YXVxAH4ABgAAAAVxAH4ADHNxAH4ADQAA\r\
  \nDnR0AAtQTEFZRVJfSEVBRHNxAH4ADQAAAAJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAh0AAlt\r\
  \nZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVxAH4ABgAAAAR0AAhJdGVtTWV0\r\
  \nYXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVz\r\
  \nY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhy\r\
  \nb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVy\r\
  \nUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0\r\
  \naWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5M\r\
  \naW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1h\r\
  \ncAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAAC\r\
  \ndAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3\r\
  \nSW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFj\r\
  \nbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1lt\r\
  \nUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhwcHBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAG\r\
  \nQ0FSUk9Uc3EAfgANAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nFHVxAH4ABgAAAARxAH4ADHNxAH4ADQAADnR0AA1TV0VFVF9CRVJSSUVTc3EAfgANAAAABHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AFHVxAH4ABgAAAARxAH4ADHNxAH4A\r\
  \nDQAADnR0AAxST1RURU5fRkxFU0hzcQB+AA0AAAAFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgAVdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQAC0RJQU1PTkRfQVhFc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AB10AAZEYW1hZ2V1cQB+AAYAAAADcQB+ACF0AApV\r\
  \nTlNQRUNJRklDc3EAfgANAAAB+3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ABR1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAALU0VBX0xBTlRFUk5zcQB+AA0AAAAWc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAUdXEAfgAGAAAABHEAfgAMc3EA\r\
  \nfgANAAAOdHEAfgBccQB+ADtwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABV1cQB+AAYAAAAEcQB+AAxzcQB+AA0AAA50dAAKSVJP\r\
  \nTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAddAAIZW5jaGFudHNxAH4AU3Vx\r\
  \nAH4ABgAAAARxAH4AIXQABUFSTU9Sc3EAfgADdXEAfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJP\r\
  \nTk1FTlRBTHQACkRVUkFCSUxJVFl1cQB+AAYAAAACcQB+AEJzcQB+AA0AAAADc3EAfgANAAAAr3Nx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AFXVxAH4ABgAAAARxAH4ADHNx\r\
  \nAH4ADQAADnR0ABBESUFNT05EX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAB1xAH4AbHEAfgBTdXEAfgAGAAAABHEAfgAhcQB+AG5zcQB+AAN1cQB+AAYAAAACdAANQklORElO\r\
  \nR19DVVJTRXEAfgBxdXEAfgAGAAAAAnNxAH4ADQAAAAFxAH4AdHEAfgCEc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAVdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQAD0lS\r\
  \nT05fQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAdcQB+AGxxAH4AU3Vx\r\
  \nAH4ABgAAAARxAH4AIXEAfgBuc3EAfgADdXEAfgAGAAAAAnEAfgBxcQB+AHJ1cQB+AAYAAAACcQB+\r\
  \nAEJxAH4AdHNxAH4ADQAAALVwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgAVdXEAfgAGAAAABHEAfgAMc3EAfgANAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAdcQB+AFN0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAhdAALVElMRV9F\r\
  \nTlRJVFlzcQB+AA0AAAAxcQB+AJg=\r\n"
xp: 1039.0
health: 24.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 11414.4
  y: 65.0
  z: 209.6
logType: QUIT
version: v1_20_R3
