inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAAHc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAFnsidGV4dCI6\r\
  \nIsKnZUJhY2twYWNrIn1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnBy\r\
  \nb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpl\r\
  \neHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nl\r\
  \nc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRo\r\
  \ncmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRl\r\
  \neUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5\r\
  \nNXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRN\r\
  \nek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5q\r\
  \nT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA\r\
  \nA3EAfgAOc3EAfgAPAAAOdHQACE9BS19ET09Sc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nAAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAZTQURETEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAMUk9U\r\
  \nVEVOX0ZMRVNIc3EAfgAPAAAACnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAtESUFNT05EX0FYRXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHEAfgAXdAAGRGFtYWdldXEAfgAGAAAAA3EAfgAbdAAKVU5TUEVDSUZJQ3Nx\r\
  \nAH4ADwAAAftwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAG\r\
  \nAAAABHEAfgAOc3EAfgAPAAAOdHQACENST1NTQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAABnEAfgAI\r\
  \ncQB+ABd0AAhlbmNoYW50c3EAfgBLdAAHY2hhcmdlZHQAE2NoYXJnZWQtcHJvamVjdGlsZXN1cQB+\r\
  \nAAYAAAAGcQB+ABtxAH4AVHNxAH4AA3VxAH4ABgAAAAJ0AAhQSUVSQ0lOR3QACkRVUkFCSUxJVFl1\r\
  \ncQB+AAYAAAACc3EAfgAPAAAAAXEAfgBhc3EAfgAPAAABtXNyABFqYXZhLmxhbmcuQm9vbGVhbs0g\r\
  \ncoDVnPruAgABWgAFdmFsdWV4cAFzcQB+ACYAAAABdwQAAAABc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAVBUlJPV3hzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8A\r\
  \nAA50dAANU1dFRVRfQkVSUklFU3NxAH4ADwAAAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAJSVJPTl9ET09ScQB+ABNz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAP\r\
  \nAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARESVJUc3EAfgAPAAAAAnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0\r\
  \nAA9ESUFNT05EX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AF3EAfgBYcQB+\r\
  \nAEt1cQB+AAYAAAAEcQB+ABtxAH4ATXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09U\r\
  \nX0JPTlVTX0JMT0NLU3QAB01FTkRJTkdxAH4AX3VxAH4ABgAAAARzcQB+AA8AAAADcQB+AIVxAH4A\r\
  \nYXEAfgCWcQB+AIVwc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAA\r\
  \nAANxAH4ADnNxAH4ADwAADnR0AAtGSVJFX0NIQVJHRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnRxAH4AEnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+ABhxAH4AGXVxAH4ABgAAAARxAH4AG3EAfgAcdACSeyJ0\r\
  \nZXh0IjoiIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJp\r\
  \ndGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNv\r\
  \nbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4AIXEAfgAidXEAfgAGAAAAA3EAfgAkdAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRk\r\
  \nODg0NTMzc3EAfgAmAAAAAXcEAAAAAXNxAH4AKD9AAAAAAAAMdwgAAAAQAAAAAnEAfgArdAAIdGV4\r\
  \ndHVyZXNxAH4ALXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2\r\
  \nTHk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXda\r\
  \nak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9U\r\
  \nRmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAVCUkVBRHEAfgCFc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAO\r\
  \ndHQACkdMQVNTX1BBTkVxAH4AcnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA1ORVRIRVJJVEVfQVhFc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABXEAfgAIcQB+ABdxAH4AWHQAC3JlcGFpci1jb3N0cQB+AEt1cQB+AAYAAAAFcQB+\r\
  \nABtxAH4ATXNxAH4AA3VxAH4ABgAAAANxAH4AknQAClNJTEtfVE9VQ0hxAH4AX3VxAH4ABgAAAANz\r\
  \ncQB+AA8AAAAFcQB+AGFxAH4AlnEAfgCWc3EAfgAPAAAAhHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARCRUVGc3EAfgAP\r\
  \nAAAAEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADnNxAH4ADwAADnR0AAtTRUFfTEFOVEVSTnNxAH4ADwAAAEBzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFVE9SQ0hz\r\
  \ncQB+AA8AAAA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgAOc3EAfgAPAAAOdHQACk9BS19QTEFOS1NzcQB+AA8AAAALc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAhPQUtfQk9B\r\
  \nVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDnNxAH4ADwAADnR0AAVTVElDS3EAfgCFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHEAfgDZc3EAfgAPAAAAFnNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAA\r\
  \nDnR0AAZDQVJST1RxAH4A2nNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAdFTUVSQUxEc3EAfgAPAAAABHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnRx\r\
  \nAH4BAHEAfgDac3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgAOc3EAfgAPAAAOdHQABENPQUxzcQB+AA8AAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnRxAH4AfnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0\r\
  \nAAtPQUtfU0FQTElOR3EAfgCFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQAB09BS19MT0dzcQB+AA8AAAAVc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAO\r\
  \ndHQADEdMQVNTX0JPVFRMRXEAfgCFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHEAfgBUc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ABdxAH4AS3EAfgBZdXEAfgAGAAAABHEAfgAbcQB+AFRzcQB+AA8AAAF0c3EAfgBj\r\
  \nAHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDnNxAH4ADwAADnR0AAVTVUdBUnEAfgCFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQADlNQUlVDRV9TQVBMSU5HcQB+AJZz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5z\r\
  \ncQB+AA8AAA50dAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+\r\
  \nAFhxAH4AS3VxAH4ABgAAAARxAH4AG3QABUFSTU9Sc3EAfgADdXEAfgAGAAAAAnQAGFBST1RFQ1RJ\r\
  \nT05fRU5WSVJPTk1FTlRBTHEAfgBfdXEAfgAGAAAAAnEAfgEHcQB+AJZzcQB+AA8AAACvc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAP\r\
  \nAAAOdHQADUlST05fTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AF3EAfgBY\r\
  \ncQB+AEt1cQB+AAYAAAAEcQB+ABtxAH4BTXNyADdjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0Lklt\r\
  \nbXV0YWJsZUJpTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+AAYAAAABcQB+\r\
  \nAF91cQB+AAYAAAABcQB+AJZzcQB+AA8AAACpc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQAD0lST05fQ0hFU1RQTEFURXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+AFhxAH4AS3VxAH4ABgAAAARxAH4AG3EA\r\
  \nfgFNc3EAfgADdXEAfgAGAAAAAnEAfgFQcQB+AF91cQB+AAYAAAACcQB+AQdxAH4AlnNxAH4ADwAA\r\
  \nALVwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAABHEA\r\
  \nfgAOc3EAfgAPAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+\r\
  \nAEt0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAbdAALVElMRV9FTlRJVFlzcQB+AA8AAAAx\r\
  \ncQB+AXU=\r\n"
xp: 1039.0
health: 24.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 11413.8
  y: 65.0
  z: 207.5
logType: QUIT
version: v1_20_R3
