texture: bd3a1436e0fd5f3e4d113a092c1d07a12e22d426c50183ccd62877d9cd885fbd
name: '&6Orange LuckyBlock'
lore:
- '&7Place me :D'
eco: true
shop: true
price: 250
animation: true
animation_type: MOBSPAWNER_FLAMES
craft:
  default: true
  custom: false
drop:
  '0':
  - 'ITEM : SMOOTH_RED_SANDSTONE : 64 : 0'
  - 'ITEM : BROWN_CONCRETE_POWDER : 8 : 0'
  - 'ENTITY : PILLAGER : 2'
  '1':
  - 'LUCKY_BLOCK_ITEM : ORANGE : 3'
  - 'SPECIAL : WATER_BUCKET : 64'
  - 'ENTITY : HORSE : 1'
  - 'ENTITY : GLOW_ITEM_FRAME : 2'
  '2':
  - 'SPECIAL : EXPERIENCE_EXPLOSION : 45'
  '3':
  - 'ITEM : STRUCTURE_VOID : 32 : 0'
  - 'SPECIAL : TNT_EXPLOSION : 20'
  '4':
  - 'ENTITY : FROG : 4'
  - 'SPECIAL : EXPERIENCE_EXPLOSION : 45'
  '5':
  - 'ITEM : COMPOSTER : 16 : 0'
  - 'ENTITY : GHAST : 4'
  - 'ITEM : CHERRY_LOG : 16 : 0'
  '6':
  - 'ITEM : LEATHER_LEGGINGS : 1 : 0'
  - 'ENTITY : RAVAGER : 4'
  '7':
  - 'ENTITY : SHEEP : 4'
  - 'ITEM : STRIPPED_MANGROVE_LOG : 16 : 0'
  - 'LUCKY_BLOCK_ITEM : RED : 3'
  - 'ENTITY : ZOMBIE_VILLAGER : 1'
  '8':
  - 'ENTITY : ZOMBIFIED_PIGLIN : 1'
  - 'SPECIAL : EXPERIENCE_EXPLOSION : 45'
  - 'ITEM : LIGHT_GRAY_CARPET : 64 : 0'
  '9':
  - 'SPECIAL : EXPERIENCE_EXPLOSION : 45'
  '10':
  - 'ITEM : SKELETON_SKULL : 16 : 0'
  - 'SPECIAL : TNT_EXPLOSION : 20'
  - 'ITEM : CLAY_BALL : 49 : 0'
  '11':
  - 'ENTITY : PANDA : 2'
  - 'ITEM : GRAY_CONCRETE_POWDER : 16 : 0'
  '12':
  - 'ITEM : EVOKER_SPAWN_EGG : 64 : 0'
  - 'SPECIAL : WATER_BUCKET : 64'
  - 'ITEM : BEETROOT_SOUP : 1 : 0'
  '13':
  - 'ITEM : MAGENTA_STAINED_GLASS : 64 : 0'
  - 'ITEM : PUFFERFISH_SPAWN_EGG : 19 : 0'
  - 'ITEM : NETHERITE_LEGGINGS : 1 : 0'
  '14':
  - 'ENTITY : TRADER_LLAMA : 4'
  - 'ENTITY : COD : 3'
  '15':
  - 'ITEM : HORN_CORAL : 32 : 0'
  - 'ENTITY : GIANT : 2'
  - 'ITEM : BIRCH_PLANKS : 16 : 0'
  '16':
  - 'ENTITY : SILVERFISH : 4'
  - 'ENTITY : PARROT : 3'
  - 'SPECIAL : WATER_BUCKET : 64'
  '17':
  - 'ITEM : STRIPPED_CHERRY_LOG : 16 : 0'
  '18':
  - 'ITEM : BOOK : 35 : 0'
  - 'ITEM : CHERRY_FENCE_GATE : 32 : 0'
  - 'ENTITY : EVOKER_FANGS : 3'
  '19':
  - 'ENTITY : WITHER_SKELETON : 4'
  '20':
  - 'ENTITY : FIREBALL : 1'
  '21':
  - 'ENTITY : ZOMBIE : 4'
  - 'SPECIAL : EXPERIENCE_EXPLOSION : 45'
  '22':
  - 'ENTITY : GHAST : 3'
  '23':
  - 'ITEM : SANDSTONE_SLAB : 32 : 0'
  - 'ITEM : PAPER : 29 : 0'
  '24':
  - 'SPECIAL : TNT_COLUMN : 5'
  '25':
  - 'LUCKY_BLOCK_ITEM : BLUE : 3'
  - 'LUCKY_BLOCK_ITEM : PURPLE : 1'
  - 'ENTITY : RAVAGER : 2'
  '26':
  - 'LUCKY_BLOCK_ITEM : CYAN : 3'
  - 'ITEM : WARPED_SLAB : 8 : 0'
  '27':
  - 'ENTITY : BLAZE : 4'
  - 'ITEM : FISHING_ROD : 1 : 0'
  '28':
  - 'SPECIAL : WATER_BUCKET : 64'
  '29':
  - 'ITEM : GRANITE_WALL : 32 : 0'
  - 'ENTITY : AXOLOTL : 3'
  '30':
  - 'ITEM : MOSSY_COBBLESTONE_SLAB : 16 : 0'
  - 'ENTITY : STRAY : 4'
  '31':
  - 'ITEM : PIGLIN_HEAD : 64 : 0'
  - 'ITEM : NETHER_STAR : 17 : 0'
  '32':
  - 'ENTITY : MARKER : 3'
  '33':
  - 'ENTITY : LEASH_HITCH : 1'
  - 'ENTITY : ALLAY : 3'
  - 'ITEM : DAMAGED_ANVIL : 8 : 0'
  - 'SPECIAL : TNT_EXPLOSION : 20'
  '34':
  - 'ITEM : FIRE_CORAL_BLOCK : 64 : 0'
  - 'ENTITY : SMALL_FIREBALL : 2'
  '35':
  - 'SPECIAL : TNT_EXPLOSION : 20'
  - 'ITEM : JUNGLE_PLANKS : 8 : 0'
  '36':
  - 'ENTITY : SPIDER : 1'
  - 'SPECIAL : LIGHTNING : 3'
  '37':
  - 'ITEM : STRIPPED_CRIMSON_HYPHAE : 8 : 0'
  - 'ENTITY : MINECART_MOB_SPAWNER : 1'
  '38':
  - 'ENTITY : CAT : 1'
  '39':
  - 'ITEM : TUBE_CORAL_BLOCK : 32 : 0'
  - 'ITEM : GRAY_CONCRETE : 32 : 0'
  '40':
  - 'ENTITY : DOLPHIN : 4'
  - 'ITEM : BAMBOO_MOSAIC : 16 : 0'
  '41':
  - 'ITEM : STRIPPED_WARPED_STEM : 8 : 0'
  - 'LUCKY_BLOCK_ITEM : RANDOM : 4'
  '42':
  - 'ENTITY : MINECART : 4'
  - 'ITEM : LIME_DYE : 11 : 0'
  - 'ITEM : WHITE_WOOL : 32 : 0'
