inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRv\r\
  \ncnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBq\r\
  \nYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AANDT0RzcQB+AA4AAAARc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxS\r\
  \nT1RURU5fRkxFU0hzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKUFVGRkVSRklTSHNxAH4ADgAAAAJzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAEbWV0YXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAZQT1RJT05zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAtwb3Rpb24t\r\
  \ndHlwZXVxAH4ABgAAAAN0AAhJdGVtTWV0YXEAfgAmdAAPbWluZWNyYWZ0OndhdGVyc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQABlNBTE1PTnNxAH4ADgAAAAVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ACN1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANTEVBVEhFUl9CT09UU3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAqdAAGRGFtYWdldXEAfgAGAAAAA3EAfgAtdAAPQ09MT1JBQkxF\r\
  \nX0FSTU9Sc3EAfgAOAAAAP3Bwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgAjdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0ZJU0hJTkdfUk9Ec3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+ACpxAH4AP3VxAH4ABgAAAANxAH4ALXQAClVOU1BFQ0lGSUNzcQB+AA4A\r\
  \nAAA2cHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=\r\n"
xp: 126.0
health: 4.5
hunger: 9
saturation: 0.8000001
location:
  world: world
  x: 875.6
  y: 63.0
  z: 664.2
logType: JOIN
version: v1_20_R3
