inventory: "rO0ABXcEAAAAKXBwcHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAAD\r\
  \nbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11\r\
  \ndGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09i\r\
  \namVjdDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhw\r\
  \nAAAABHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZl\r\
  \nbnRvcnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhy\r\
  \nABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAVUT1JDSHNxAH4ADgAAAAxzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAEbWV0YXVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAlt\r\
  \nZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0AApVTlNQRUNJRklDc3EAfgAO\r\
  \nAAAAMnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AFnVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAdcQB+AB51cQB+AAYAAAADcQB+ACBxAH4AIXNxAH4ADgAAAD1zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABZ1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALUExBWUVS\r\
  \nX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AHXQADGRpc3BsYXktbmFtZXQAC3Nr\r\
  \ndWxsLW93bmVydXEAfgAGAAAABHEAfgAgdAAFU0tVTEx0AJJ7InRleHQiOiIiLCJleHRyYSI6W3si\r\
  \ndGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2UsInVuZGVy\r\
  \nbGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ciLCJib2xk\r\
  \nIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAKcHJvcGVy\r\
  \ndGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEt\r\
  \nMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAA\r\
  \nAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2FjY2Vzc09y\r\
  \nZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNo\r\
  \nb2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQAtGV5SjBa\r\
  \nWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFX\r\
  \nNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1Rn\r\
  \nNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5\r\
  \nZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAhQT1JLQ0hPUHNxAH4ADgAAAApzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALQ09PS0VE\r\
  \nX0JFRUZzcQB+AA4AAAAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AFnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AHXEAfgAedAANYmxvY2tNYXRl\r\
  \ncmlhbHVxAH4ABgAAAARxAH4AIHQAC1RJTEVfRU5USVRZc3EAfgAOAAAAknEAfgBg\r\n"
xp: 141.0
health: 17.330886840820312
hunger: 17
saturation: 0.0
location:
  world: world
  x: 709.3
  y: 37.0
  z: 686.4
logType: JOIN
version: v1_20_R3
