inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JD\r\
  \nSHNxAH4ADgAAAD5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAADQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+\r\
  \nABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0AA5B\r\
  \nUlJPV19JTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ACFxAH4A\r\
  \nInEAfgA4c3EAfgAOAAAAmnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFORVRIRVJJVEVfUElDS0FYRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AB1xAH4AM3QAClNJTEtfVE9VQ0hxAH4AH3VxAH4ABgAAAARxAH4A\r\
  \nIXEAfgA4cQB+ADhxAH4AInEAfgAic3EAfgAOAAAA6HNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAIU1BZR0xBU1NzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAANR09MREVOX0NBUlJPVHEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA8cQB+AAt1cQB+AAYAAAAFcQB+AA1zcQB+AA4AAA50dAAPRklSRVdPUktfUk9DS0VUc3EA\r\
  \nfgAOAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAFcG93ZXJ1cQB+AAYAAAAD\r\
  \ncQB+ABl0AAhGSVJFV09SS3EAfgA4cHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4AAAAQ\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgA/c3EAfgAOAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJ\r\
  \ncQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAALTkVUSEVSX1NUQVJzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAF\r\
  \nQVJST1dzcQB+AA4AAAA1c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
  \nBgAAAANxAH4ADXNxAH4ADgAADnR0AAdPQUtfTE9Hc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgAac3EA\r\
  \nfgADdXEAfgAGAAAAAnEAfgAzcQB+AB91cQB+AAYAAAACcQB+ADhxAH4AInEAfgAicHBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nB0ZVUk5BQ0VwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKSVJPTl9JTkdPVHNxAH4ADgAAAAZwc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxXQVRF\r\
  \nUl9CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHEAfgC4cHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAE\r\
  \ncQB+ABl0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJv\r\
  \nYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlr\r\
  \nZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBs\r\
  \nYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2\r\
  \nYS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0\r\
  \naWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhh\r\
  \nc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQ\r\
  \nAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxP\r\
  \nSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxl\r\
  \nSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9H\r\
  \nSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4cHBwcHBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AGtxAH4AcnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AP3NxAH4ADgAAACpwc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhF\r\
  \nUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4A\r\
  \nBgAAAARxAH4AGXQABUFSTU9Sc3EAfgADdXEAfgAGAAAABHQADURFUFRIX1NUUklERVJxAH4AM3QA\r\
  \nGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHEAfgAfdXEAfgAGAAAABHEAfgAicQB+ADhzcQB+AA4A\r\
  \nAAAEcQB+ACJzcQB+AA4AAAAPc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3NxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+\r\
  \nAPJzcQB+AAN1cQB+AAYAAAADcQB+ADNxAH4A9nEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+APhxAH4A\r\
  \nInNxAH4ADgAAAAdxAH4AN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABRORVRIRVJJVEVfQ0hFU1RQTEFURXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgDyc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAzcQB+APZxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgD4cQB+ACJxAH4B\r\
  \nB3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAI\r\
  \ncQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4A8nNxAH4AA3VxAH4ABgAAAANx\r\
  \nAH4AM3EAfgD2cQB+AB91cQB+AAYAAAADcQB+ADhxAH4A+HEAfgAicQB+AQdzcQB+AA4AAAARc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABd0AA1i\r\
  \nbG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAZdAALVElMRV9FTlRJVFlzcQB+AA4AAABbcQB+ASg=\r\
  \n"
xp: 1318.0
health: 26.0
hunger: 20
saturation: 10.400001
location:
  world: world
  x: 11429.9
  y: 64.1
  z: 221.3
logType: QUIT
version: v1_20_R3
