inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0cQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4AGnNxAH4AA3VxAH4ABgAAAAZ0AAlLTk9DS0JBQ0t0AA9MT09UX0JPTlVTX01PQlN0AAdN\r\
  \nRU5ESU5HdAANREFNQUdFX1VOREVBRHQADVNXRUVQSU5HX0VER0VxAH4AH3VxAH4ABgAAAAZzcQB+\r\
  \nAA4AAAACcQB+ACJzcQB+AA4AAAABcQB+ACFxAH4AInEAfgAicQB+ACJzcQB+AA4AAAAJc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AAVUT1JDSHNxAH4ADgAAAD5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAADQk9Xc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4A\r\
  \nA3VxAH4ABgAAAAN0AA5BUlJPV19JTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAA\r\
  \nA3EAfgA4cQB+ACFxAH4AInEAfgA4c3EAfgAOAAAAmnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFORVRIRVJJVEVfUElD\r\
  \nS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAG\r\
  \nAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAAEcQB+AB1xAH4AM3QAClNJTEtfVE9VQ0hxAH4A\r\
  \nH3VxAH4ABgAAAARxAH4AIXEAfgA4cQB+ADhxAH4AInEAfgAic3EAfgAOAAAA6HNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAIU1BZ\r\
  \nR0xBU1NzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAAGQ0FSUk9Uc3EAfgAOAAAAMnNxAH4AAHNxAH4AA3VxAH4ABgAAAAVx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4APXEAfgALdXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHQAD0ZJUkVX\r\
  \nT1JLX1JPQ0tFVHNxAH4ADgAAACtzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQABXBv\r\
  \nd2VydXEAfgAGAAAAA3EAfgAZdAAIRklSRVdPUktxAH4AOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JP\r\
  \nRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARxAH4A\r\
  \nGXEAfgAac3EAfgADdXEAfgAGAAAAA3QABExVQ0t0AARMVVJFcQB+AB91cQB+AAYAAAADcQB+ACJx\r\
  \nAH4AInEAfgAic3EAfgAOAAAADHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4AAAAQc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA9dXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHEAfgBAc3EAfgAOAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4APXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApQVUZGRVJGSVNIcQB+ACFzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAFQVJST1dzcQB+AA4AAAApc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA9dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAB09BS19MT0dzcQB+AA4AAAAOc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAFE5FVEhFUklURV9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAADcQB+ADN0\r\
  \nABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AH3VxAH4ABgAAAANxAH4AOHNxAH4ADgAAAARx\r\
  \nAH4AInNxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAJR1VOUE9XREVScQB+ALtzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAB0VNRVJBTERz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAO\r\
  \nAAAOdHQAB0ZVUk5BQ0VzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AMJzcQB+AA4AAABAcHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAOTkFVVElMVVNf\r\
  \nU0hFTExzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAAKSVJPTl9JTkdPVHNxAH4ADgAAAAZzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AFdzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4A\r\
  \nGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAecQB+ADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAi\r\
  \ncQB+ADhxAH4AInNxAH4ADgAAAMxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAK\r\
  \ndXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50cQB+APRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AD11cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAHRElBTU9ORHEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA9cQB+AAt1cQB+AAYAAAAFcQB+AA1zcQB+AA4AAA50dAALUExBWUVSX0hFQURxAH4AN3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1\r\
  \ncQB+AAYAAAAEcQB+ABl0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFj\r\
  \na3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFs\r\
  \nc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAG\r\
  \nAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1\r\
  \nMzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNy\r\
  \nABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2\r\
  \nYS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAA\r\
  \nAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJ\r\
  \nNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1\r\
  \nYm1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdO\r\
  \nelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQADkdPTERFTl9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVx\r\
  \nAH4AFnVxAH4ABgAAAANxAH4AGXEAfgAac3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1t\r\
  \ndXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAFxAH4A\r\
  \nHXVxAH4ABgAAAAFxAH4AIXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApDT09LRURfQ09Ec3EAfgAOAAAACHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAP\r\
  \nRkxJTlRfQU5EX1NURUVMcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA9dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBAc3EAfgAOAAAAKnNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAxH\r\
  \nT0xERU5fQVBQTEVxAH4AN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ORVRIRVJJVEVfQk9PVFNzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgC2c3EA\r\
  \nfgADdXEAfgAGAAAABHQADURFUFRIX1NUUklERVJxAH4AM3EAfgC5cQB+AB91cQB+AAYAAAAEcQB+\r\
  \nACJxAH4AOHEAfgC7cQB+ACJzcQB+AA4AAAAPc3EAfgAOAAAAG3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABJORVRIRVJJ\r\
  \nVEVfTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4A\r\
  \nF3VxAH4ABgAAAAVxAH4AGXEAfgC2c3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+ALlxAH4AH3VxAH4A\r\
  \nBgAAAANxAH4AOHEAfgC7cQB+ACJxAH4AvHEAfgEzc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAACcQB+ADNxAH4AH3VxAH4ABgAAAAJxAH4AOHEAfgAicQB+ACJxAH4A\r\
  \ndHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ALZzcQB+AAN1cQB+AAYAAAADcQB+ADNx\r\
  \nAH4AuXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ALtxAH4AInEAfgC8c3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVM\r\
  \nRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABd0AA1ibG9ja01hdGVyaWFsdXEA\r\
  \nfgAGAAAABHEAfgAZdAALVElMRV9FTlRJVFlzcQB+AA4AAABbcQB+AYI=\r\n"
xp: 1618.0
health: 25.296302795410156
hunger: 17
saturation: 0.0
location:
  world: world
  x: 18733.6
  y: 74.0
  z: -105.1
logType: QUIT
version: v1_20_R3
