inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4AFXQACGVuY2hhbnRzdAALcmVwYWlyLWNvc3R0AAZEYW1hZ2V1cQB+AAYAAAAFcQB+ABl0\r\
  \nAApVTlNQRUNJRklDc3EAfgADdXEAfgAGAAAABHQACURJR19TUEVFRHQAB01FTkRJTkd0AApTSUxL\r\
  \nX1RPVUNIdAAKRFVSQUJJTElUWXVxAH4ABgAAAARzcQB+AA4AAAAFc3EAfgAOAAAAAXEAfgBDc3EA\r\
  \nfgAOAAAAA3EAfgBEc3EAfgAOAAAA9XNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ORVRIRVJJVEVfU1dPUkRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgA2cQB+ADd1cQB+AAYAAAAEcQB+ABlxAH4AOnNx\r\
  \nAH4AA3VxAH4ABgAAAAZ0AAlLTk9DS0JBQ0t0AA9MT09UX0JPTlVTX01PQlNxAH4APnQADURBTUFH\r\
  \nRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AEB1cQB+AAYAAAAGc3EAfgAOAAAAAnEAfgBEcQB+\r\
  \nAENxAH4AQnEAfgBEcQB+AERxAH4ARHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMR0xBU1NfQk9UVExFc3EAfgAO\r\
  \nAAAADXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAdFTUVSQUxEc3EAfgAOAAAAJnNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANCT1dzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+ADdxAH4AOHVxAH4ABgAAAAVxAH4AGXEA\r\
  \nfgA6c3EAfgADdXEAfgAGAAAAA3QADkFSUk9XX0lORklOSVRFdAAMQVJST1dfREFNQUdFcQB+AEB1\r\
  \ncQB+AAYAAAADcQB+AENxAH4AQnEAfgBEcQB+AENzcQB+AA4AAACsc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJPT0tz\r\
  \ncQB+AA4AAAAxc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQAC0RJQU1PTkRfQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EA\r\
  \nfgAIcQB+ABVxAH4AOHVxAH4ABgAAAANxAH4AGXEAfgA6c3EAfgAOAAAA2nNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1H\r\
  \nT0xERU5fQ0FSUk9Uc3EAfgAOAAAAN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRIRVJSQUNLc3EAfgAOAAAAJXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AApJUk9OX0lOR09UcQB+AEJwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADh0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAZ\r\
  \ndAALVElMRV9FTlRJVFlzcQB+AA4AAABbcQB+AKJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAORU5DSEFOVEVEX0JPT0tz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQAD3N0b3JlZC1lbmNoYW50c3VxAH4ABgAA\r\
  \nAANxAH4AGXQACUVOQ0hBTlRFRHNyADdjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJs\r\
  \nZUJpTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+AAYAAAABcQB+AD51cQB+\r\
  \nAAYAAAABcQB+AENzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0\r\
  \nZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJs\r\
  \naW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQi\r\
  \nOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AB9xAH4AIHVxAH4ABgAAAANx\r\
  \nAH4AInQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NxAH4AJAAAAAF3BAAA\r\
  \nAAFzcQB+ACY/QAAAAAAADHcIAAAAEAAAAAJxAH4AKXQACHRleHR1cmVzcQB+ACt0ALRleUowWlho\r\
  \nMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVs\r\
  \nWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRP\r\
  \nR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZY\r\
  \nMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA/c3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNUUklOR3EAfgBX\r\
  \ncHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAtESUFNT05EX0hPRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ADZxAH4AOHVxAH4ABgAAAARxAH4AGXEAfgA6c3EAfgC2dXEAfgAGAAAAAXEAfgA9dXEAfgAG\r\
  \nAAAAAXNxAH4ADgAAAARzcQB+AA4AAADhc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJPTkVxAH4AV3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAZFTFlUUkFzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+ADdxAH4AOHVx\r\
  \nAH4ABgAAAAVxAH4AGXEAfgA6c3EAfgADdXEAfgAGAAAAAnEAfgA+cQB+AEB1cQB+AAYAAAACcQB+\r\
  \nAENxAH4ARHEAfgBEc3EAfgAOAAAATnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4Ar3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAVcQB+ALN1cQB+AAYAAAADcQB+ABlxAH4AtXNxAH4AtnVxAH4ABgAAAAFxAH4A\r\
  \nPnVxAH4ABgAAAAFxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4Ar3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAVcQB+ALN1cQB+AAYAAAADcQB+ABlxAH4AtXNxAH4AtnVxAH4ABgAAAAFxAH4APnVxAH4A\r\
  \nBgAAAAFxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAlHVU5QT1dERVJzcQB+AA4AAAAGc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhTUFlHTEFT\r\
  \nU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AApTUElERVJfRVlFc3EAfgAOAAAAFnNxAH4AAHNxAH4AA3VxAH4ABgAAAAVx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AW3EAfgALdXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHQAD0ZJUkVX\r\
  \nT1JLX1JPQ0tFVHNxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQABXBv\r\
  \nd2VydXEAfgAGAAAAA3EAfgAZdAAIRklSRVdPUktxAH4AQ3BzcQB+AABzcQB+AAN1cQB+AAYAAAAF\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AFtxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnRxAH4BLnNx\r\
  \nAH4ADgAAAB1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgEzdXEAfgAGAAAAA3EA\r\
  \nfgAZcQB+ATVxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdMRUNURVJOcQB+AEJzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJf\r\
  \nUEVBUkxzcQB+AA4AAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCvc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAI\r\
  \ncQB+ABVxAH4As3VxAH4ABgAAAANxAH4AGXEAfgC1c3EAfgC2dXEAfgAGAAAAAXEAfgA+dXEAfgAG\r\
  \nAAAAAXEAfgBDc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAOnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4Ar3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ALN1cQB+AAYAAAADcQB+ABlxAH4AtXNxAH4A\r\
  \ntnVxAH4ABgAAAAFxAH4APnVxAH4ABgAAAAFxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4Ar3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ALN1cQB+AAYAAAADcQB+ABlxAH4AtXNxAH4AtnVxAH4A\r\
  \nBgAAAAFxAH4APnVxAH4ABgAAAAFxAH4AQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AW3EAfgALdXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHEAfgEucQB+AS9zcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgEzdXEAfgAGAAAAA3EAfgAZcQB+ATVxAH4AQ3Nx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AA9ORVRIRVJJVEVfQk9PVFNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgA2cQB+ADd1cQB+AAYAAAAEcQB+ABl0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAR0AA1ERVBU\r\
  \nSF9TVFJJREVScQB+AD50ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AQHVxAH4ABgAAAARx\r\
  \nAH4ARHEAfgBDcQB+AOdxAH4ARHNxAH4ADgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJ\r\
  \nTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4ANnEAfgA3dXEAfgAGAAAABHEA\r\
  \nfgAZcQB+AYtzcQB+AAN1cQB+AAYAAAADcQB+AD5xAH4Bj3EAfgBAdXEAfgAGAAAAA3EAfgBDcQB+\r\
  \nAOdxAH4ARHNxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgA2cQB+ADd1cQB+AAYAAAAEcQB+ABlxAH4Bi3Nx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4APnEAfgGPcQB+AEB1cQB+AAYAAAADcQB+AENxAH4A53EAfgBEcQB+\r\
  \nAZ9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAVcQB+ADZxAH4AN3VxAH4ABgAAAARxAH4AGXEAfgGLc3EAfgADdXEAfgAGAAAABHEAfgA+\r\
  \ncQB+AY90AAZPWFlHRU5xAH4AQHVxAH4ABgAAAARxAH4AQ3EAfgDncQB+AERxAH4ARHEAfgGRcA==\r\
  \n"
xp: 1397.0
health: 22.380002975463867
hunger: 17
saturation: 0.0
location:
  world: world
  x: 11418.6
  y: 64.0
  z: 207.1
logType: QUIT
version: v1_20_R3
