inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAAEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAFnsidGV4dCI6\r\
  \nIsKnZUJhY2twYWNrIn1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnBy\r\
  \nb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpl\r\
  \neHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nl\r\
  \nc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRo\r\
  \ncmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRl\r\
  \neUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5\r\
  \nNXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRN\r\
  \nek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5q\r\
  \nT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+\r\
  \nAAYAAAAEcQB+AA5zcQB+AA8AAA50dAAQRElBTU9ORF9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAXdAAIZW5jaGFudHN1cQB+AAYAAAADcQB+ABt0AAVBUk1PUnNxAH4AA3Vx\r\
  \nAH4ABgAAAAJ0AA1CSU5ESU5HX0NVUlNFdAAKRFVSQUJJTElUWXVxAH4ABgAAAAJzcQB+AA8AAAAB\r\
  \nc3EAfgAPAAAAA3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4A\r\
  \nBgAAAARxAH4ADnNxAH4ADwAADnR0AA5FTkNIQU5URURfQk9PS3NxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAXdAAPc3RvcmVkLWVuY2hhbnRzdXEAfgAGAAAAA3EAfgAbdAAJRU5DSEFOVEVE\r\
  \nc3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZv\r\
  \ncm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAF0ABVQUk9URUNUSU9OX0VYUExPU0lPTlN1cQB+\r\
  \nAAYAAAABcQB+ABNzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA\r\
  \nA3EAfgAOc3EAfgAPAAAOdHQABExFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAGUE9USU9Oc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+ABd0AAtwb3Rpb24tdHlwZXVxAH4ABgAAAANxAH4AG3EAfgBedAAdbWlu\r\
  \nZWNyYWZ0OnN0cm9uZ19yZWdlbmVyYXRpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50cQB+AF5zcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4AF3EAfgBidXEAfgAGAAAAA3EAfgAbcQB+AF50AB1taW5lY3JhZnQ6c3Ry\r\
  \nb25nX3JlZ2VuZXJhdGlvbnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AApORVRIRVJSQUNLc3EAfgAPAAAAQHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAA\r\
  \nDnR0AAtESUFNT05EX0hPRXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+ADh0AAZE\r\
  \nYW1hZ2V1cQB+AAYAAAAEcQB+ABt0AApVTlNQRUNJRklDc3EAfgBOdXEAfgAGAAAAAXQACURJR19T\r\
  \nUEVFRHVxAH4ABgAAAAFxAH4AE3NxAH4ADwAAAN9zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAPAAAOdHQABUJSRUFEc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHEAfgB0\r\
  \nc3EAfgAPAAAADXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADnNxAH4ADwAADnR0AARCT09Lc3EAfgAPAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA5BTUVUSFlT\r\
  \nVF9TSEFSRHEAfgATc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABENPQUxzcQB+AA8AAAAQc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAdGVVJOQUNFc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAABHEAfgAOc3EA\r\
  \nfgAPAAAOdHEAfgASc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABdxAH4AGHEAfgAZdXEA\r\
  \nfgAGAAAABHEAfgAbcQB+ABx0AJJ7InRleHQiOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNr\r\
  \nIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJz\r\
  \ndHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAhcQB+ACJ1cQB+AAYAAAADcQB+ACR0ACRlZDU3ZWJj\r\
  \nNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcQB+ACYAAAABdwQAAAABc3EAfgAoP0AAAAAA\r\
  \nAAx3CAAAABAAAAACcQB+ACt0AAh0ZXh0dXJlc3EAfgAtdAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRT\r\
  \nMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwz\r\
  \nUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpV\r\
  \nNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAO\r\
  \ndHQABVRPUkNIcQB+ABNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAARRVhQRVJJRU5DRV9CT1RUTEVxAH4AQXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAG\r\
  \nU0FERExFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAGAAAA\r\
  \nBHEAfgAOc3EAfgAPAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAX\r\
  \ncQB+AH90AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAbdAALVElMRV9FTlRJVFlzcQB+AA8A\r\
  \nAABbcQB+ANdwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\r\n"
xp: 1268.0
health: 26.0
hunger: 20
saturation: 2.0
location:
  world: world
  x: 11425.4
  y: 64.0
  z: 211.1
logType: QUIT
version: v1_20_R3
