inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JD\r\
  \nSHNxAH4ADgAAAD5zcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+ADxxAH4A\r\
  \nC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRzcQB+AA4AAAAGc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4AGXQACEZJ\r\
  \nUkVXT1JLcQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAac3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAdcQB+ADN0AApTSUxLX1RPVUNIcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4A\r\
  \nOHEAfgA4cQB+ACJxAH4AInNxAH4ADgAAAOhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nCXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHBzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAGQ0FSUk9Uc3EAfgAOAAAAO3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEA\r\
  \nfgAGAAAAA3QABExVQ0t0AARMVVJFcQB+AB91cQB+AAYAAAADcQB+ACJxAH4AInEAfgAic3EAfgAO\r\
  \nAAAADHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AARESVJUcQB+ACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4A\r\
  \nAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHEAfgA/c3EAfgAOAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApQVUZGRVJGSVNIc3EAfgAO\r\
  \nAAAABHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAVBUlJPV3NxAH4ADgAAAClzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHT0FLX0xPR3NxAH4A\r\
  \nDgAAABNzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+ADxxAH4AC3VxAH4A\r\
  \nBgAAAAVxAH4ADXNxAH4ADgAADnR0AAVDSEVTVHEAfgA3c3EAfgAAc3EAfgADdXEAfgAGAAAABXEA\r\
  \nfgAIcQB+ABV0AAxkaXNwbGF5LW5hbWV0ABJQdWJsaWNCdWtraXRWYWx1ZXN0AA1ibG9ja01hdGVy\r\
  \naWFsdXEAfgAGAAAABXEAfgAZdAALVElMRV9FTlRJVFl0ACJ7InRleHQiOiIiLCJleHRyYSI6WyJF\r\
  \nbnRpdHlQYWNrIl19dAA8ewogICAgImZpc2hyZXdhcmRzOmV4YW1wbGVlbnRpdHlwYWNrIjogIkV4\r\
  \nYW1wbGVFbnRpdHlQYWNrIgp9cQB+AKdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAJR1VOUE9XREVScQB+ACJzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKQ09PS0VEX0NPRHNxAH4ADgAAAAhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nCXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAB0ZVUk5BQ0VzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+ALdz\r\
  \ncQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANx\r\
  \nAH4ADXNxAH4ADgAADnR0AA1UUklQV0lSRV9IT09Lc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAI\r\
  \ncQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AA5OQVVUSUxVU19TSEVMTHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AApPQUtfUExBTktTcQB+ADdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AFNzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4AHXEAfgAecQB+ADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAicQB+ADhxAH4AInNxAH4A\r\
  \nDgAAAMxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgBic3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCnc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAI\r\
  \ncQB+ABVxAH4Aq3EAfgCscQB+AK11cQB+AAYAAAAFcQB+ABlxAH4Ar3QAIXsidGV4dCI6IiIsImV4\r\
  \ndHJhIjpbIml0ZW1zUGFjayJdfXQAOnsKICAgICJmaXNocmV3YXJkczpleGFtcGxlaXRlbXNwYWNr\r\
  \nIjogIkV4YW1wbGVJdGVtc1BhY2siCn1xAH4Ap3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABRORVRIRVJJVEVfQ0hFU1RQ\r\
  \nTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAG\r\
  \nAAAABXEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAADcQB+ADN0ABhQUk9URUNUSU9OX0VOVklS\r\
  \nT05NRU5UQUxxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgCTcQB+ACJzcQB+AA4AAAAHc3EAfgAOAAAA\r\
  \nDXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+AKt0AAtza3VsbC1vd25lcnVxAH4ABgAAAARxAH4AGXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwi\r\
  \nZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZh\r\
  \nbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVs\r\
  \nbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJ\r\
  \nZHQACnByb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUt\r\
  \nM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJ\r\
  \nAARzaXpleHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFa\r\
  \nAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3Rv\r\
  \nckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFs\r\
  \ndWV0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgw\r\
  \nZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhO\r\
  \nREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlU\r\
  \nUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ABVxAH4AF3EAfgCtdXEAfgAGAAAABHEAfgAZcQB+AK9zcQB+AA4AAABbcQB+AS5w\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4A\r\
  \nDgAADnR0AA9GTElOVF9BTkRfU1RFRUxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEA\r\
  \nfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADEdMQVNTX0JPVFRMRXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANC\r\
  \nT1dzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAA\r\
  \nAAVxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3QADkFSUk9XX0lORklOSVRFdAAMQVJST1dfREFN\r\
  \nQUdFcQB+AB91cQB+AAYAAAADcQB+ADhxAH4AIXEAfgAicQB+ADhzcQB+AA4AAAB2cHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnRxAH4AP3NxAH4ADgAAACpwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgEEc3EAfgAD\r\
  \ndXEAfgAGAAAABHQADURFUFRIX1NUUklERVJxAH4AM3EAfgEHcQB+AB91cQB+AAYAAAAEcQB+ACJx\r\
  \nAH4AOHEAfgCTcQB+ACJzcQB+AA4AAAAPc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3Nx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEA\r\
  \nfgEEc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+AQdxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgCTcQB+\r\
  \nACJxAH4BCXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAZFTFlUUkFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgAWcQB+AC11cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAJxAH4AM3EAfgAf\r\
  \ndXEAfgAGAAAAAnEAfgA4cQB+ACJxAH4AInNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+\r\
  \nAQRzcQB+AAN1cQB+AAYAAAADcQB+ADNxAH4BB3EAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AJNxAH4A\r\
  \nInEAfgEJcA==\r\n"
xp: 1595.0
health: 24.957202911376953
hunger: 17
saturation: 0.0
location:
  world: world
  x: 13152.2
  y: 67.0
  z: 104.6
logType: QUIT
version: v1_20_R3
