inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtDT09L\r\
  \nRURfQkVFRnNxAH4ADgAAABVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADxxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRzcQB+AA4A\r\
  \nAAAmc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4A\r\
  \nGXQACEZJUkVXT1JLcQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAa\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAdcQB+ADN0AApTSUxLX1RPVUNIcQB+AB91cQB+AAYAAAAEcQB+\r\
  \nACFxAH4AOHEAfgA4cQB+ACJxAH4AInNxAH4ADgAAASBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALQ09DT0FfQkVBTlNx\r\
  \nAH4AInNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1z\r\
  \ncQB+AA4AAA50dAALTUlMS19CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAAqc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnRx\r\
  \nAH4AaHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AARESVJUcQB+ADdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4A\r\
  \nAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHEAfgBuc3EAfgAOAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtTQ0FGRk9MRElOR3EAfgAi\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAInNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdPQUtfTE9Hc3EAfgAOAAAA\r\
  \nF3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0ABFQUklTTUFSSU5FX0JSSUNLU3NxAH4ADgAAAB9zcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AG5z\r\
  \ncQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQAFE5FVEhFUklURV9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABl0AAVBUk1PUnNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4AM3QAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHEAfgAfdXEAfgAG\r\
  \nAAAAA3EAfgA4c3EAfgAOAAAABHEAfgAic3EAfgAOAAAAB3NxAH4ADgAAACdwc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nCUdVTlBPV0RFUnEAfgCBcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADFJPVFRFTl9GTEVTSHEAfgC4cHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAD\r\
  \nRUdHcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEcQB+ABl0AAVTS1VMTHQA\r\
  \nknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxz\r\
  \nZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNl\r\
  \nLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EA\r\
  \nfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRl\r\
  \nZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlz\r\
  \ndHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1h\r\
  \ncDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMA\r\
  \nAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0\r\
  \nZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1o\r\
  \nMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelps\r\
  \nWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNN\r\
  \nekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4cHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50cQB+AGhzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAD0ZMSU5UX0FO\r\
  \nRF9TVEVFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4AU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+\r\
  \nABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAABHEAfgAdcQB+AB5xAH4A\r\
  \nM3EAfgAfdXEAfgAGAAAABHEAfgAhcQB+ACJxAH4AOHEAfgAic3EAfgAOAAAAzHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAANCT1dzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4A\r\
  \nBgAAAAVxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3QADkFSUk9XX0lORklOSVRFdAAMQVJST1df\r\
  \nREFNQUdFcQB+AB91cQB+AAYAAAADcQB+ADhxAH4AIXEAfgAicQB+ADhzcQB+AA4AAAB2cHBwc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAV\r\
  \ncQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ALNzcQB+AAN1cQB+AAYAAAAEdAANREVQ\r\
  \nVEhfU1RSSURFUnEAfgAzcQB+ALZxAH4AH3VxAH4ABgAAAARxAH4AInEAfgA4cQB+ALhxAH4AInNx\r\
  \nAH4ADgAAAA9xAH4AOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABJORVRIRVJJVEVfTEVHR0lOR1NzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgCzc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAzcQB+ALZxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgC4cQB+ACJxAH4A\r\
  \nuXEAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAV\r\
  \ncQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAACcQB+ADNx\r\
  \nAH4AH3VxAH4ABgAAAAJxAH4AOHEAfgAicQB+ACJzcQB+AA4AAAATc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEE5FVEhF\r\
  \nUklURV9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4A\r\
  \nF3VxAH4ABgAAAAVxAH4AGXEAfgCzc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+ALZxAH4AH3VxAH4A\r\
  \nBgAAAANxAH4AOHEAfgC4cQB+ACJxAH4AuXEAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABd0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEA\r\
  \nfgAZdAALVElMRV9FTlRJVFlzcQB+AA4AAABbcQB+AVA=\r\n"
xp: 1472.0
health: 26.0
hunger: 20
saturation: 1.8000002
location:
  world: world
  x: 12304.1
  y: 112.0
  z: -154.4
logType: QUIT
version: v1_20_R3
