enderchest: "rO0ABXcEAAAAG3NyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAAWTElHSFRfQkxVRV9TSFVMS0VSX0JPWHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGludGVybmFsdAANYmxvY2tN\r\
  \nYXRlcmlhbHVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAC1RJTEVfRU5USVRZdAGkSDRzSUFBQUFBQUFB\r\
  \nLzVYVXowNkVNQkFHOElHRmRjRjExWU12NGI5NDlxang0Tm05a3k1MFliS2xKV1hRNWUwbHFkMGxh\r\
  \nVXphQjVoZnZtK21rQVBrc0hrVHFqeDhTRUlhdDZ4ZVFZd1YzTFVvZWFuWm5sNzdaaEFIcm91ZE9t\r\
  \nYVFmaEp2K3h3QWJpTkl2b1FpTUFNUDU0RnFrTHhndWxXNklJMXQwYmRJRGNxNm1FWTd3WWhIa0w2\r\
  \nclFWSUNmMFpralB1endVYy9ZbUdKMkJDUHM5eFNEZVNGWkJaWk9GMSttSzY4ak53YWlUR2VaMEZR\r\
  \nY0ZuNjlZa3NrN3BSVVBoRldWcGo2YXoxbXgvRFlsd1k0bW5XaGt2U1k5aDlWODV4U3NWNnYrT2My\r\
  \nbVRPUmdpcndLM214bmlaSDNqY282eW05eDBFWGJwN2FWam5xYVJXV1R1Vkd1VzVscE54NVNUUkRQ\r\
  \ndlFKQnYzOCtsUSsyMDN0c2kxODk0MDdzS0lHNmVONU5Sd2pjU0xvYXMxbXk3K3I3S2Vma3UvQ2xm\r\
  \nOVNOTUVBQUE9cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPUkVEX1NIVUxLRVJfQk9Yc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0BHRINHNJQUFB\r\
  \nQUFBQUEvKzJZMzAvYk1CREgzVitqN1RaZzVmZlFYdks0VmZDeXZmUVJ4Z1BTTmswQzdXVmlscHM0\r\
  \nalJYWERyYlRnbEQvOTExbzF3UVNwWU41VkpyMlJFbDYvdHlkdjNkbnQ0MVFHNjBlY2VtR0o4SXdj\r\
  \nMzFPQmsxVVpSN2FHakpCWFVWODA5TkJ6RU9xY0Y5ZXRWRGoxTkNoYmlPRTlpdW9mc2FsUVZPRDNk\r\
  \nU0FDamNnd2xBUFRHVFlSalZEQm0zVStScjNPWE9QNGpCazVodmhNZFUxdERzaWd2YmNXQnM1eEF5\r\
  \nV3hpT3FOSk1DQUpVbTJzKzlaaDRGUjMxR0ZYcWZ2TVF6MkJBZTZ3eVpDSmZCSXd5R0ZFc2ZtNERp\r\
  \nZ2ZRMHhMdmlNUjF4Y3QxRTlTOWtTTkhGamNNTUFkZWNuays0cGwzSEtDSTBKNFk2UFNjSE9iajFZ\r\
  \nekhwUU1EaXpxU0Y2cCtrb3Mwa29NcnhqV1BvbFlGbG5hNERIeFJ4ZXQvbnovS296RDg0Rm4xRlNV\r\
  \najZuRTZYN2pxeTc4ZmFCVCs5dWVzdXhCR2VqTURBNmQwNHhEV1FTMWhhUmxUZ1dIRXdHaVdwaDBl\r\
  \nQk1WSHY4UENCMEVuM2ZySmk0VkhGWWZOVEo3UlJMS1FtVURJZUJLbHJra3NGNElIa0h2alJULzVN\r\
  \nMzAyNjJiemNXLytPMmVSaWdtcG83ZmhXRVorbFIvbEhZZ2dhbzBZTGRjNE1KTm83eWNUU25zb28w\r\
  \nZWVidkZveXdWVlJqWTg0cXNEWFVlTll4c0pVMEV6ZmxkL1M5eUw4V3FhZWhxQ2dHYkJSQUt4YUFh\r\
  \nNm41aWFRU3VnWnNWWkFyRmtoYnFmbXZwTGE0REZKK3NhTVd5M2cxbTF6TDJOUVA0WnZxUUV0aWJk\r\
  \naGhidVoyVklaYzZ3alNyMFM2ak1yMUd4akhqUGZZQzFBd3lYWUZTdllUbW9lUWZOMW1Sak1tUFVD\r\
  \nWm5OcXRKb2EvZFZKOERaZjJ3L28vMmVQNmY4THVuNXhrNnJuTTlXeUxrWEdRL0FxZG9PU250WmUx\r\
  \nc3orOEpDWkhRbzU1dFFiME9KczF2SmIrY1B1S0o4N1VEVExULzlnbGdlVWM5eUhUMDgzeWU4aExj\r\
  \neHhqNmdRazh1WVBHS1lwN2JKUkY4azcvMjhhdWJobEtqOHVlM0o3WE5JWFFud3hmK3krbDlXLzN4\r\
  \nWnZiUlNWbnVac3FJRXhxZkNFQXd2UDFlc0x1Y0l0V1lGdTVHYVF3VzRZWis0WWNuaGVOMEtkQ2Mx\r\
  \nVDNTQmllOHpBUmY5a3YxOTliU0h0M2VMRDI5cHg4cjNwbk1icDdmN0hhbTRNMWJudWFyL3lsWEh0\r\
  \nakkwM0YwaVFiVXV1U0J1Mks0Q1JYWEVGRWxhWVVrVmJOcStTTEJoUkRJRlh4VHExbklLZnZ2SnIr\r\
  \nQTd5d2wwMS9xZWlvWDlaVzhKek5lMnIxbXozNDVTOWQ3SkxrSS9BVFhKT0xOYUZRQUFxAH4AIXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVdAAI\r\
  \nZW5jaGFudHN0AAtyZXBhaXItY29zdHVxAH4ABgAAAARxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AAN1\r\
  \ncQB+AAYAAAAEdAAETFVDS3QABExVUkV0AAdNRU5ESU5HdAAKRFVSQUJJTElUWXVxAH4ABgAAAARz\r\
  \ncQB+AA4AAAADcQB+ADtzcQB+AA4AAAABcQB+ADtxAH4APHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBORVRIRVJJVEVf\r\
  \nSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AMHEAfgAxdXEAfgAGAAAA\r\
  \nBHEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAGdAAMV0FURVJfV09SS0VScQB+ADh0ABhQUk9U\r\
  \nRUNUSU9OX0VOVklST05NRU5UQUx0AAZPWFlHRU50AAZUSE9STlNxAH4AOXVxAH4ABgAAAAZxAH4A\r\
  \nPHEAfgA8c3EAfgAOAAAABHEAfgA7cQB+ADtxAH4AO3NxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVU\r\
  \nSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAwcQB+\r\
  \nADF1cQB+AAYAAAAEcQB+ABlxAH4AR3NxAH4AA3VxAH4ABgAAAARxAH4AOHEAfgBLcQB+AE1xAH4A\r\
  \nOXVxAH4ABgAAAARxAH4APHEAfgBPcQB+ADtxAH4AO3EAfgA7c3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5FVEhFUklU\r\
  \nRV9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4A\r\
  \nBgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAABXEAfgA4cQB+AEt0AAtTV0lGVF9TTkVBS3EA\r\
  \nfgBNcQB+ADl1cQB+AAYAAAAFcQB+ADxxAH4AT3EAfgA7cQB+ADtxAH4AO3EAfgA7c3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBx\r\
  \nAH4AMXVxAH4ABgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAAB3QADURFUFRIX1NUUklERVJ0\r\
  \nAA9QUk9URUNUSU9OX0ZBTExxAH4AOHEAfgBLdAAKU09VTF9TUEVFRHEAfgBNcQB+ADl1cQB+AAYA\r\
  \nAAAHcQB+ADtxAH4AT3EAfgA8cQB+AE9xAH4AO3EAfgA7cQB+ADtzcQB+AA4AAAA/c3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQAB1RSSURFTlRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAwcQB+ADF1cQB+\r\
  \nAAYAAAAEcQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAAV0AApDSEFOTkVMSU5HdAAISU1QQUxJTkd0\r\
  \nAAdMT1lBTFRZcQB+ADhxAH4AOXVxAH4ABgAAAAVxAH4APHNxAH4ADgAAAAVxAH4AO3EAfgA8cQB+\r\
  \nADtxAH4AUHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4AgnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+\r\
  \nADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgAzc3EAfgADdXEAfgAGAAAABHEAfgCKcQB+ADh0AAdS\r\
  \nSVBUSURFcQB+ADl1cQB+AAYAAAAEcQB+AI1xAH4APHEAfgA7cQB+ADtxAH4AO3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAWRU5DSEFOVEVEX0dPTERFTl9BUFBMRXNxAH4ADgAAABhzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANTkVUSEVS\r\
  \nSVRFX0hPRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ADB1cQB+AAYAAAADcQB+\r\
  \nABlxAH4AM3NxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3EA\r\
  \nfgA4cQB+ADl1cQB+AAYAAAAEcQB+AI1xAH4AO3EAfgA8cQB+ADtzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRElBTU9O\r\
  \nRF9IT0VzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAwcQB+ADF1cQB+AAYAAAAE\r\
  \ncQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAARxAH4Ar3EAfgA4dAAKU0lMS19UT1VDSHEAfgA5dXEA\r\
  \nfgAGAAAABHEAfgCNcQB+ADxxAH4APHEAfgA7cQB+ADxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJ\r\
  \nQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAwcQB+ADF1cQB+AAYAAAAE\r\
  \ncQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAARxAH4Ar3EAfgCwcQB+ADhxAH4AOXVxAH4ABgAAAARx\r\
  \nAH4AjXEAfgA7cQB+ADxxAH4AO3EAfgA7c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgDFc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AMHEAfgAxdXEAfgAGAAAABHEAfgAZcQB+ADNzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AK9xAH4AOHEAfgC+cQB+ADl1cQB+AAYAAAAEcQB+AI1xAH4APHEAfgA8cQB+ADtxAH4A\r\
  \nUHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AnnVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAlIQVlfQkxPQ0tzcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgCedXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgDec3EAfgAOAAAA\r\
  \nInNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AnnVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AA1TSFVMS0VSX1NIRUxMc3EAfgAOAAAACXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAQVE9URU1fT0ZfVU5E\r\
  \nWUlOR3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AnnVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAlHVU5QT1dERVJxAH4A33NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AnnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4A+HEAfgDfc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgCedXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHEAfgD4cQB+AN9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AJ51\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+APhxAH4A33NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AnnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4A+HEAfgDfc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgCedXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQAD05FVEhFUklURV9TQ1JBUHNxAH4ADgAAAAJzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AJ51cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRF\r\
  \nX0lOR09UcQB+AI1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA\r\
  \nA3EAfgANc3EAfgAOAAAOdHEAfgDyc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnRxAH4A8g==\r\n"
xp: 1144.0
health: 0.0
hunger: 16
saturation: 0.0
location:
  world: world
  x: 11528.5
  y: 66.0
  z: 259.7
logType: DEATH
version: v1_20_R3
deathReason: PROJECTILE (Arrow, Skeleton)
