enderchest: "rO0ABXcEAAAAG3NyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAAWTElHSFRfQkxVRV9TSFVMS0VSX0JPWHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGludGVybmFsdAANYmxvY2tN\r\
  \nYXRlcmlhbHVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAC1RJTEVfRU5USVRZdAGkSDRzSUFBQUFBQUFB\r\
  \nLzVYVXowNkVNQkFHOElHRmRjRjExWU12NGI5NDlxang0Tm05a3k1MFliS2xKV1hRNWUwbHFkMGxh\r\
  \nVXphQjVoZnZtK21rQVBrc0hrVHFqeDhTRUlhdDZ4ZVFZd1YzTFVvZWFuWm5sNzdaaEFIcm91ZE9t\r\
  \nYVFmaEp2K3h3QWJpTkl2b1FpTUFNUDU0RnFrTHhndWxXNklJMXQwYmRJRGNxNm1FWTd3WWhIa0w2\r\
  \nclFWSUNmMFpralB1endVYy9ZbUdKMkJDUHM5eFNEZVNGWkJaWk9GMSttSzY4ak53YWlUR2VaMEZR\r\
  \nY0ZuNjlZa3NrN3BSVVBoRldWcGo2YXoxbXgvRFlsd1k0bW5XaGt2U1k5aDlWODV4U3NWNnYrT2My\r\
  \nbVRPUmdpcndLM214bmlaSDNqY282eW05eDBFWGJwN2FWam5xYVJXV1R1Vkd1VzVscE54NVNUUkRQ\r\
  \ndlFKQnYzOCtsUSsyMDN0c2kxODk0MDdzS0lHNmVONU5Sd2pjU0xvYXMxbXk3K3I3S2Vma3UvQ2xm\r\
  \nOVNOTUVBQUE9cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPUkVEX1NIVUxLRVJfQk9Yc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0A9hINHNJQUFB\r\
  \nQUFBQUEvKzJYeTAvYlFCQ0hKNitTdUE4UWxFS0ZldkU1Z2t0N3lSSEtBYW10S2xIMVV0SFYybDdi\r\
  \nSzI5Mnd6NFNFTXIvM2pHSllwZWtwclJXSTFXYzR1ejZOOS9zN016TzJnUHc0TVd4VUdGMktpMjMx\r\
  \nMTlvMG9VbWoyQjN5Q1VMTlkzdHdLUk9aRXlUUUYzMW9ITm0yZEI0QUxEVGdQYTVVQlptZ3YxQ3dH\r\
  \nU1lVbWxaaEJLVmVkQ3lOUEZnKzdNTEJBK1BYWlp4KzVVS3gwd0w5c2RVc2tIb2pGVkR3dEUwR1RO\r\
  \ndHVKSUlhSFRoWUdtYVJ3d2RqVG5UOERhZkpIUFlFSWROaVV4bHlIR0lvSkFSRlJPYk1wS295RUFM\r\
  \nTms5dTdYMVVFUlB2cWFVd2dZNEhHeEUzSTBHdnU5RCtSSWNNTG01OGJpazY3QTlpS2d6cisxWlRh\r\
  \nUVMxekIvNFMrakRXKy91NXg5S05PNVBlOUQrb0RUcjVzdHNuTno0bGwxWk5PdjNmWHpRMUI5OFc0\r\
  \nd3RvMHAvaUpPQlpqU2pnV0F6MDMxZkJiRXpJZm9aTFZ3UGNSM1o2UmdGL3VER3A2SEZDS05wTldL\r\
  \nU09DMVFOTTQzQklkU2EwZURvNk1IUXFmOXU4RnlNbUphWUVvVVRoaXJlY1pzcXBWTDBzSTFKWlJH\r\
  \nY0tKRWhINEUrYzlzYnRvdngrV08vWjlrMDRzcDlHRDczR0pJbzlPUzE5NHNqZkw4ZkxPY0xhVmxO\r\
  \nS0VseGdJYStEcDBUcFNUdGdIei9HNzhWbjdmaDk4czFkTVFjMlVPN0t3QU5tc0JiaFZ5bXlvdHpa\r\
  \nellXa0ZzMVVKOFZjaGpyWXdsRTVxZkczTnVjd1czWFRmMzBtR2VFM3hMSjZ4aXZaMWF1QzlMVzZx\r\
  \nY0lHYkVXRlJCZlZJTHRYd3dUM2hzaVpHWXd4WFlqVnF3MjRWOGhJZHZ5R1V5WjdaWE1IdTFCNWlM\r\
  \nRE05U0Y2WVZsZXF0cXhPOWUwZ255cVNhQ0JZbERKYWJ6dmQ2bTg0Q3RhcnJuUDFGMTBtWkVDVEFw\r\
  \nMy9YYys0Z2ErZzRFZFVab1plTy9rSGJLYlI1NzFsNXAyamRsOTRIeTFteldHUkZsait0dXgvRkFn\r\
  \nTmFBWHoyV0ZhUFpmWGZsOVh6V3NycWRhbXNHTVZMdnlhNFJGSGRMVitzNTJLd1dRdDJwNUJqWFlS\r\
  \nWlFNT3M0c3EzVlF0MHI1RG4yVUpvSEhPSm42OFYrN3U3bmlEdnJRZTdYL2Vsajh0ZlJ4amdCM0Vq\r\
  \nYitsSUVBQUFxAH4AIXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAVdAAIZW5jaGFudHN0AAtyZXBhaXItY29zdHVxAH4ABgAAAARxAH4AGXQAClVO\r\
  \nU1BFQ0lGSUNzcQB+AAN1cQB+AAYAAAAEdAAETFVDS3QABExVUkV0AAdNRU5ESU5HdAAKRFVSQUJJ\r\
  \nTElUWXVxAH4ABgAAAARzcQB+AA4AAAADcQB+ADtzcQB+AA4AAAABcQB+ADtxAH4APHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4A\r\
  \nMHEAfgAxdXEAfgAGAAAABHEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAGdAAMV0FURVJfV09S\r\
  \nS0VScQB+ADh0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUx0AAZPWFlHRU50AAZUSE9STlNxAH4A\r\
  \nOXVxAH4ABgAAAAZxAH4APHEAfgA8c3EAfgAOAAAABHEAfgA7cQB+ADtxAH4AO3NxAH4ADgAAAAdz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4AFXEAfgAwcQB+ADF1cQB+AAYAAAAEcQB+ABlxAH4AR3NxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nOHEAfgBLcQB+AE1xAH4AOXVxAH4ABgAAAARxAH4APHEAfgBPcQB+ADtxAH4AO3EAfgA7c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAABXEAfgA4cQB+AEt0\r\
  \nAAtTV0lGVF9TTkVBS3EAfgBNcQB+ADl1cQB+AAYAAAAFcQB+ADxxAH4AT3EAfgA7cQB+ADtxAH4A\r\
  \nO3EAfgA7c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAAB3QA\r\
  \nDURFUFRIX1NUUklERVJ0AA9QUk9URUNUSU9OX0ZBTExxAH4AOHEAfgBLdAAKU09VTF9TUEVFRHEA\r\
  \nfgBNcQB+ADl1cQB+AAYAAAAHcQB+ADtxAH4AT3EAfgA8cQB+AE9xAH4AO3EAfgA7cQB+ADtzcQB+\r\
  \nAA4AAAA/c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAB1RSSURFTlRzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4A\r\
  \nFXEAfgAwcQB+ADF0AAZEYW1hZ2V1cQB+AAYAAAAFcQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAAR0\r\
  \nAApDSEFOTkVMSU5HdAAISU1QQUxJTkd0AAdMT1lBTFRZcQB+ADl1cQB+AAYAAAAEcQB+ADxzcQB+\r\
  \nAA4AAAAFcQB+ADtxAH4AO3EAfgA7c3EAfgAOAAAAfXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AgnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADBxAH4AMXEAfgCGdXEAfgAGAAAABXEAfgAZcQB+ADNz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AIt0AAdSSVBUSURFcQB+ADl1cQB+AAYAAAADcQB+AI5xAH4AO3EA\r\
  \nfgA7cQB+ADxzcQB+AA4AAACLc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnQA\r\
  \nBmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABZFTkNIQU5URURfR09MREVOX0FQUExF\r\
  \nc3EAfgAOAAAAE3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AA1ORVRIRVJJVEVfSE9Fc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ABVxAH4AMHEAfgCGdXEAfgAGAAAABHEAfgAZcQB+ADNzcQB+AAN1cQB+AAYAAAAE\r\
  \ndAAJRElHX1NQRUVEdAARTE9PVF9CT05VU19CTE9DS1NxAH4AOHEAfgA5dXEAfgAGAAAABHEAfgCO\r\
  \ncQB+ADtxAH4APHEAfgA7c3EAfgAOAAABC3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0hPRXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgAzc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgCycQB+ADh0AApTSUxLX1RPVUNIcQB+ADl1cQB+AAYAAAAEcQB+AI5x\r\
  \nAH4APHEAfgA8cQB+ADtxAH4APHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFORVRIRVJJVEVfUElDS0FYRXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgAzc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgCycQB+ALNxAH4AOHEAfgA5dXEAfgAGAAAABHEAfgCOcQB+ADtxAH4A\r\
  \nPHEAfgA7cQB+ADtzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AMlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgAwcQB+ADF1cQB+AAYAAAAEcQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAARxAH4AsnEAfgA4\r\
  \ncQB+AMJxAH4AOXVxAH4ABgAAAARxAH4AjnEAfgA8cQB+ADxxAH4AO3EAfgBQc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nCUhBWV9CTE9DS3EAfgB8c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
  \nBgAAAANxAH4ADXNxAH4ADgAADnR0ABNESUFNT05EX0hPUlNFX0FSTU9Sc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADVNI\r\
  \nVUxLRVJfU0hFTExzcQB+AA4AAAAJc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0ABBUT1RFTV9PRl9VTkRZSU5Hc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nCUdVTlBPV0RFUnNxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AKF1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+APtxAH4A/HNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AoXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4A+3EA\r\
  \nfgD8c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHEAfgD7cQB+APxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AKF1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+APtxAH4A/HNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AoXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9O\r\
  \nRVRIRVJJVEVfU0NSQVBzcQB+AA4AAAACc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9JTkdPVHEAfgCO\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4A\r\
  \nDgAADnRxAH4A9XNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAAD\r\
  \ncQB+AA1zcQB+AA4AAA50cQB+APU=\r\n"
xp: 1960.0
health: 0.0
hunger: 15
saturation: 0.0
location:
  world: world
  x: 8023.3
  y: 10.0
  z: 161.3
logType: DEATH
version: v1_20_R3
deathReason: FALL
