chestData:
- ==: ChestData
  playerUUID: a9e84f2a-b34b-400f-b455-155f6a0231bf
  holographicTimer: world;8280.5;-49.200000047683716;149.5
  worldName: world
  as_timer_id: c3d3cd42-f488-4771-a076-89130bb98ba0
  playerName: lishuoning
  isRemovedBlock: false
  isInfinity: true
  as_owner_id: 64f55033-720f-4cf3-ae9e-665d58ed355a
  chestDate: 2023-12-24T14:36:33.829Z
  xpStored: 1113
  inventory:
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: PLAYER_HEAD
    meta:
      ==: ItemMeta
      meta-type: SKULL
      display-name: '{"text":"","extra":[{"text":"Backpack","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"yellow","bold":false}]}'
      skull-owner:
        ==: PlayerProfile
        uniqueId: ed57ebc5-704e-3ba1-8e1a-1e774d884533
        properties:
        - name: textures
          value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGRjYzZlYjQwZjNiYWRhNDFlNDMzOTg4OGQ2ZDIwNzQzNzU5OGJkYmQxNzVjMmU3MzExOTFkNWE5YTQyZDNjOCJ9fX0=
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: DIAMOND_HOE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        DIG_SPEED: 4
        LOOT_BONUS_BLOCKS: 3
        MENDING: 1
      Damage: 159
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  chestLocation: world;8280.0;-50.0;149.0
- ==: ChestData
  playerUUID: c744de25-a482-3eca-b3e4-d44a92b9f3d5
  holographicTimer: world;4381.5;144.79999995231628;706.5
  worldName: world
  as_timer_id: 858bb32e-8911-4c9e-bc2c-b095efc07c90
  playerName: DSLZL
  isRemovedBlock: false
  isInfinity: true
  as_owner_id: 912af82c-f936-4dcf-b372-206e79089a8e
  chestDate: 2023-12-27T07:50:44.410Z
  xpStored: 30
  inventory:
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: PLAYER_HEAD
    meta:
      ==: ItemMeta
      meta-type: SKULL
      display-name: '{"text":"","extra":[{"text":"Backpack","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"yellow","bold":false}]}'
      skull-owner:
        ==: PlayerProfile
        uniqueId: ed57ebc5-704e-3ba1-8e1a-1e774d884533
        properties:
        - name: textures
          value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGRjYzZlYjQwZjNiYWRhNDFlNDMzOTg4OGQ2ZDIwNzQzNzU5OGJkYmQxNzVjMmU3MzExOTFkNWE5YTQyZDNjOCJ9fX0=
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: IRON_PICKAXE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      Damage: 28
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: IRON_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      Damage: 1
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: IRON_SHOVEL
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: IRON_AXE
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: BREAD
    amount: 52
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: COBBLESTONE
    amount: 27
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: WHEAT_SEEDS
    amount: 11
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: COCOA_BEANS
    amount: 6
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: JUNGLE_LOG
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: MELON_SLICE
    amount: 3
  - ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: DIRT
    amount: 10
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  chestLocation: world;4381.0;144.0;706.0
