inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EA\r\
  \nfgAOAAAOdHQACE9BS19ET09Sc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVx\r\
  \nAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxHT0xERU5fQVBQTEVzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPRElBTU9O\r\
  \nRF9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAhlbmNoYW50c3VxAH4A\r\
  \nBgAAAANxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AAN1cQB+AAYAAAAEdAAJRElHX1NQRUVEdAARTE9P\r\
  \nVF9CT05VU19CTE9DS1N0AAdNRU5ESU5HdAAKRFVSQUJJTElUWXVxAH4ABgAAAARzcQB+AA4AAAAF\r\
  \nc3EAfgAOAAAAA3NxAH4ADgAAAAFxAH4ATXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0FYRXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AEJ1cQB+AAYAAAADcQB+ABlxAH4ARHNxAH4AA3Vx\r\
  \nAH4ABgAAAAJxAH4AR3EAfgBIdXEAfgAGAAAAAnNxAH4ADgAAAARxAH4ATXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAMR0xPV19CRVJSSUVTc3EAfgAOAAAABnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ORVRIRVJJVEVfU1dPUkRzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgBCdAALcmVwYWlyLWNvc3R1cQB+AAYAAAAE\r\
  \ncQB+ABlxAH4ARHNxAH4AA3VxAH4ABgAAAAd0AAtGSVJFX0FTUEVDVHQACUtOT0NLQkFDS3QAD0xP\r\
  \nT1RfQk9OVVNfTU9CU3EAfgBJdAAKREFNQUdFX0FMTHQADVNXRUVQSU5HX0VER0VxAH4ASnVxAH4A\r\
  \nBgAAAAdzcQB+AA4AAAACcQB+AHhxAH4ATXEAfgBOcQB+AExxAH4ATXEAfgBNc3EAfgAOAAAAD3Nx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AYHVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AAdESUFNT05Ec3EAfgAOAAAAGHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBgdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQABUFSUk9Xc3EAfgAOAAAAC3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA5FTkNIQU5URURfQk9PS3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAPc3RvcmVkLWVuY2hhbnRzdXEAfgAGAAAAA3EAfgAZdAAJ\r\
  \nRU5DSEFOVEVEc3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2Vy\r\
  \naWFsaXplZEZvcm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAF0AAxRVUlDS19DSEFSR0V1cQB+\r\
  \nAAYAAAABcQB+AE1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AD5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgBCdAAGRGFtYWdldXEAfgAGAAAABHEAfgAZcQB+AERzcQB+AJp1cQB+AAYAAAABdAAKU0lM\r\
  \nS19UT1VDSHVxAH4ABgAAAAFxAH4ATnNxAH4ADgAAAQxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4Ap3QADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAE\r\
  \ncQB+ABl0AAtUSUxFX0VOVElUWXNxAH4ADgAAAFZxAH4As3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AYHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdFTUVSQUxEc3EA\r\
  \nfgAOAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4APnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+\r\
  \nAEJ1cQB+AAYAAAADcQB+ABlxAH4ARHNxAH4AA3VxAH4ABgAAAARxAH4AR3EAfgBIcQB+AElxAH4A\r\
  \nSnVxAH4ABgAAAARxAH4AXHEAfgB4cQB+AE5xAH4ATXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AYHEAfgALdXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHQAD0ZJUkVXT1JL\r\
  \nX1JPQ0tFVHNxAH4ADgAAABpzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQABXBvd2Vy\r\
  \ndXEAfgAGAAAAA3EAfgAZdAAIRklSRVdPUktxAH4ATnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AYHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4Af3EAfgDBc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+AAlxAH4ACnEAfgBgcQB+AAt1cQB+AAYAAAAFcQB+AA1z\r\
  \ncQB+AA4AAA50dAAMV0hJVEVfQkFOTkVScQB+AFxzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhx\r\
  \nAH4AFXEAfgAWdAAJSXRlbUZsYWdzdAAIcGF0dGVybnN1cQB+AAYAAAAFcQB+ABl0AAZCQU5ORVJ0\r\
  \nAD17InRyYW5zbGF0ZSI6ImJsb2NrLm1pbmVjcmFmdC5vbWlub3VzX2Jhbm5lciIsImNvbG9yIjoi\r\
  \nZ29sZCJ9c3EAfgAkAAAAAXcEAAAAAXQAE0hJREVfUE9USU9OX0VGRkVDVFN4c3IANmNvbS5nb29n\r\
  \nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlTGlzdCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAB\r\
  \nWwAIZWxlbWVudHN0ABNbTGphdmEvbGFuZy9PYmplY3Q7eHB1cQB+AAYAAAAIc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIdAAFY29sb3J0AAdwYXR0ZXJudXEAfgAGAAAAA3QAB1BhdHRlcm50AARD\r\
  \nWUFOdAACbXJzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A93EAfgD4dXEAfgAGAAAAA3EA\r\
  \nfgD6dAAKTElHSFRfR1JBWXQAAmJzc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+APdxAH4A\r\
  \n+HVxAH4ABgAAAANxAH4A+nQABEdSQVl0AAJjc3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgD3cQB+APh1cQB+AAYAAAADcQB+APpxAH4BAXQAAmJvc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EA\r\
  \nfgAIcQB+APdxAH4A+HVxAH4ABgAAAANxAH4A+nQABUJMQUNLdAACbXNzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4A93EAfgD4dXEAfgAGAAAAA3EAfgD6cQB+AQF0AAJoaHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgD3cQB+APh1cQB+AAYAAAADcQB+APpxAH4BAXQAAm1jc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+APdxAH4A+HVxAH4ABgAAAANxAH4A+nEAfgEScQB+AQ1z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AGB1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAKSVJPTl9JTkdPVHNxAH4ADgAAAB9zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nAAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAEFRPVEVNX09GX1VORFlJTkdz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAO\r\
  \nAAAOdHEAfgEuc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANx\r\
  \nAH4ADXNxAH4ADgAADnRxAH4BLnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1\r\
  \ncQB+AAYAAAADcQB+AA1zcQB+AA4AAA50cQB+AS5zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHEAfgEuc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnRxAH4BLnNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50cQB+\r\
  \nAS5zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EA\r\
  \nfgAOAAAOdHEAfgEuc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBgdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgDAc3EAfgAOAAAAHHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AYHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAlHVU5QT1dE\r\
  \nRVJzcQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBgdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgB/cQB+AMFzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AGBxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AARCT09LcQB+\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWdAARY3VzdG9tLW1vZGVsLWRh\r\
  \ndGF0ABJQdWJsaWNCdWtraXRWYWx1ZXN1cQB+AAYAAAAFcQB+ABlxAH4ARHQAR3siaXRhbGljIjpm\r\
  \nYWxzZSwidHJhbnNsYXRlIjoidmFuZV9lbmNoYW50bWVudHMuaXRlbV9hbmNpZW50X3RvbWUubmFt\r\
  \nZSJ9c3EAfgAOAHcAAHQAansKICAgICJ2YW5lOmN1c3RvbV9pdGVtX2lkZW50aWZpZXIiOiAidmFu\r\
  \nZV9lbmNoYW50bWVudHM6YW5jaWVudF90b21lIiwKICAgICJ2YW5lOmN1c3RvbV9pdGVtX3ZlcnNp\r\
  \nb24iOiAxCn1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AGB1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50cQB+AH9xAH4AwXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZQT1RJT05zcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAADcQB+AAhxAH4AFXQAC3BvdGlvbi10eXBldXEAfgAGAAAAA3EAfgAZcQB+AX10\r\
  \nABltaW5lY3JhZnQ6d2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgF9c3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+ABVxAH4BgXVxAH4ABgAAAANxAH4AGXEAfgF9dAAZbWluZWNyYWZ0Ondh\r\
  \ndGVyX2JyZWF0aGluZ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABJESUFNT05EX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4AFXEAfgBCcQB+AKd1cQB+AAYAAAAEcQB+ABl0AAVBUk1PUnNxAH4A\r\
  \nA3VxAH4ABgAAAAJ0AA9QUk9URUNUSU9OX0ZJUkVxAH4ASXVxAH4ABgAAAAJxAH4ATXEAfgBOc3EA\r\
  \nfgAOAAAAFHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AYHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4Af3EAfgDBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADURJQU1PTkRfQk9PVFNzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgBCcQB+AG51cQB+AAYAAAAEcQB+ABlxAH4B\r\
  \nmHNxAH4AA3VxAH4ABgAAAAJxAH4ASXQAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHVxAH4ABgAA\r\
  \nAAJxAH4ATnEAfgBccQB+AE5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQRElBTU9ORF9MRUdHSU5HU3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AEJ1cQB+AAYAAAADcQB+ABlxAH4BmHNxAH4AA3VxAH4A\r\
  \nBgAAAAJxAH4ASXEAfgGvdXEAfgAGAAAAAnEAfgBOcQB+AFxzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGRUxZVFJBc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AQnEAfgBudXEAfgAGAAAABHEAfgAZcQB+\r\
  \nAERzcQB+AAN1cQB+AAYAAAACcQB+AElxAH4ASnVxAH4ABgAAAAJxAH4ATnEAfgBNcQB+AE1zcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAAORElBTU9ORF9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEA\r\
  \nfgBCdXEAfgAGAAAAA3EAfgAZcQB+AZhzcQB+AAN1cQB+AAYAAAACcQB+AElxAH4Br3VxAH4ABgAA\r\
  \nAAJxAH4ATnEAfgBcc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEA\r\
  \nfgAVcQB+AEJxAH4AbnEAfgCndXEAfgAGAAAABXEAfgAZcQB+AERzcQB+AAN1cQB+AAYAAAAFdAAK\r\
  \nQVJST1dfRklSRXQADkFSUk9XX0lORklOSVRFdAAMQVJST1dfREFNQUdFdAAPQVJST1dfS05PQ0tC\r\
  \nQUNLcQB+AEp1cQB+AAYAAAAFcQB+AE5xAH4ATnEAfgBMcQB+AHhxAH4ATXEAfgBNc3EAfgAOAAAA\r\
  \nTA==\r\n"
enderchest: "rO0ABXcEAAAAG3NyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAAWTElHSFRfQkxVRV9TSFVMS0VSX0JPWHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGludGVybmFsdAANYmxvY2tN\r\
  \nYXRlcmlhbHVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAC1RJTEVfRU5USVRZdAGkSDRzSUFBQUFBQUFB\r\
  \nLzVYVXowNkVNQkFHOElHRmRjRjExWU12NGI5NDlxang0Tm05a3k1MFliS2xKV1hRNWUwbHFkMGxh\r\
  \nVXphQjVoZnZtK21rQVBrc0hrVHFqeDhTRUlhdDZ4ZVFZd1YzTFVvZWFuWm5sNzdaaEFIcm91ZE9t\r\
  \nYVFmaEp2K3h3QWJpTkl2b1FpTUFNUDU0RnFrTHhndWxXNklJMXQwYmRJRGNxNm1FWTd3WWhIa0w2\r\
  \nclFWSUNmMFpralB1endVYy9ZbUdKMkJDUHM5eFNEZVNGWkJaWk9GMSttSzY4ak53YWlUR2VaMEZR\r\
  \nY0ZuNjlZa3NrN3BSVVBoRldWcGo2YXoxbXgvRFlsd1k0bW5XaGt2U1k5aDlWODV4U3NWNnYrT2My\r\
  \nbVRPUmdpcndLM214bmlaSDNqY282eW05eDBFWGJwN2FWam5xYVJXV1R1Vkd1VzVscE54NVNUUkRQ\r\
  \ndlFKQnYzOCtsUSsyMDN0c2kxODk0MDdzS0lHNmVONU5Sd2pjU0xvYXMxbXk3K3I3S2Vma3UvQ2xm\r\
  \nOVNOTUVBQUE9cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPUkVEX1NIVUxLRVJfQk9Yc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0A9hINHNJQUFB\r\
  \nQUFBQUEvKzJYeTAvYlFCQ0hKNitTdUE4UWxFS0ZldkU1Z2t0N3lSSEtBYW10S2xIMVV0SFYybDdi\r\
  \nSzI5Mnd6NFNFTXIvM2pHSllwZWtwclJXSTFXYzR1ejZOOS9zN016TzJnUHc0TVd4VUdGMktpMjMx\r\
  \nMTlvMG9VbWoyQjN5Q1VMTlkzdHdLUk9aRXlUUUYzMW9ITm0yZEI0QUxEVGdQYTVVQlptZ3YxQ3dH\r\
  \nU1lVbWxaaEJLVmVkQ3lOUEZnKzdNTEJBK1BYWlp4KzVVS3gwd0w5c2RVc2tIb2pGVkR3dEUwR1RO\r\
  \ndHVKSUlhSFRoWUdtYVJ3d2RqVG5UOERhZkpIUFlFSWROaVV4bHlIR0lvSkFSRlJPYk1wS295RUFM\r\
  \nTms5dTdYMVVFUlB2cWFVd2dZNEhHeEUzSTBHdnU5RCtSSWNNTG01OGJpazY3QTlpS2d6cisxWlRh\r\
  \nUVMxekIvNFMrakRXKy91NXg5S05PNVBlOUQrb0RUcjVzdHNuTno0bGwxWk5PdjNmWHpRMUI5OFc0\r\
  \nd3RvMHAvaUpPQlpqU2pnV0F6MDMxZkJiRXpJZm9aTFZ3UGNSM1o2UmdGL3VER3A2SEZDS05wTldL\r\
  \nU09DMVFOTTQzQklkU2EwZURvNk1IUXFmOXU4RnlNbUphWUVvVVRoaXJlY1pzcXBWTDBzSTFKWlJH\r\
  \nY0tKRWhINEUrYzlzYnRvdngrV08vWjlrMDRzcDlHRDczR0pJbzlPUzE5NHNqZkw4ZkxPY0xhVmxO\r\
  \nS0VseGdJYStEcDBUcFNUdGdIei9HNzhWbjdmaDk4czFkTVFjMlVPN0t3QU5tc0JiaFZ5bXlvdHpa\r\
  \nellXa0ZzMVVKOFZjaGpyWXdsRTVxZkczTnVjd1czWFRmMzBtR2VFM3hMSjZ4aXZaMWF1QzlMVzZx\r\
  \nY0lHYkVXRlJCZlZJTHRYd3dUM2hzaVpHWXd4WFlqVnF3MjRWOGhJZHZ5R1V5WjdaWE1IdTFCNWlM\r\
  \nRE05U0Y2WVZsZXF0cXhPOWUwZ255cVNhQ0JZbERKYWJ6dmQ2bTg0Q3RhcnJuUDFGMTBtWkVDVEFw\r\
  \nMy9YYys0Z2ErZzRFZFVab1plTy9rSGJLYlI1NzFsNXAyamRsOTRIeTFteldHUkZsait0dXgvRkFn\r\
  \nTmFBWHoyV0ZhUFpmWGZsOVh6V3NycWRhbXNHTVZMdnlhNFJGSGRMVitzNTJLd1dRdDJwNUJqWFlS\r\
  \nWlFNT3M0c3EzVlF0MHI1RG4yVUpvSEhPSm42OFYrN3U3bmlEdnJRZTdYL2Vsajh0ZlJ4amdCM0Vq\r\
  \nYitsSUVBQUFxAH4AIXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAVdAAIZW5jaGFudHN0AAtyZXBhaXItY29zdHVxAH4ABgAAAARxAH4AGXQAClVO\r\
  \nU1BFQ0lGSUNzcQB+AAN1cQB+AAYAAAAEdAAETFVDS3QABExVUkV0AAdNRU5ESU5HdAAKRFVSQUJJ\r\
  \nTElUWXVxAH4ABgAAAARzcQB+AA4AAAADcQB+ADtzcQB+AA4AAAABcQB+ADtxAH4APHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4A\r\
  \nMHEAfgAxdXEAfgAGAAAABHEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAGdAAMV0FURVJfV09S\r\
  \nS0VScQB+ADh0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUx0AAZPWFlHRU50AAZUSE9STlNxAH4A\r\
  \nOXVxAH4ABgAAAAZxAH4APHEAfgA8c3EAfgAOAAAABHEAfgA7cQB+ADtxAH4AO3NxAH4ADgAAAAdz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4AFXEAfgAwcQB+ADF1cQB+AAYAAAAEcQB+ABlxAH4AR3NxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nOHEAfgBLcQB+AE1xAH4AOXVxAH4ABgAAAARxAH4APHEAfgBPcQB+ADtxAH4AO3EAfgA7c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAABXEAfgA4cQB+AEt0\r\
  \nAAtTV0lGVF9TTkVBS3EAfgBNcQB+ADl1cQB+AAYAAAAFcQB+ADxxAH4AT3EAfgA7cQB+ADtxAH4A\r\
  \nO3EAfgA7c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgBHc3EAfgADdXEAfgAGAAAAB3QA\r\
  \nDURFUFRIX1NUUklERVJ0AA9QUk9URUNUSU9OX0ZBTExxAH4AOHEAfgBLdAAKU09VTF9TUEVFRHEA\r\
  \nfgBNcQB+ADl1cQB+AAYAAAAHcQB+ADtxAH4AT3EAfgA8cQB+AE9xAH4AO3EAfgA7cQB+ADtzcQB+\r\
  \nAA4AAAA/c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAB1RSSURFTlRzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4A\r\
  \nFXEAfgAwcQB+ADF0AAZEYW1hZ2V1cQB+AAYAAAAFcQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAAR0\r\
  \nAApDSEFOTkVMSU5HdAAISU1QQUxJTkd0AAdMT1lBTFRZcQB+ADl1cQB+AAYAAAAEcQB+ADxzcQB+\r\
  \nAA4AAAAFcQB+ADtxAH4AO3EAfgA7c3EAfgAOAAAAfXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AgnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADBxAH4AMXEAfgCGdXEAfgAGAAAABXEAfgAZcQB+ADNz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AIt0AAdSSVBUSURFcQB+ADl1cQB+AAYAAAADcQB+AI5xAH4AO3EA\r\
  \nfgA7cQB+ADxzcQB+AA4AAACLc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnQA\r\
  \nBmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABZFTkNIQU5URURfR09MREVOX0FQUExF\r\
  \nc3EAfgAOAAAAE3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AA1ORVRIRVJJVEVfSE9Fc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ABVxAH4AMHEAfgCGdXEAfgAGAAAABHEAfgAZcQB+ADNzcQB+AAN1cQB+AAYAAAAE\r\
  \ndAAJRElHX1NQRUVEdAARTE9PVF9CT05VU19CTE9DS1NxAH4AOHEAfgA5dXEAfgAGAAAABHEAfgCO\r\
  \ncQB+ADtxAH4APHEAfgA7c3EAfgAOAAABC3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0hPRXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgAzc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgCycQB+ADh0AApTSUxLX1RPVUNIcQB+ADl1cQB+AAYAAAAEcQB+AI5x\r\
  \nAH4APHEAfgA8cQB+ADtxAH4APHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFORVRIRVJJVEVfUElDS0FYRXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADBxAH4AMXVxAH4ABgAAAARxAH4AGXEAfgAzc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgCycQB+ALNxAH4AOHEAfgA5dXEAfgAGAAAABHEAfgCOcQB+ADtxAH4A\r\
  \nPHEAfgA7cQB+ADtzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AMlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nFXEAfgAwcQB+ADF1cQB+AAYAAAAEcQB+ABlxAH4AM3NxAH4AA3VxAH4ABgAAAARxAH4AsnEAfgA4\r\
  \ncQB+AMJxAH4AOXVxAH4ABgAAAARxAH4AjnEAfgA8cQB+ADxxAH4AO3EAfgBQc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nCUhBWV9CTE9DS3EAfgB8c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4A\r\
  \nBgAAAANxAH4ADXNxAH4ADgAADnR0ABNESUFNT05EX0hPUlNFX0FSTU9Sc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADVNI\r\
  \nVUxLRVJfU0hFTExzcQB+AA4AAAAJc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0ABBUT1RFTV9PRl9VTkRZSU5Hc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nCUdVTlBPV0RFUnNxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AKF1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+APtxAH4A/HNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AoXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4A+3EA\r\
  \nfgD8c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgChdXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHEAfgD7cQB+APxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AKF1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+APtxAH4A/HNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AoXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9O\r\
  \nRVRIRVJJVEVfU0NSQVBzcQB+AA4AAAACc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgChdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9JTkdPVHEAfgCO\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4A\r\
  \nDgAADnRxAH4A9XNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAAD\r\
  \ncQB+AA1zcQB+AA4AAA50cQB+APU=\r\n"
xp: 1959.0
health: 24.0
hunger: 18
saturation: 0.0
location:
  world: world
  x: 8549.0
  y: -51.0
  z: 566.6
logType: JOIN
version: v1_20_R3
