upgrade: life_bonus
recipeType: SHAPED
ingredients:
  '0': BLAZE_POWDER
  '1': GLISTERING_MELON_SLICE
  '2': BLAZE_POWDER
  '3': GLISTERING_MELON_SLICE
  '4': NETHERITE_INGOT
  '5': GLISTERING_MELON_SLICE
  '6': BLAZE_POWDER
  '7': GLISTERING_MELON_SLICE
  '8': BLAZE_POWDER
