upgrade: magnetism
recipeType: SHAPED
ingredients:
  '0': DIAMOND_SWORD
  '1': DIAMOND
  '2': DIAMOND_PICKAXE
  '3': DIAMOND
  '4': ENDER_PEARL
  '5': DIAMOND
  '6': DIAMOND_PICKAXE
  '7': DIAMOND
  '8': DIAMOND_SWORD
