inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EA\r\
  \nfgAOAAAOdHQACVdISVRFX0JFRHNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+AAp0\r\
  \nAAZhbW91bnRxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AARCT09Lc3EAfgAOAAAAAnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZ0ABFjdXN0b20tbW9kZWwtZGF0YXQA\r\
  \nElB1YmxpY0J1a2tpdFZhbHVlc3VxAH4ABgAAAAVxAH4AGXQAClVOU1BFQ0lGSUN0AEd7Iml0YWxp\r\
  \nYyI6ZmFsc2UsInRyYW5zbGF0ZSI6InZhbmVfZW5jaGFudG1lbnRzLml0ZW1fYW5jaWVudF90b21l\r\
  \nLm5hbWUifXNxAH4ADgB3AAB0AGp7CiAgICAidmFuZTpjdXN0b21faXRlbV9pZGVudGlmaWVyIjog\r\
  \nInZhbmVfZW5jaGFudG1lbnRzOmFuY2llbnRfdG9tZSIsCiAgICAidmFuZTpjdXN0b21faXRlbV92\r\
  \nZXJzaW9uIjogMQp9c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklST05fU1dPUkRzcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
  \ncQB+AAhxAH4AFXQABkRhbWFnZXVxAH4ABgAAAANxAH4AGXEAfgBBc3EAfgAOAAAAGXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAI\r\
  \nT0FLX0JPQVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAALSVJPTl9TSE9WRUxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nAAhxAH4AFXEAfgBOdXEAfgAGAAAAA3EAfgAZcQB+AEFzcQB+AA4AAAANc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADElS\r\
  \nT05fUElDS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AE51cQB+AAYAAAAD\r\
  \ncQB+ABlxAH4AQXNxAH4ADgAAAB9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAISVJPTl9BWEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4AFXEAfgBOdXEAfgAGAAAAA3EAfgAZcQB+AEFzcQB+AA4AAAAJc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA2dXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQABUJSRUFEc3EAfgAOAAAAOXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ANnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AARCRUVGc3EAfgAOAAAADHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANnVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AARDT0FMc3EAfgAOAAAAEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ANnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApTVUdBUl9DQU5Fc3EAfgAOAAAACnNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANnVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAZDQVJST1RzcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgA2dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADFJPVFRFTl9GTEVTSHNxAH4ADgAA\r\
  \nAARzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAEQk9ORXEAfgChc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgA2dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAA3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANnVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAdMRUFUSEVSc3EAfgAOAAAAB3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA5HT0xERU5fUElDS0FYRXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAIZW5jaGFudHN1cQB+AAYAAAADcQB+ABlxAH4A\r\
  \nQXNyADdjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNlcmlhbGl6ZWRG\r\
  \nb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+AAYAAAABdAAJRElHX1NQRUVEdXEAfgAGAAAAAXNxAH4A\r\
  \nDgAAAAVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAAKT0FLX1BMQU5LU3NxAH4ADgAAADVzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALV0hFQVRf\r\
  \nU0VFRFNxAH4AOnBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElBTU9ORHEAfgCTc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA2dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABERJUlRzcQB+\r\
  \nAA4AAAALc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA2dXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHEAfgA5cQB+AIVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nCXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAB0xFQ1RFUk5zcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQACllFTExPV19C\r\
  \nRURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAFU1RJQ0txAH4AOnBwc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nAAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AA1CUkVXSU5HX1NUQU5EcHBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADZ1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAFQVBQTEVxAH4AoXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+\r\
  \nAAYAAAADcQB+AA1zcQB+AA4AAA50dAALRklSRV9DSEFSR0Vwc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA2dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPQkJMRVNU\r\
  \nT05FcQB+AOBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0ABJMRUFUSEVSX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4AFXEAfgC/cQB+AE51cQB+AAYAAAAEcQB+ABl0AA9DT0xPUkFCTEVfQVJN\r\
  \nT1JzcQB+AAN1cQB+AAYAAAACdAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMdAAKRFVSQUJJTElU\r\
  \nWXVxAH4ABgAAAAJxAH4AOnEAfgA6c3EAfgAOAAAAGHBw\r\n"
xp: 41.0
health: 20.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 6243.6
  y: 63.0
  z: 545.7
logType: JOIN
version: v1_20_R3
