inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAADc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAknsidGV4dCI6\r\
  \nIiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGlj\r\
  \nIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6\r\
  \nInllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5p\r\
  \ncXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03\r\
  \nMDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2Gd\r\
  \nAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7\r\
  \nAgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRG\r\
  \nYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QA\r\
  \nBXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkw\r\
  \nWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZ\r\
  \nV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05X\r\
  \nRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQACk9BS19QTEFOS1NzcQB+AA8AAAAlc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EA\r\
  \nfgAPAAAOdHQABUJSRUFEc3EAfgAPAAAAPXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AF3QABkRhbWFnZXVxAH4ABgAAAANxAH4AG3QAClVO\r\
  \nU1BFQ0lGSUNzcQB+AA8AAAACc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgAMdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQADElST05fUElDS0FYRXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHEAfgAXcQB+AEZ1cQB+AAYAAAADcQB+ABtxAH4ASHNxAH4ADwAAAB9wcHBw\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4A\r\
  \nDwAADnR0AAhPQUtfQk9BVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nDHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAhJUk9OX0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAXcQB+AEZ1cQB+AAYAAAADcQB+ABtxAH4ASHNxAH4ADwAAACtzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50\r\
  \ndAAGQ0FSUk9UcQB+ADxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1\r\
  \ncQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAALSVJPTl9TSE9WRUxzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AF3EAfgBGdXEAfgAGAAAAA3EAfgAbcQB+AEhzcQB+AA8AAAANc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAO\r\
  \ndHQABUFSUk9XcQB+ABNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAKSVJPTl9JTkdPVHNxAH4ADwAAAARzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50\r\
  \ndAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAXcQB+AEZ1cQB+AAYA\r\
  \nAAADcQB+ABtxAH4ASHNxAH4ADwAAACdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAEQkVFRnNxAH4ADwAAABRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8A\r\
  \nAA50dAAEQ09BTHNxAH4ADwAAABJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAKU1VHQVJfQ0FORXNxAH4ADwAAAApwc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EA\r\
  \nfgAPAAAOdHQADFJPVFRFTl9GTEVTSHEAfgCDc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABEJPTkVxAH4Ag3BzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8A\r\
  \nAA50dAAHTEVBVEhFUnEAfgCjc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABUFQUExFcQB+ABNwc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABlNU\r\
  \nUklOR3EAfgCDc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgAOc3EAfgAPAAAOdHQAB0RJQU1PTkRzcQB+AA8AAAAHc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQABVNUSUNL\r\
  \ncQB+AMhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\r\
  \ncQB+AA5zcQB+AA8AAA50dAAEQk9PS3NxAH4ADwAAAB5zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nAAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAPAAAOdHQAB0xFQ1RFUk5zcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAOc3EAfgAPAAAOdHQABlNB\r\
  \nRERMRXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMdXEAfgAG\r\
  \nAAAABXEAfgAOc3EAfgAPAAAOdHEAfgDUcQB+AElzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhx\r\
  \nAH4AF3EAfgAYdAARY3VzdG9tLW1vZGVsLWRhdGF0ABJQdWJsaWNCdWtraXRWYWx1ZXN1cQB+AAYA\r\
  \nAAAFcQB+ABtxAH4ASHQAR3siaXRhbGljIjpmYWxzZSwidHJhbnNsYXRlIjoidmFuZV9lbmNoYW50\r\
  \nbWVudHMuaXRlbV9hbmNpZW50X3RvbWUubmFtZSJ9c3EAfgAPAHcAAHQAansKICAgICJ2YW5lOmN1\r\
  \nc3RvbV9pdGVtX2lkZW50aWZpZXIiOiAidmFuZV9lbmNoYW50bWVudHM6YW5jaWVudF90b21lIiwK\r\
  \nICAgICJ2YW5lOmN1c3RvbV9pdGVtX3ZlcnNpb24iOiAxCn1zcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAKR1JJTkRTVE9O\r\
  \nRXEAfgBJc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4A\r\
  \nDnNxAH4ADwAADnR0AA1CUkVXSU5HX1NUQU5Ec3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nAAlxAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnRxAH4AWnBzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAANSVJPTl9M\r\
  \nRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAXcQB+AEZ1cQB+AAYAAAADcQB+\r\
  \nABt0AAVBUk1PUnNxAH4ADwAAABdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAASTEVBVEhFUl9DSEVTVFBMQVRFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABd0AAhlbmNoYW50c3EAfgBGdXEAfgAGAAAABHEAfgAb\r\
  \ndAAPQ09MT1JBQkxFX0FSTU9Sc3EAfgADdXEAfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJPTk1F\r\
  \nTlRBTHQACkRVUkFCSUxJVFl1cQB+AAYAAAACcQB+AElxAH4ASXNxAH4ADwAAAC5zcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50\r\
  \ndAALSVJPTl9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AF3EAfgBGdXEAfgAG\r\
  \nAAAAA3EAfgAbcQB+AQtzcQB+AA8AAAAac3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx\r\
  \nAH4ACnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0ABBUT1RFTV9PRl9VTkRZSU5H\r\n"
xp: 85.0
health: 20.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 16174.3
  y: 64.0
  z: -707.4
logType: JOIN
version: v1_20_R3
