inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQi\r\
  \nOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVk\r\
  \nIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFs\r\
  \nc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1\r\
  \ncQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0\r\
  \nZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQA\r\
  \nAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhy\r\
  \nABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhw\r\
  \nP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRY\r\
  \nSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNK\r\
  \naFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1Ey\r\
  \nWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14\r\
  \nAHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50dXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NzcQB+AA4AAAARc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUJSRUFE\r\
  \nc3EAfgAOAAAAOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AFXQABkRhbWFnZXVxAH4ABgAAAANxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AA4A\r\
  \nAAA0c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQADElST05fUElDS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAVcQB+AEV1cQB+AAYAAAADcQB+ABlxAH4AR3NxAH4ADgAAAEFzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKSVJPTl9T\r\
  \nV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AEV1cQB+AAYAAAADcQB+ABlx\r\
  \nAH4AR3NxAH4ADgAAACpwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACElST05fQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+ABVxAH4ARXVxAH4ABgAAAANxAH4AGXEAfgBHc3EAfgAOAAAAfnNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAtDT0JCTEVTVE9ORXNxAH4ADgAAAAJzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEA\r\
  \nfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAEUNBUlRPR1JBUEhZX1RBQkxFc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQACUhBWV9CTE9DS3NxAH4ADgAAAApzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAAFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAC0lST05fU0hPVkVMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4ARXVx\r\
  \nAH4ABgAAAANxAH4AGXEAfgBHc3EAfgAOAAAADXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVBUlJPV3NxAH4ADgAAAANz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAKSVJPTl9JTkdPVHNxAH4ADgAAAAlwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AMHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AARDT0FMc3EAfgAO\r\
  \nAAAAEnBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAN\r\
  \nc3EAfgAOAAAOdHQACllFTExPV19CRURwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHTEVBVEhFUnNxAH4ADgAAAA9w\r\
  \ncHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADB1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAHRElBTU9ORHNxAH4ADgAAAAdwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgAwdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJPT0tzcQB+AA4A\r\
  \nAAAec3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNx\r\
  \nAH4ADgAADnR0AAdMRUNURVJOcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUlST05fTEVHR0lOR1NzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgBFdXEAfgAGAAAAA3EAfgAZdAAFQVJNT1JzcQB+\r\
  \nAA4AAAAdc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAEkxFQVRIRVJfQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAVdAAIZW5jaGFudHNxAH4ARXVxAH4ABgAAAARxAH4AGXQAD0NPTE9SQUJMRV9B\r\
  \nUk1PUnNxAH4AA3VxAH4ABgAAAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUx0AApEVVJBQklM\r\
  \nSVRZdXEAfgAGAAAAAnEAfgBwcQB+AHBzcQB+AA4AAAAyc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0lST05fSEVMTUVU\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4ARXVxAH4ABgAAAANxAH4AGXEAfgDQ\r\
  \nc3EAfgAOAAAAIHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAAD\r\
  \ncQB+AA1zcQB+AA4AAA50dAAQVE9URU1fT0ZfVU5EWUlORw==\r\n"
xp: 150.0
health: 20.0
hunger: 20
saturation: 8.0
location:
  world: world
  x: 16163.5
  y: 63.0
  z: -710.5
logType: JOIN
version: v1_20_R3
