inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAA4nNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAAF3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMQkFLRURfUE9UQVRPc3EAfgAOAAAAIHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4A\r\
  \nAA50dAAIT0FLX0JPQVRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAG\r\
  \nAAAAA3EAfgANc3EAfgAOAAAOdHQACE9BS19ET09Sc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNQT05HRXNxAH4ADgAA\r\
  \nAAlzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EA\r\
  \nfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4ADgAAADlzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAHRElBTU9ORHNxAH4ADgAAAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKR0xBU1NfUEFORXEAfgBfc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABV0AAxkaXNw\r\
  \nbGF5LW5hbWV0AAtza3VsbC1vd25lcnVxAH4ABgAAAARxAH4AGHQABVNLVUxMdACSeyJ0ZXh0Ijoi\r\
  \nIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMi\r\
  \nOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoi\r\
  \neWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlx\r\
  \ndWVJZHQACnByb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcw\r\
  \nNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0D\r\
  \nAAFJAARzaXpleHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsC\r\
  \nAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZh\r\
  \nY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAF\r\
  \ndmFsdWV0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBa\r\
  \nWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlX\r\
  \nUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldF\r\
  \nNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAEQkVFRnNxAH4ADgAAABJwc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQABlBPVElPTnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAALcG90aW9uLXR5cGV1\r\
  \ncQB+AAYAAAADcQB+ABhxAH4AkXQAG21pbmVjcmFmdDpsb25nX25pZ2h0X3Zpc2lvbnNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnRxAH4AkXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AJV1cQB+AAYAAAADcQB+\r\
  \nABhxAH4AkXQAG21pbmVjcmFmdDpsb25nX25pZ2h0X3Zpc2lvbnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AkXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+AJV1cQB+AAYAAAADcQB+ABhxAH4AkXQAG21p\r\
  \nbmVjcmFmdDpsb25nX25pZ2h0X3Zpc2lvbnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtTQ0FGRk9MRElOR3NxAH4ADgAA\r\
  \nABpzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAKUFJJU01BUklORXNxAH4ADgAAACNzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJFzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCVdXEAfgAGAAAAA3EAfgAYcQB+AJF0AB5taW5l\r\
  \nY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhpbmdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJFzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4AFXEAfgCVdXEAfgAGAAAAA3EAfgAYcQB+AJF0AB5taW5lY3JhZnQ6bG9u\r\
  \nZ193YXRlcl9icmVhdGhpbmdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJFzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nAAhxAH4AFXEAfgCVdXEAfgAGAAAAA3EAfgAYcQB+AJF0AA9taW5lY3JhZnQ6d2F0ZXJzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAALU1RPTkVfU1dPUkRzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgAWdXEA\r\
  \nfgAGAAAAA3EAfgAYcQB+ABlxAH4ALnBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAATUFJJU01BUklORV9DUllTVEFMU3Nx\r\
  \nAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHQAEFBIQU5UT01fTUVNQlJBTkVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALU0VBX0xBTlRFUk5x\r\
  \nAH4ALnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtDT09LRURfQkVFRnNxAH4ADgAAAARzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPQ09PS0VE\r\
  \nX1BPUktDSE9QcQB+APtzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAAAANxAH4AGHEAfgAZc3EAfgAOAAAAEHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnRxAH4AV3EAfgAuc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NxAH4AMHNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBQ\r\
  \nUklTTUFSSU5FX1NIQVJEc3EAfgAOAAAAE3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARUFJJU01BUklORV9CUklDS1Nx\r\
  \nAH4AOHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQACklST05fQk9PVFNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABh0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAJ0ABhQ\r\
  \nUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AK3VxAH4ABgAAAAJxAH4A+3EAfgAtc3EAfgAOAAAA\r\
  \ncXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+AS9zcgA3Y29tLmdvb2dsZS5jb21tb24uY29s\r\
  \nbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgADdXEAfgAG\r\
  \nAAAAAXEAfgArdXEAfgAGAAAAAXEAfgAtc3EAfgAOAAAAc3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9JUk9OX0NIRVNU\r\
  \nUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAE\r\
  \ncQB+ABhxAH4BL3NxAH4AA3VxAH4ABgAAAAJxAH4BMnEAfgArdXEAfgAGAAAAAnEAfgD7cQB+AC1z\r\
  \ncQB+AA4AAAB2cHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4AFXEAfgAWdAANYmxvY2tNYXRlcmlhbHVxAH4ABgAAAARxAH4AGHQAC1RJTEVfRU5USVRZc3EA\r\
  \nfgAOAAAAFHEAfgFX\r\n"
xp: 740.0
health: 24.0
hunger: 20
saturation: 2.0
location:
  world: world
  x: 9208.5
  y: 41.0
  z: 191.8
logType: WORLD_CHANGE
version: v1_20_R3
