inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAArHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAAD3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVBQTEVzcQB+AA4AAAAFc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhP\r\
  \nQUtfQk9BVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0ABFQUklTTUFSSU5FX0JSSUNLU3NxAH4ADgAAABJzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAIT0FLX0RPT1JxAH4ALnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+\r\
  \nAAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAdESUFNT05EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKR0xBU1NfUEFORXNxAH4ADgAAAAZzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRpc3Bs\r\
  \nYXktbmFtZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAYdAAFU0tVTEx0AJJ7InRleHQiOiIi\r\
  \nLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6\r\
  \nZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5\r\
  \nZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1\r\
  \nZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0\r\
  \nZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMA\r\
  \nAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIA\r\
  \nAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFj\r\
  \ndG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2\r\
  \nYWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpY\r\
  \naDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdS\r\
  \naE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1\r\
  \nWVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AARCRUVGcQB+AEVzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMQkFL\r\
  \nRURfUE9UQVRPc3EAfgAOAAAAJXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZQT1RJT05zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AFXQAC3BvdGlvbi10eXBldXEAfgAGAAAAA3EAfgAYcQB+AJZ0ABttaW5lY3Jh\r\
  \nZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
  \ncQB+AAhxAH4AFXEAfgCadXEAfgAGAAAAA3EAfgAYcQB+AJZ0ABttaW5lY3JhZnQ6bG9uZ19uaWdo\r\
  \ndF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEA\r\
  \nfgCadXEAfgAGAAAAA3EAfgAYcQB+AJZ0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAALU0NBRkZPTERJTkdzcQB+AA4AAAAac3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAClBSSVNNQVJJTkVzcQB+\r\
  \nAA4AAAAWc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHEAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4A\r\
  \nmnVxAH4ABgAAAANxAH4AGHEAfgCWdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHEAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AmnVxAH4ABgAA\r\
  \nAANxAH4AGHEAfgCWdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEA\r\
  \nfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AmnVxAH4ABgAAAANxAH4AGHEA\r\
  \nfgCWdAAPbWluZWNyYWZ0OndhdGVyc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NUT05FX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAAAANxAH4AGHEAfgAZcQB+AC5zcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAADQ09EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAATUFJJU01BUklORV9DUllTVEFMU3EAfgAtc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0\r\
  \nABBQSEFOVE9NX01FTUJSQU5Fc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NFQV9MQU5URVJOcQB+AC5zcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAALQ09PS0VEX0JFRUZzcQB+AA4AAAAEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0NPT0tFRF9QT1JLQ0hPUHEAfgEF\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQAD0ZMSU5UX0FORF9TVEVFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAVcQB+ABZ1cQB+AAYAAAADcQB+ABhxAH4AGXNxAH4ADgAAABBzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKV0VUX1NQ\r\
  \nT05HRXEAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NzcQB+AA4AAAAXc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEFBS\r\
  \nSVNNQVJJTkVfU0hBUkRzcQB+AA4AAAANcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApJUk9OX0JPT1RTc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYdAAFQVJN\r\
  \nT1JzcQB+AAN1cQB+AAYAAAACdAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+ACt1cQB+AAYA\r\
  \nAAACcQB+AQVxAH4ALXNxAH4ADgAAAGJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANSVJPTl9MRUdHSU5HU3NxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgE1c3IA\r\
  \nN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0A\r\
  \nAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAFxAH4AK3VxAH4ABgAAAAFxAH4ALXNxAH4ADgAAAGRz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAPSVJPTl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+ATVzcQB+AAN1cQB+AAYAAAACcQB+AThxAH4A\r\
  \nK3VxAH4ABgAAAAJxAH4BBXEAfgAtc3EAfgAOAAAAZnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtJUk9OX0hFTE1FVHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEA\r\
  \nfgE1c3EAfgFFdXEAfgAGAAAAAXEAfgE4dXEAfgAGAAAAAXEAfgEFc3EAfgAOAAAAknNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWdAANYmxvY2tN\r\
  \nYXRlcmlhbHVxAH4ABgAAAARxAH4AGHQAC1RJTEVfRU5USVRZcQB+ADBxAH4Baw==\r\n"
xp: 679.0
health: 20.0
hunger: 19
saturation: 0.0
location:
  world: world_nether
  x: 1159.5
  y: 45.0
  z: 21.9
logType: WORLD_CHANGE
version: v1_20_R3
