inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAApHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAABnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVBQTEVzcQB+AA4AAAAHc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhP\r\
  \nQUtfQk9BVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AApQUklTTUFSSU5FcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAIT0FLX0RPT1Jx\r\
  \nAH4ALnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1z\r\
  \ncQB+AA4AAA50dAAQUEhBTlRPTV9NRU1CUkFORXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBQUklTTUFSSU5FX1NIQVJE\r\
  \nc3EAfgAOAAAADHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAdESUFNT05EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKR0xBU1NfUEFO\r\
  \nRXEAfgAwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+ABV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVxAH4ABgAAAARxAH4AGHQABVNLVUxM\r\
  \ndACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZh\r\
  \nbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFs\r\
  \nc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
  \ncQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQA\r\
  \nJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlM\r\
  \naXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNo\r\
  \nTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDR\r\
  \nAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQA\r\
  \nCHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJ\r\
  \nbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6\r\
  \nWmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1V\r\
  \nM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAEQkVFRnNxAH4ADgAA\r\
  \nABJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAAMQkFLRURfUE9UQVRPc3EAfgAOAAAAJXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZQT1RJT05z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQAC3BvdGlvbi10eXBldXEAfgAGAAAAA3EA\r\
  \nfgAYcQB+AJZ0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJZzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCadXEAfgAGAAAAA3EAfgAYcQB+AJZ0ABtt\r\
  \naW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4AFXEAfgCadXEAfgAGAAAAA3EAfgAYcQB+AJZ0ABttaW5lY3JhZnQ6bG9u\r\
  \nZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALU0NBRkZPTERJTkdzcQB+AA4AAAAac3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxX\r\
  \nQVRFUl9CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nFXEAfgCadXEAfgAGAAAAA3EAfgAYcQB+AJZ0AB5taW5lY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhp\r\
  \nbmdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCadXEA\r\
  \nfgAGAAAAA3EAfgAYcQB+AJZ0AB5taW5lY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhpbmdzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AJZzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCadXEAfgAGAAAAA3EA\r\
  \nfgAYcQB+AJZ0AA9taW5lY3JhZnQ6d2F0ZXJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALU1RPTkVfU1dPUkRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgAWdXEAfgAGAAAAA3EAfgAYcQB+ABlxAH4ALnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AANDT0RxAH4ALXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABNQUklTTUFSSU5FX0NSWVNUQUxTcQB+AC1z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAARUFJJU01BUklORV9CUklDS1NzcQB+AA4AAAAIc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NFQV9M\r\
  \nQU5URVJOcQB+AC5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAALQ09PS0VEX0JFRUZzcQB+AA4AAAAEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nD0NPT0tFRF9QT1JLQ0hPUHEAfgEFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0ZMSU5UX0FORF9TVEVFTHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVcQB+ABZ1cQB+AAYAAAADcQB+ABhxAH4AGXNxAH4ADgAA\r\
  \nABBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NzcQB+AA4AAAAXcHBwcHBzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKSVJP\r\
  \nTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAA\r\
  \nAARxAH4AGHQABUFSTU9Sc3EAfgADdXEAfgAGAAAAAnQAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRB\r\
  \nTHEAfgArdXEAfgAGAAAAAnEAfgEFcQB+AC1zcQB+AA4AAABhc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUlST05fTEVH\r\
  \nR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAE\r\
  \ncQB+ABhxAH4BKHNyADdjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNl\r\
  \ncmlhbGl6ZWRGb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+AAYAAAABcQB+ACt1cQB+AAYAAAABcQB+\r\
  \nAC1zcQB+AA4AAABkc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0lST05fQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgEoc3EAfgADdXEAfgAG\r\
  \nAAAAAnEAfgErcQB+ACt1cQB+AAYAAAACcQB+AQVxAH4ALXNxAH4ADgAAAGVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAL\r\
  \nSVJPTl9IRUxNRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+\r\
  \nAAYAAAAEcQB+ABhxAH4BKHNxAH4BOHVxAH4ABgAAAAFxAH4BK3VxAH4ABgAAAAFxAH4BBXNxAH4A\r\
  \nDgAAAJFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\r\
  \nAH4AFnQADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABh0AAtUSUxFX0VOVElUWXNxAH4ADgAA\r\
  \nAApxAH4BXg==\r\n"
xp: 669.0
health: 20.0
hunger: 19
saturation: 0.4000001
location:
  world: world_nether
  x: 1159.5
  y: 45.0
  z: 22.6
logType: WORLD_CHANGE
version: v1_20_R3
