inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAApHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAABnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVBQTEVzcQB+AA4AAAAHc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhP\r\
  \nQUtfQk9BVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AApQUklTTUFSSU5FcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAIT0FLX0RPT1Jx\r\
  \nAH4ALnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1z\r\
  \ncQB+AA4AAA50dAAQUEhBTlRPTV9NRU1CUkFORXBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElBTU9ORHEAfgAtc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQACkdMQVNTX1BBTkVxAH4AMHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+\r\
  \nAAYAAAAEcQB+ABh0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3Bh\r\
  \nY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2Us\r\
  \nInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAA\r\
  \nA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNz\r\
  \ncgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdq\r\
  \nYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51\r\
  \ndGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAM\r\
  \ndwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5\r\
  \nSlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1W\r\
  \nMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6\r\
  \nTnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQABEJFRUZzcQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADEJBS0VEX1BPVEFUT3NxAH4ADgAAACVz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAGUE9USU9Oc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAtwb3Rp\r\
  \nb24tdHlwZXVxAH4ABgAAAANxAH4AGHEAfgCPdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9u\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgCPc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4Ak3VxAH4A\r\
  \nBgAAAANxAH4AGHEAfgCPdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEA\r\
  \nfgCPc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4Ak3VxAH4ABgAAAANxAH4AGHEA\r\
  \nfgCPdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NDQUZGT0xESU5H\r\
  \nc3EAfgAOAAAAGnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAAD\r\
  \ncQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCPc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4Ak3VxAH4ABgAAAANxAH4AGHEAfgCPdAAebWluZWNyYWZ0\r\
  \nOmxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCPc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+ABVxAH4Ak3VxAH4ABgAAAANxAH4AGHEAfgCPdAAebWluZWNyYWZ0Omxvbmdfd2F0\r\
  \nZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCPc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nABVxAH4Ak3VxAH4ABgAAAANxAH4AGHEAfgCPdAAPbWluZWNyYWZ0OndhdGVyc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nC1NUT05FX1NXT1JEc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAA\r\
  \nAANxAH4AGHEAfgAZcQB+AC5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAADQ09EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAATUFJJU01B\r\
  \nUklORV9DUllTVEFMU3EAfgAtc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEVBSSVNNQVJJTkVfQlJJQ0tTc3EAfgAOAAAA\r\
  \nCHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAtTRUFfTEFOVEVSTnEAfgAuc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPT0tFRF9CRUVGc3EA\r\
  \nfgAOAAAABHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AA9DT09LRURfUE9SS0NIT1BxAH4A/nNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9GTElO\r\
  \nVF9BTkRfU1RFRUxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgAWdXEAfgAGAAAA\r\
  \nA3EAfgAYcQB+ABlzcQB+AA4AAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNQT05HRXNxAH4ADgAAABhzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKT0FLX1BMQU5LU3NxAH4ADgAAABdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQUFJJU01BUklORV9TSEFSRHNx\r\
  \nAH4ADgAAAAxwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklST05fQk9PVFNzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABh0AAVBUk1PUnNxAH4AA3VxAH4ABgAA\r\
  \nAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AK3VxAH4ABgAAAAJxAH4A/nEAfgAtc3EA\r\
  \nfgAOAAAAYXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+AS9zcgA3Y29tLmdvb2dsZS5jb21t\r\
  \nb24uY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgAD\r\
  \ndXEAfgAGAAAAAXEAfgArdXEAfgAGAAAAAXEAfgAtc3EAfgAOAAAAZHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9JUk9O\r\
  \nX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+\r\
  \nAAYAAAAEcQB+ABhxAH4BL3NxAH4AA3VxAH4ABgAAAAJxAH4BMnEAfgArdXEAfgAGAAAAAnEAfgD+\r\
  \ncQB+AC1zcQB+AA4AAABlc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0lST05fSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+AS9zcQB+AT91cQB+AAYA\r\
  \nAAABcQB+ATJ1cQB+AAYAAAABcQB+AP5zcQB+AA4AAACRc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZ0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAA\r\
  \nBHEAfgAYdAALVElMRV9FTlRJVFlzcQB+AA4AAAAKcQB+AWU=\r\n"
xp: 669.0
health: 20.0
hunger: 19
saturation: 0.4000001
location:
  world: world
  x: 9208.5
  y: 41.0
  z: 191.4
logType: WORLD_CHANGE
version: v1_20_R3
