inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAArHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAAD3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVBQTEVzcQB+AA4AAAAEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAhP\r\
  \nQUtfQk9BVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0ABFQUklTTUFSSU5FX0JSSUNLU3NxAH4ADgAAABJzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAGU1BPTkdFc3EAfgAOAAAAFHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1\r\
  \ncQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAdESUFNT05EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKR0xBU1NfUEFORXNxAH4ADgAAAAZzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRp\r\
  \nc3BsYXktbmFtZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAYdAAFU0tVTEx0AJJ7InRleHQi\r\
  \nOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxp\r\
  \nYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3Ii\r\
  \nOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVu\r\
  \naXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUt\r\
  \nNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdh\r\
  \nnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA\r\
  \n+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2Fk\r\
  \nRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0\r\
  \nAAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5\r\
  \nMFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5p\r\
  \nWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtO\r\
  \nV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AARCRUVGcQB+AEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAM\r\
  \nQkFLRURfUE9UQVRPc3EAfgAOAAAAJXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZQT1RJT05zcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4AFXQAC3BvdGlvbi10eXBldXEAfgAGAAAAA3EAfgAYcQB+AJd0ABttaW5l\r\
  \nY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJdzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AFXEAfgCbdXEAfgAGAAAAA3EAfgAYcQB+AJd0ABttaW5lY3JhZnQ6bG9uZ19u\r\
  \naWdodF92aXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJdzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nFXEAfgCbdXEAfgAGAAAAA3EAfgAYcQB+AJd0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAALU0NBRkZPTERJTkdzcQB+AA4AAAAac3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAClBSSVNNQVJJTkVz\r\
  \ncQB+AA4AAAAWc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHEAfgCXc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVx\r\
  \nAH4Am3VxAH4ABgAAAANxAH4AGHEAfgCXdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5n\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgCXc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4Am3VxAH4A\r\
  \nBgAAAANxAH4AGHEAfgCXdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHEAfgCXc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4Am3VxAH4ABgAAAANxAH4A\r\
  \nGHEAfgCXdAAPbWluZWNyYWZ0OndhdGVyc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NUT05FX1NXT1JEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAAAANxAH4AGHEAfgAZcQB+AC5zcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAADQ09EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAATUFJJU01BUklORV9DUllTVEFMU3EAfgAtc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAA\r\
  \nDnR0ABBQSEFOVE9NX01FTUJSQU5Fc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NFQV9MQU5URVJOcQB+AC5zcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAALQ09PS0VEX0JFRUZxAH4AOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9DT09LRURfUE9SS0NIT1BxAH4AOHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AA9GTElOVF9BTkRfU1RFRUxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4A\r\
  \nFXEAfgAWdXEAfgAGAAAAA3EAfgAYcQB+ABlzcQB+AA4AAAAQcHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApPQUtfUExB\r\
  \nTktTc3EAfgAOAAAAF3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBQUklTTUFSSU5FX1NIQVJEc3EAfgAOAAAADXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAhPQUtfRE9PUnEAfgAucHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklST05fQk9PVFNzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABh0AAVBUk1PUnNx\r\
  \nAH4AA3VxAH4ABgAAAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AK3VxAH4ABgAAAAJx\r\
  \nAH4AOHEAfgAtc3EAfgAOAAAAYnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+ATVzcgA3Y29t\r\
  \nLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAA\r\
  \nAAAAAgAAeHEAfgADdXEAfgAGAAAAAXEAfgArdXEAfgAGAAAAAXEAfgAtc3EAfgAOAAAAZHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AA9JUk9OX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEA\r\
  \nfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABhxAH4BNXNxAH4AA3VxAH4ABgAAAAJxAH4BOHEAfgArdXEA\r\
  \nfgAGAAAAAnEAfgA4cQB+AC1zcQB+AA4AAABmc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0lST05fSEVMTUVUc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+ATVz\r\
  \ncQB+AUV1cQB+AAYAAAABcQB+ATh1cQB+AAYAAAABcQB+ADhzcQB+AA4AAACSc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nBlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZ0AA1ibG9ja01hdGVy\r\
  \naWFsdXEAfgAGAAAABHEAfgAYdAALVElMRV9FTlRJVFlxAH4AMHEAfgFr\r\n"
xp: 679.0
health: 20.0
hunger: 20
saturation: 2.4
location:
  world: world
  x: 9208.5
  y: 41.0
  z: 191.9
logType: WORLD_CHANGE
version: v1_20_R3
