inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAPBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0cQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4AGnNxAH4AA3VxAH4ABgAAAAZ0AAlLTk9DS0JBQ0t0AA9MT09UX0JPTlVTX01PQlN0AAdN\r\
  \nRU5ESU5HdAANREFNQUdFX1VOREVBRHQADVNXRUVQSU5HX0VER0VxAH4AH3VxAH4ABgAAAAZzcQB+\r\
  \nAA4AAAACcQB+ACJzcQB+AA4AAAABcQB+ACFxAH4AInEAfgAicQB+ACJxAH4AInNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKTkVUSEVSUkFDS3NxAH4ADgAAACNwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEU5FVEhFUklURV9QSUNLQVhF\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAF\r\
  \ncQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAzdAAKU0lMS19UT1VDSHEAfgAfdXEA\r\
  \nfgAGAAAABHEAfgAhcQB+ADhxAH4AOHEAfgAicQB+ACJzcQB+AA4AAAEPc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUdP\r\
  \nTERFTl9DQVJST1RzcQB+AA4AAAAEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACE9BS19ET09Sc3EAfgAOAAAAJXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0AAVUT1JDSHNxAH4ADgAAADlzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEA\r\
  \nfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQABEJFTExzcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
  \ncQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAC0xBVkFfQlVDS0VUc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQAC0VOREVSX1BFQVJMc3EAfgAOAAAAEHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApXRVRfU1BPTkdFc3EA\r\
  \nfgAOAAAAKnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+\r\
  \nAA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAFHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AAdPQUtfTE9Hc3EAfgAOAAAAGXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFQUklTTUFSSU5FX0JSSUNL\r\
  \nU3NxAH4ADgAAAApzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AGNxAH4AQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdESUFNT05EcQB+ACJw\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQAC1NFQV9MQU5URVJOc3EAfgAOAAAAO3BzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AF3QADWJsb2NrTWF0ZXJpYWx1cQB+AAYA\r\
  \nAAAEcQB+ABl0AAtUSUxFX0VOVElUWXNxAH4ADgAAAFtxAH4AsXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1ORVRIRVJJ\r\
  \nVEVfQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+\r\
  \nAAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAANxAH4AHXEAfgBNcQB+AB91cQB+AAYAAAAD\r\
  \ncQB+ACFxAH4AOHEAfgAicQB+ACJzcQB+AA4AAACBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPT0tFRF9CRUVGc3EA\r\
  \nfgAOAAAAGnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4AY3NxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AGNxAH4A03BzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRp\r\
  \nc3BsYXktbmFtZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAZdAAFU0tVTEx0AJJ7InRleHQi\r\
  \nOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxp\r\
  \nYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3Ii\r\
  \nOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVu\r\
  \naXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUt\r\
  \nNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdh\r\
  \nnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA\r\
  \n+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2Fk\r\
  \nRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0\r\
  \nAAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5\r\
  \nMFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5p\r\
  \nWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtO\r\
  \nV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANCT1dzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4AFXEAfgAXdXEAfgAGAAAAA3EAfgAZcQB+ABpzcQB+AA4AAAEBc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAtN\r\
  \nSUxLX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAAD\r\
  \ncQB+AA1zcQB+AA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBGc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AB1xAH4AHnEAfgAzcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4AInEAfgA4\r\
  \ncQB+ACJzcQB+AA4AAADMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgD9c3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAI\r\
  \ncQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0\r\
  \nAA5BUlJPV19JTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ACFx\r\
  \nAH4AInEAfgA4c3EAfgAOAAAAdnNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4APHEAfgALdXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHQAD0ZJUkVXT1JLX1JPQ0tFVHNxAH4A\r\
  \nDgAAADdzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQABXBvd2VydXEAfgAGAAAAA3EA\r\
  \nfgAZdAAIRklSRVdPUktxAH4AOHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGRUxZVFJBc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1cQB+AAYA\r\
  \nAAACcQB+ADNxAH4AH3VxAH4ABgAAAAJxAH4AOHEAfgAicQB+ACJzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVS\r\
  \nSVRFX0JPT1RTc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1\r\
  \ncQB+AAYAAAAFcQB+ABl0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAR0AA1ERVBUSF9TVFJJREVScQB+\r\
  \nADN0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AH3VxAH4ABgAAAARxAH4AInEAfgA4cQB+\r\
  \nAFZxAH4AInNxAH4ADgAAAA9zcQB+AA4AAAAcc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5FVEhFUklURV9MRUdHSU5H\r\
  \nU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAA\r\
  \nBXEAfgAZcQB+AU9zcQB+AAN1cQB+AAYAAAADcQB+ADNxAH4BU3EAfgAfdXEAfgAGAAAAA3EAfgA4\r\
  \ncQB+AFZxAH4AInNxAH4ADgAAAAdzcQB+AA4AAAAxc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAFE5FVEhFUklURV9DSEVT\r\
  \nVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+\r\
  \nAAYAAAAFcQB+ABlxAH4BT3NxAH4AA3VxAH4ABgAAAANxAH4AM3EAfgFTcQB+AB91cQB+AAYAAAAD\r\
  \ncQB+ADhxAH4AVnEAfgAicQB+AWRzcQB+AA4AAAAdc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEE5FVEhFUklURV9IRUxN\r\
  \nRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAA\r\
  \nAAVxAH4AGXEAfgFPc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+AVNxAH4AH3VxAH4ABgAAAANxAH4A\r\
  \nOHEAfgBWcQB+ACJxAH4BZHNxAH4ADgAAABtw\r\n"
xp: 1929.0
health: 26.0
hunger: 20
saturation: 0.0
location:
  world: world_nether
  x: 1159.5
  y: 45.0
  z: 22.2
logType: WORLD_CHANGE
version: v1_20_R3
