inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAQBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRI\r\
  \nRVJSQUNLc3EAfgAOAAAAI3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtTRUFfTEFOVEVSTnEAfgAic3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nEU5FVEhFUklURV9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEA\r\
  \nfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAzdAAK\r\
  \nU0lMS19UT1VDSHEAfgAfdXEAfgAGAAAABHEAfgAhcQB+ADhxAH4AOHEAfgAicQB+ACJzcQB+AA4A\r\
  \nAAETc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQADUdPTERFTl9DQVJST1RxAH4AN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAhPQUtfRE9PUnNx\r\
  \nAH4ADgAAACVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA3cHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAALTEFWQV9CVUNLRVRz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4AAAAQc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBoc3EAfgAOAAAA\r\
  \nHHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+\r\
  \nAA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUFSUk9Xc3EAfgAOAAAAFHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAdPQUtfTE9Hc3EAfgAOAAAAGXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABFQUklTTUFSSU5FX0JSSUNLU3NxAH4A\r\
  \nDgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50cQB+AGhzcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAB0RJQU1PTkRxAH4AInNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKUFJJU01BUklORXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4ARnEAfgCdc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACldFVF9TUE9O\r\
  \nR0VzcQB+AA4AAAATc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAVcQB+ABd0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgAZdAALVElMRV9FTlRJVFlz\r\
  \ncQB+AA4AAABbcQB+ALtzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANTkVUSEVSSVRFX0FYRXNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AB1xAH4AU3EAfgAfdXEAfgAGAAAAA3EAfgAhcQB+ADhxAH4AInEAfgAic3EA\r\
  \nfgAOAAAAgXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAtDT09LRURfQkVFRnNxAH4ADgAAABpwcHBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAL\r\
  \nUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRpc3BsYXktbmFt\r\
  \nZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAZdAAFU0tVTEx0AJJ7InRleHQiOiIiLCJleHRy\r\
  \nYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2Us\r\
  \nInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ci\r\
  \nLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAK\r\
  \ncHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmEx\r\
  \nLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNp\r\
  \nemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2Fj\r\
  \nY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJ\r\
  \ndGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQA\r\
  \ntGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEps\r\
  \nY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxO\r\
  \nRE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpE\r\
  \nTmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANCT1dzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4AFXEAfgAXdXEAfgAGAAAAA3EAfgAZcQB+ABpzcQB+AA4AAAEBc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAtNSUxLX0JVQ0tF\r\
  \nVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+\r\
  \nAA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBMc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AB1xAH4AHnEAfgAzcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4AInEAfgA4cQB+ACJzcQB+\r\
  \nAA4AAADMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHEAfgD8c3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4A\r\
  \nFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0AA5BUlJPV19J\r\
  \nTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ACFxAH4AInEAfgA4\r\
  \nc3EAfgAOAAAAdnBzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+ADxxAH4A\r\
  \nC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRxAH4AaXNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAFcG93ZXJ1cQB+AAYAAAADcQB+ABl0AAhGSVJFV09S\r\
  \nS3EAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAAnEAfgAzcQB+AB91\r\
  \ncQB+AAYAAAACcQB+ADhxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9CT09UU3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZ\r\
  \ndAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RSSURFUnEAfgAzdAAYUFJPVEVDVElP\r\
  \nTl9FTlZJUk9OTUVOVEFMcQB+AB91cQB+AAYAAAAEcQB+ACJxAH4AOHNxAH4ADgAAAARxAH4AInEA\r\
  \nfgCXcQB+AGJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4BTXNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4AM3EAfgFRcQB+AB91cQB+AAYAAAADcQB+ADhxAH4BU3EAfgAic3EAfgAOAAAA\r\
  \nB3NxAH4ADgAAADBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgFNc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAzcQB+AVFxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgFTcQB+ACJxAH4B\r\
  \nYXNxAH4ADgAAACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+AU1zcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+ADNxAH4BUXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AVNxAH4AInEAfgFhc3EA\r\
  \nfgAOAAAAIHA=\r\n"
xp: 2013.0
health: 26.0
hunger: 20
saturation: 3.4000006
location:
  world: world_nether
  x: 1159.5
  y: 45.0
  z: 22.6
logType: WORLD_CHANGE
version: v1_20_R3
