inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAQZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRI\r\
  \nRVJSQUNLc3EAfgAOAAAAI3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtTRUFfTEFOVEVSTnEAfgAic3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nEU5FVEhFUklURV9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEA\r\
  \nfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAzdAAK\r\
  \nU0lMS19UT1VDSHEAfgAfdXEAfgAGAAAABHEAfgAhcQB+ADhxAH4AOHEAfgAicQB+ACJzcQB+AA4A\r\
  \nAAETc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQADUdPTERFTl9DQVJST1RxAH4AN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAhPQUtfRE9PUnNx\r\
  \nAH4ADgAAACVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA3c3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNQT05HRXNx\r\
  \nAH4ADgAAABNzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHQAC0xBVkFfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0VOREVSX1BFQVJMc3EAfgAO\r\
  \nAAAAEHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnRxAH4AaHNxAH4ADgAAABxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAVBUlJPV3NxAH4ADgAAABRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHT0FLX0xPR3NxAH4ADgAAABlzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAARUFJJU01BUklORV9CUklDS1NzcQB+AA4AAAAPc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBoc3EAfgAOAAAA\r\
  \nQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAdESUFNT05EcQB+ACJwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBGcQB+AKRwc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABd0AA1ibG9ja01h\r\
  \ndGVyaWFsdXEAfgAGAAAABHEAfgAZdAALVElMRV9FTlRJVFlzcQB+AA4AAABbcQB+ALVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAANTkVUSEVSSVRFX0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZx\r\
  \nAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAADcQB+AB1xAH4AU3EA\r\
  \nfgAfdXEAfgAGAAAAA3EAfgAhcQB+ADhxAH4AInEAfgAic3EAfgAOAAAAgXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtD\r\
  \nT09LRURfQkVFRnNxAH4ADgAAABpwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRpc3BsYXktbmFtZXQAC3NrdWxsLW93bmVydXEAfgAG\r\
  \nAAAABHEAfgAZdAAFU0tVTEx0AJJ7InRleHQiOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNr\r\
  \nIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJz\r\
  \ndHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0\r\
  \nAA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IA\r\
  \nE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2\r\
  \nYS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRp\r\
  \nbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcI\r\
  \nAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpU\r\
  \nUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBM\r\
  \nM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56\r\
  \nVTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nC01JTEtfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAA\r\
  \nAANxAH4ADXNxAH4ADgAADnR0AA9GTElOVF9BTkRfU1RFRUxzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AExzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAecQB+ADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAicQB+\r\
  \nADhxAH4AInNxAH4ADgAAAMxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAADQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAABXEA\r\
  \nfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAA\r\
  \nAAN0AA5BUlJPV19JTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+\r\
  \nACFxAH4AInEAfgA4c3EAfgAOAAAAdnBzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADxxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRx\r\
  \nAH4AaXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAFcG93ZXJ1cQB+AAYAAAADcQB+\r\
  \nABl0AAhGSVJFV09SS3EAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAVcQB+ABZxAH4ALXVxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAA\r\
  \nAnEAfgAzcQB+AB91cQB+AAYAAAACcQB+ADhxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklU\r\
  \nRV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEA\r\
  \nfgAGAAAABXEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RSSURFUnEAfgAz\r\
  \ndAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+AB91cQB+AAYAAAAEcQB+ACJxAH4AOHNxAH4A\r\
  \nDgAAAARxAH4AInEAfgCecQB+AGJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJTkdTc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlx\r\
  \nAH4BPXNxAH4AA3VxAH4ABgAAAANxAH4AM3EAfgFBcQB+AB91cQB+AAYAAAADcQB+ADhxAH4BQ3EA\r\
  \nfgAic3EAfgAOAAAAB3NxAH4ADgAAADBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVUSEVSSVRFX0NIRVNUUExBVEVz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVx\r\
  \nAH4AGXEAfgE9c3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+AUFxAH4AH3VxAH4ABgAAAANxAH4AOHEA\r\
  \nfgFDcQB+ACJxAH4BUXNxAH4ADgAAACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZ\r\
  \ncQB+AT1zcQB+AAN1cQB+AAYAAAADcQB+ADNxAH4BQXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AUNx\r\
  \nAH4AInEAfgFRc3EAfgAOAAAAIHA=\r\n"
xp: 2049.0
health: 26.0
hunger: 20
saturation: 3.4000006
location:
  world: world
  x: 9208.5
  y: 41.0
  z: 192.2
logType: WORLD_CHANGE
version: v1_20_R3
