inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdAAWeyJ0ZXh0IjoiwqdlQmFja3BhY2sifXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0\r\
  \nAA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IA\r\
  \nE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2\r\
  \nYS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRp\r\
  \nbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcI\r\
  \nAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpU\r\
  \nUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBM\r\
  \nM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56\r\
  \nVTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AA1ORVRIRVJJVEVfSE9Fc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABV0AAhlbmNo\r\
  \nYW50c3QABkRhbWFnZXVxAH4ABgAAAARxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AAN1cQB+AAYAAAAD\r\
  \ndAAJRElHX1NQRUVEdAARTE9PVF9CT05VU19CTE9DS1N0AApEVVJBQklMSVRZdXEAfgAGAAAAA3Nx\r\
  \nAH4ADgAAAAVzcQB+AA4AAAADcQB+AEFzcQB+AA4AAAEUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9T\r\
  \nV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADZ0AAtyZXBhaXItY29zdHVx\r\
  \nAH4ABgAAAARxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAABnQACUtOT0NLQkFDS3QAD0xPT1RfQk9O\r\
  \nVVNfTU9CU3QAB01FTkRJTkd0AA1EQU1BR0VfVU5ERUFEdAANU1dFRVBJTkdfRURHRXEAfgA+dXEA\r\
  \nfgAGAAAABnNxAH4ADgAAAAJxAH4AQXNxAH4ADgAAAAFxAH4AQHEAfgBBcQB+AEFxAH4AQXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4ATHEAfgA3dXEAfgAGAAAABXEAfgAZcQB+ADlzcQB+\r\
  \nAAN1cQB+AAYAAAADdAAOQVJST1dfSU5GSU5JVEV0AAxBUlJPV19EQU1BR0VxAH4APnVxAH4ABgAA\r\
  \nAANxAH4AV3EAfgBAcQB+AEFxAH4AV3NxAH4ADgAAAKxzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AFtxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09S\r\
  \nS19ST0NLRVRzcQB+AA4AAAA8c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dl\r\
  \ncnVxAH4ABgAAAANxAH4AGXQACEZJUkVXT1JLcQB+AFdwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAUTkVUSEVSSVRF\r\
  \nX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+AExxAH4A\r\
  \nN3VxAH4ABgAAAAVxAH4AGXQABUFSTU9Sc3EAfgADdXEAfgAGAAAAA3EAfgBSdAAYUFJPVEVDVElP\r\
  \nTl9FTlZJUk9OTUVOVEFMcQB+AD51cQB+AAYAAAADcQB+AFdzcQB+AA4AAAAEcQB+AEFzcQB+AA4A\r\
  \nAAAHcQB+AFdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAALRU5ERVJfUEVBUkxzcQB+AA4AAAAQc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBe\r\
  \nc3EAfgAOAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAVHTEFTU3NxAH4ADgAAABpzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVJST1dz\r\
  \ncQB+AA4AAAA1c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANx\r\
  \nAH4ADXNxAH4ADgAADnR0AAhTUFlHTEFTU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApJUk9OX0lOR09UcQB+AEBzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAO\r\
  \ndHQAB0ZVUk5BQ0VzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA\r\
  \nA3EAfgANc3EAfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nCHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50cQB+AMBzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+ABFz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlx\r\
  \nAH4AGnQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVk\r\
  \nIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2gi\r\
  \nOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AB9xAH4AIHVxAH4ABgAAAANxAH4AInQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NxAH4AJAAAAAF3BAAAAAFzcQB+ACY/QAAAAAAADHcIAAAAEAAAAAJx\r\
  \nAH4AKXQACHRleHR1cmVzcQB+ACt0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJD\r\
  \nSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dS\r\
  \nall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZq\r\
  \nTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRF\r\
  \nX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgA2cQB+AExxAH4AN3Vx\r\
  \nAH4ABgAAAAVxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAABHEAfgA8cQB+AFJ0AApTSUxLX1RPVUNI\r\
  \ncQB+AD51cQB+AAYAAAAEcQB+AEBxAH4AV3EAfgBXcQB+AEFxAH4AQXNxAH4ADgAAAOhzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AF5xAH4AjHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADkRJQU1PTkRfU0hPVkVMc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+ABVxAH4ANnVxAH4ABgAAAANxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgA8cQB+AD1xAH4APnVxAH4ABgAAAANxAH4AjHEAfgBBcQB+AEFwc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUdP\r\
  \nTERFTl9DQVJST1RxAH4AmnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdESUFNT05EcQB+AEFwcHBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAH\r\
  \nVFJJREVOVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADZxAH4AN3VxAH4ABgAA\r\
  \nAARxAH4AGXEAfgA5c3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAk\r\
  \nU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAF0AAdMT1lBTFRZdXEAfgAG\r\
  \nAAAAAXEAfgBBc3EAfgAOAAAAxnBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX0JPT1RTc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4ANnEAfgBMdXEAfgAGAAAABHEAfgAZcQB+AIdz\r\
  \ncQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RSSURFUnEAfgBScQB+AIpxAH4APnVxAH4ABgAAAARx\r\
  \nAH4AQXEAfgBXcQB+AIxxAH4AQXNxAH4ADgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJ\r\
  \nTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4ANnEAfgBMdXEAfgAGAAAABHEA\r\
  \nfgAZcQB+AIdzcQB+AAN1cQB+AAYAAAADcQB+AFJxAH4AinEAfgA+dXEAfgAGAAAAA3EAfgBXcQB+\r\
  \nAIxxAH4AQXEAfgCNc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAVcQB+ADZxAH4ATHVxAH4ABgAAAARxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAAAnEAfgBS\r\
  \ncQB+AD51cQB+AAYAAAACcQB+AFdxAH4AQXEAfgBBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEE5FVEhFUklURV9IRUxN\r\
  \nRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgA2cQB+AEx1cQB+AAYAAAAEcQB+\r\
  \nABlxAH4Ah3NxAH4AA3VxAH4ABgAAAANxAH4AUnEAfgCKcQB+AD51cQB+AAYAAAADcQB+AFdxAH4A\r\
  \njHEAfgBBcQB+AI1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+ABVxAH4AN3QADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABl0AAtUSUxFX0VOVElUWXNx\r\
  \nAH4ADgAAAFtxAH4BUQ==\r\n"
xp: 1799.0
health: 23.38053321838379
hunger: 16
saturation: 0.0
location:
  world: world
  x: 11417.5
  y: 64.5
  z: 208.5
logType: WORLD_CHANGE
version: v1_20_R3
