inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAQZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRI\r\
  \nRVJSQUNLc3EAfgAOAAAAI3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtTRUFfTEFOVEVSTnEAfgAic3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nEU5FVEhFUklURV9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEA\r\
  \nfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAzdAAK\r\
  \nU0lMS19UT1VDSHEAfgAfdXEAfgAGAAAABHEAfgAhcQB+ADhxAH4AOHEAfgAicQB+ACJzcQB+AA4A\r\
  \nAAETc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQADUdPTERFTl9DQVJST1RxAH4AN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAhPQUtfRE9PUnNx\r\
  \nAH4ADgAAACVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA3c3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNQT05HRXNx\r\
  \nAH4ADgAAABNzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EA\r\
  \nfgANc3EAfgAOAAAOdHQAC0xBVkFfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0VOREVSX1BFQVJMc3EAfgAO\r\
  \nAAAAEHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnRxAH4AaHNxAH4ADgAAABxzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADFdBVEVSX0JVQ0tFVHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAVBUlJPV3NxAH4ADgAAABRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAK\r\
  \ncQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHT0FLX0xPR3NxAH4ADgAAABlzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAARUFJJU01BUklORV9CUklDS1NzcQB+AA4AAAAPc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBoc3EAfgAOAAAA\r\
  \nQHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAdESUFNT05EcQB+ACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAKV0VUX1NQT05HRXNxAH4ADgAA\r\
  \nAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50cQB+AEZxAH4ApHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+ABVxAH4AF3QADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABl0AAtU\r\
  \nSUxFX0VOVElUWXNxAH4ADgAAAFtxAH4AvHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1ORVRIRVJJVEVfQVhFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlx\r\
  \nAH4AGnNxAH4AA3VxAH4ABgAAAANxAH4AHXEAfgBTcQB+AB91cQB+AAYAAAADcQB+ACFxAH4AOHEA\r\
  \nfgAicQB+ACJzcQB+AA4AAACBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPT0tFRF9CRUVGc3EAfgAOAAAAGnBwcHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVdAAM\r\
  \nZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEcQB+ABl0AAVTS1VMTHQAknsidGV4\r\
  \ndCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRh\r\
  \nbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xv\r\
  \nciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAI\r\
  \ndW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJj\r\
  \nNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Z\r\
  \nx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQ\r\
  \nbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxv\r\
  \nYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJl\r\
  \nc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZM\r\
  \neTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pq\r\
  \nTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RG\r\
  \na05XRTVZVFF5WkROak9DSjlmWDA9eAB4cHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJ\r\
  \ncQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAALTUlMS19CVUNLRVRzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAD0ZMSU5U\r\
  \nX0FORF9TVEVFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnRxAH4ATHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAV\r\
  \ncQB+ABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAABHEAfgAdcQB+AB5x\r\
  \nAH4AM3EAfgAfdXEAfgAGAAAABHEAfgAhcQB+ACJxAH4AOHEAfgAic3EAfgAOAAAAzHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AANCT1dzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3Vx\r\
  \nAH4ABgAAAAVxAH4AGXEAfgAac3EAfgADdXEAfgAGAAAAA3QADkFSUk9XX0lORklOSVRFdAAMQVJS\r\
  \nT1dfREFNQUdFcQB+AB91cQB+AAYAAAADcQB+ADhxAH4AIXEAfgAicQB+ADhzcQB+AA4AAAB2cHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+AApxAH4APHEAfgALdXEAfgAGAAAABXEA\r\
  \nfgANc3EAfgAOAAAOdHQAD0ZJUkVXT1JLX1JPQ0tFVHEAfgBpc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4AGXQACEZJUkVXT1JLcQB+ADhzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAGRUxZVFJBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAtdXEA\r\
  \nfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAACcQB+ADNxAH4AH3VxAH4ABgAAAAJxAH4A\r\
  \nOHEAfgAicQB+ACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX0JPT1RTc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABl0AAVBUk1PUnNxAH4A\r\
  \nA3VxAH4ABgAAAAR0AA1ERVBUSF9TVFJJREVScQB+ADN0ABhQUk9URUNUSU9OX0VOVklST05NRU5U\r\
  \nQUxxAH4AH3VxAH4ABgAAAARxAH4AInEAfgA4c3EAfgAOAAAABHEAfgAicQB+AJ5xAH4AYnNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\r\
  \nDgAADnR0ABJORVRIRVJJVEVfTEVHR0lOR1NzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4A\r\
  \nFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgFEc3EAfgADdXEAfgAGAAAAA3EAfgAz\r\
  \ncQB+AUhxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgFKcQB+ACJzcQB+AA4AAAAHc3EAfgAOAAAAMHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0ABRORVRIRVJJVEVfQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4A\r\
  \nCHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+AURzcQB+AAN1cQB+AAYAAAAD\r\
  \ncQB+ADNxAH4BSHEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AUpxAH4AInEAfgFYc3EAfgAOAAAAInNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+\r\
  \nABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4BRHNxAH4AA3VxAH4ABgAAAANxAH4A\r\
  \nM3EAfgFIcQB+AB91cQB+AAYAAAADcQB+ADhxAH4BSnEAfgAicQB+AVhzcQB+AA4AAAAgcA==\r\n"
xp: 2049.0
health: 26.0
hunger: 20
saturation: 3.4000006
location:
  world: world_nether
  x: 1159.5
  y: 45.0
  z: 22.0
logType: WORLD_CHANGE
version: v1_20_R3
