inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAAPhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AApORVRI\r\
  \nRVJSQUNLc3EAfgAOAAAAJHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nPHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTUE9OR0VzcQB+AA4AAAATc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nEU5FVEhFUklURV9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEA\r\
  \nfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAzdAAK\r\
  \nU0lMS19UT1VDSHEAfgAfdXEAfgAGAAAABHEAfgAhcQB+ADhxAH4AOHEAfgAicQB+ACJzcQB+AA4A\r\
  \nAAEPc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEA\r\
  \nfgANc3EAfgAOAAAOdHQADUdPTERFTl9DQVJST1RzcQB+AA4AAAAEc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACE9BS19E\r\
  \nT09Sc3EAfgAOAAAAJXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4ADgAAADpzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQABEJFTExzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAO\r\
  \ndHQAC0xBVkFfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0VOREVSX1BFQVJMc3EAfgAOAAAAEHBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nDFdBVEVSX0JVQ0tFVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVBUlJPV3NxAH4ADgAAABRzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHT0FL\r\
  \nX0xPR3NxAH4ADgAAABlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARUFJJU01BUklORV9CUklDS1NzcQB+AA4AAAAKc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHEAfgBqc3EAfgAOAAAAI3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdESUFNT05EcQB+ACJwc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQAC1NFQV9MQU5URVJOc3EAfgAOAAAAO3BzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AF3QADWJsb2NrTWF0ZXJpYWx1cQB+AAYAAAAEcQB+ABl0\r\
  \nAAtUSUxFX0VOVElUWXNxAH4ADgAAAFtxAH4AsnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1ORVRIRVJJVEVfQVhFc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4AGnNxAH4AA3VxAH4ABgAAAANxAH4AHXEAfgBUcQB+AB91cQB+AAYAAAADcQB+ACFxAH4A\r\
  \nOHEAfgAicQB+ACJzcQB+AA4AAACBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPT0tFRF9CRUVGc3EAfgAOAAAAGnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnRxAH4AanNxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AGpxAH4A1HBzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAL\r\
  \nUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQADGRpc3BsYXktbmFt\r\
  \nZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAZdAAFU0tVTEx0AJJ7InRleHQiOiIiLCJleHRy\r\
  \nYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2Us\r\
  \nInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ci\r\
  \nLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAK\r\
  \ncHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmEx\r\
  \nLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNp\r\
  \nemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2Fj\r\
  \nY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJ\r\
  \ndGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQA\r\
  \ntGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEps\r\
  \nY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxO\r\
  \nRE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpE\r\
  \nTmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AANCT1dzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4AFXEAfgAXdXEAfgAGAAAAA3EAfgAZcQB+ABpzcQB+AA4AAAEBc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAtNSUxLX0JVQ0tF\r\
  \nVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+\r\
  \nAA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBNc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AB1xAH4AHnEAfgAzcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4AInEAfgA4cQB+ACJzcQB+\r\
  \nAA4AAADMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHEAfgD+c3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4A\r\
  \nFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0AA5BUlJPV19J\r\
  \nTkZJTklURXQADEFSUk9XX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ACFxAH4AInEAfgA4\r\
  \nc3EAfgAOAAAAdnNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAJcQB+AApxAH4APHEAfgAL\r\
  \ndXEAfgAGAAAABXEAfgANc3EAfgAOAAAOdHQAD0ZJUkVXT1JLX1JPQ0tFVHNxAH4ADgAAADdzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQABXBvd2VydXEAfgAGAAAAA3EAfgAZdAAIRklS\r\
  \nRVdPUktxAH4AOHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGRUxZVFJBc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAACcQB+ADNx\r\
  \nAH4AH3VxAH4ABgAAAAJxAH4AOHEAfgAicQB+ACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX0JPT1RT\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAF\r\
  \ncQB+ABl0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAR0AA1ERVBUSF9TVFJJREVScQB+ADN0ABhQUk9U\r\
  \nRUNUSU9OX0VOVklST05NRU5UQUxxAH4AH3VxAH4ABgAAAARxAH4AInEAfgA4cQB+AF1xAH4AInNx\r\
  \nAH4ADgAAAA9zcQB+AA4AAAAgc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3NxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+\r\
  \nAVBzcQB+AAN1cQB+AAYAAAADcQB+ADNxAH4BVHEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AF1xAH4A\r\
  \nInNxAH4ADgAAAAdzcQB+AA4AAAAsc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAFE5FVEhFUklURV9DSEVTVFBMQVRFc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+\r\
  \nABlxAH4BUHNxAH4AA3VxAH4ABgAAAANxAH4AM3EAfgFUcQB+AB91cQB+AAYAAAADcQB+ADhxAH4A\r\
  \nXXEAfgAicQB+AWVzcQB+AA4AAAAfc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEE5FVEhFUklURV9IRUxNRVRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEA\r\
  \nfgFQc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+AVRxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgBdcQB+\r\
  \nACJxAH4BZXNxAH4ADgAAABxw\r\n"
xp: 1981.0
health: 24.847999572753906
hunger: 16
saturation: 0.0
location:
  world: world
  x: 9208.5
  y: 41.0
  z: 192.6
logType: WORLD_CHANGE
version: v1_20_R3
