inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVx\r\
  \nAH4ABgAAAAR0AAhJdGVtTWV0YXQABVNLVUxMdAAWeyJ0ZXh0IjoiwqdlQmFja3BhY2sifXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0\r\
  \nAA1QbGF5ZXJQcm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IA\r\
  \nE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2\r\
  \nYS51dGlsLkxpbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRp\r\
  \nbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcI\r\
  \nAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpU\r\
  \nUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBM\r\
  \nM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56\r\
  \nVTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNx\r\
  \nAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAA\r\
  \nDnR0AA1ORVRIRVJJVEVfSE9Fc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABV0AAhlbmNo\r\
  \nYW50c3QABkRhbWFnZXVxAH4ABgAAAARxAH4AGXQAClVOU1BFQ0lGSUNzcQB+AAN1cQB+AAYAAAAD\r\
  \ndAAJRElHX1NQRUVEdAARTE9PVF9CT05VU19CTE9DS1N0AApEVVJBQklMSVRZdXEAfgAGAAAAA3Nx\r\
  \nAH4ADgAAAAVzcQB+AA4AAAADcQB+AEFzcQB+AA4AAAEUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD05FVEhFUklURV9T\r\
  \nV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ADZ0AAtyZXBhaXItY29zdHVx\r\
  \nAH4ABgAAAARxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAABnQACUtOT0NLQkFDS3QAD0xPT1RfQk9O\r\
  \nVVNfTU9CU3QAB01FTkRJTkd0AA1EQU1BR0VfVU5ERUFEdAANU1dFRVBJTkdfRURHRXEAfgA+dXEA\r\
  \nfgAGAAAABnNxAH4ADgAAAAJxAH4AQXNxAH4ADgAAAAFxAH4AQHEAfgBBcQB+AEFxAH4AQXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZhbW91bnR1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAA4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4ATHEAfgA3dXEAfgAGAAAABXEAfgAZcQB+ADlzcQB+\r\
  \nAAN1cQB+AAYAAAADdAAOQVJST1dfSU5GSU5JVEV0AAxBUlJPV19EQU1BR0VxAH4APnVxAH4ABgAA\r\
  \nAANxAH4AV3EAfgBAcQB+AEFxAH4AV3NxAH4ADgAAAJpwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtFTkRFUl9Q\r\
  \nRUFSTHNxAH4ADgAAABBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AF5zcQB+AA4AAABAc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUdMQVNT\r\
  \nc3EAfgAOAAAAGnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AW3VxAH4A\r\
  \nBgAAAARxAH4ADXNxAH4ADgAADnR0AAVBUlJPV3NxAH4ADgAAADVzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQACFNQWUdMQVNTc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgBbdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQACklST05fSU5HT1RxAH4AQHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJ\r\
  \ncQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAHRlVSTkFDRXNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVD\r\
  \nS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNx\r\
  \nAH4ADgAADnRxAH4AonNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AEXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7\r\
  \nInRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRl\r\
  \ncmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9s\r\
  \nZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AH3EAfgAgdXEAfgAGAAAA\r\
  \nA3EAfgAidAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3EAfgAkAAAAAXcE\r\
  \nAAAAAXNxAH4AJj9AAAAAAAAMdwgAAAAQAAAAAnEAfgApdAAIdGV4dHVyZXNxAH4AK3QAtGV5SjBa\r\
  \nWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFX\r\
  \nNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1Rn\r\
  \nNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5\r\
  \nZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0ABFORVRIRVJJVEVfUElDS0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAAVxAH4ACHEAfgAVcQB+ADZxAH4ATHEAfgA3dXEAfgAGAAAABXEAfgAZcQB+ADlzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+ADxxAH4AUnQAClNJTEtfVE9VQ0hxAH4APnVxAH4ABgAAAARxAH4AQHEAfgBXcQB+\r\
  \nAFdxAH4AQXEAfgBBc3EAfgAOAAAA6HNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AW3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnRxAH4AXnNxAH4ADgAAAARzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAGRUxZVFJBc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4ANnEAfgBMcQB+ADd1\r\
  \ncQB+AAYAAAAFcQB+ABlxAH4AOXNxAH4AA3VxAH4ABgAAAAJxAH4AUnEAfgA+dXEAfgAGAAAAAnEA\r\
  \nfgBXcQB+AEFxAH4AQXNxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AFt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAANR09MREVOX0NBUlJPVHEAfgBWc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQADkRJQU1PTkRfU0hPVkVMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVx\r\
  \nAH4ANnVxAH4ABgAAAANxAH4AGXEAfgA5c3EAfgADdXEAfgAGAAAAA3EAfgA8cQB+AD1xAH4APnVx\r\
  \nAH4ABgAAAANxAH4Az3EAfgBBcQB+AEFzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AFtxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRx\r\
  \nAH4AfHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAVdAAFcG93ZXJ1cQB+AAYAAAADcQB+\r\
  \nABl0AAhGSVJFV09SS3EAfgBXc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgBbdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgDjcQB+AHxzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AFt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElBTU9O\r\
  \nRHEAfgBBcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQAB1RSSURFTlRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4AFXEAfgA2cQB+ADd1cQB+AAYAAAAEcQB+ABlxAH4AOXNyADdjb20uZ29vZ2xlLmNvbW1vbi5j\r\
  \nb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAAAAACAAB4cQB+AAN1cQB+\r\
  \nAAYAAAABdAAHTE9ZQUxUWXVxAH4ABgAAAAFxAH4AQXNxAH4ADgAAAMZwcHBwc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nD05FVEhFUklURV9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4A\r\
  \nTHEAfgA3dXEAfgAGAAAABXEAfgAZdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RS\r\
  \nSURFUnEAfgBSdAAYUFJPVEVDVElPTl9FTlZJUk9OTUVOVEFMcQB+AD51cQB+AAYAAAAEcQB+AEFx\r\
  \nAH4AV3EAfgDPcQB+AEFzcQB+AA4AAAAPcQB+AFdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJ\r\
  \nTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4ANnEAfgBMcQB+ADd1cQB+AAYA\r\
  \nAAAFcQB+ABlxAH4BInNxAH4AA3VxAH4ABgAAAANxAH4AUnEAfgEmcQB+AD51cQB+AAYAAAADcQB+\r\
  \nAFdxAH4Az3EAfgBBcQB+AN1xAH4AVnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABRORVRIRVJJVEVfQ0hFU1RQTEFURXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4ATHEAfgA3dXEAfgAGAAAABXEA\r\
  \nfgAZcQB+ASJzcQB+AAN1cQB+AAYAAAADcQB+AFJxAH4BJnEAfgA+dXEAfgAGAAAAA3EAfgBXcQB+\r\
  \nAM9xAH4AQXEAfgDdcQB+AFdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ADZxAH4ATHEAfgA3dXEAfgAGAAAABXEAfgAZcQB+ASJz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AFJxAH4BJnEAfgA+dXEAfgAGAAAAA3EAfgBXcQB+AM9xAH4AQXEA\r\
  \nfgDdc3EAfgAOAAAAEnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4AFXEAfgA3dAANYmxvY2tNYXRlcmlhbHVxAH4ABgAAAARxAH4AGXQAC1RJTEVfRU5USVRZ\r\
  \nc3EAfgAOAAAAW3EAfgFW\r\n"
xp: 1319.0
health: 26.0
hunger: 20
saturation: 12.400001
location:
  world: world_the_end
  x: 100.5
  y: 49.0
  z: 0.5
logType: WORLD_CHANGE
version: v1_20_R3
