inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtDT09L\r\
  \nRURfQkVFRnNxAH4ADgAAABBzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADxxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRzcQB+AA4A\r\
  \nAAAfc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4A\r\
  \nGXQACEZJUkVXT1JLcQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAa\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAdcQB+ADN0AApTSUxLX1RPVUNIcQB+AB91cQB+AAYAAAAEcQB+\r\
  \nACFxAH4AOHEAfgA4cQB+ACJxAH4AInNxAH4ADgAAAOVwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkJVQ0tFVHEAfgAi\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQABVRPUkNIc3EAfgAOAAAAKnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtGSVNISU5HX1JPRHNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARxAH4AGXEAfgAa\r\
  \nc3EAfgADdXEAfgAGAAAAA3QABExVQ0t0AARMVVJFcQB+AB91cQB+AAYAAAADcQB+ACJxAH4AInEA\r\
  \nfgAicQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50dAAERElSVHEAfgA3c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0VOREVSX1BFQVJMcQB+\r\
  \nAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50cQB+AGhzcQB+AA4AAAAcc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nAAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxCQUtFRF9QT1RBVE9zcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAFQVJST1dzcQB+AA4AAAAic3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAB09BS19MT0dzcQB+AA4AAAAVc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQAEVBSSVNNQVJJTkVfQlJJQ0tTcQB+AEdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AGhzcQB+AA4AAABAc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAFE5FVEhFUklURV9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+\r\
  \nABVxAH4AFnEAfgAtcQB+ABd1cQB+AAYAAAAFcQB+ABl0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAANx\r\
  \nAH4AM3QAGFBST1RFQ1RJT05fRU5WSVJPTk1FTlRBTHEAfgAfdXEAfgAGAAAAA3EAfgA4c3EAfgAO\r\
  \nAAAABHEAfgAic3EAfgAOAAAAB3NxAH4ADgAAACdzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQAB0ZVUk5BQ0VzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAJ\r\
  \nR1VOUE9XREVScQB+AEBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAG\r\
  \nAAAAA3EAfgANc3EAfgAOAAAOdHQABkNBUlJPVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAdQVU1QS0lOcQB+ADdzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAAKQ09PS0VEX0NPRHNxAH4ADgAAAAhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMUk9UVEVOX0ZMRVNIcQB+\r\
  \nALpzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EA\r\
  \nfgAOAAAOdHQACExJTFlfUEFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABUNIRVNUc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBXEAfgAIcQB+ABV0AAxkaXNwbGF5LW5hbWV0ABJQdWJsaWNCdWtraXRWYWx1ZXN0AA1ibG9ja01h\r\
  \ndGVyaWFsdXEAfgAGAAAABXEAfgAZdAALVElMRV9FTlRJVFl0ACF7InRleHQiOiIiLCJleHRyYSI6\r\
  \nWyJpdGVtc1BhY2siXX10ADp7CiAgICAiZmlzaHJld2FyZHM6ZXhhbXBsZWl0ZW1zcGFjayI6ICJF\r\
  \neGFtcGxlSXRlbXNQYWNrIgp9cQB+AO1wc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4A8XQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAZ\r\
  \ndAAFU0tVTEx0AJJ7InRleHQiOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNj\r\
  \nYXRlZCI6ZmFsc2UsIml0YWxpYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJv\r\
  \ndWdoIjpmYWxzZSwiY29sb3IiOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3Vx\r\
  \nAH4ABgAAAANxAH4ACHQACHVuaXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQ\r\
  \ncm9maWxldAAkZWQ1N2ViYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRp\r\
  \nbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxp\r\
  \nbmtlZEhhc2hNYXA0wE5cEGzA+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFw\r\
  \nBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0\r\
  \nAARuYW1ldAAIdGV4dHVyZXN0AAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJ\r\
  \nblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNt\r\
  \nVXZPR1JqWXpabFlqUXdaak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1R\r\
  \neE56VmpNbVUzTXpFeE9URmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHBwc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AA9GTElOVF9B\r\
  \nTkRfU1RFRUxzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYA\r\
  \nAAAEcQB+AA1zcQB+AA4AAA50cQB+AFNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEA\r\
  \nfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAARxAH4AHXEAfgAecQB+\r\
  \nADNxAH4AH3VxAH4ABgAAAARxAH4AIXEAfgAicQB+ADhxAH4AInNxAH4ADgAAAMxzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAADQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIcQB+ABVxAH4AFnEAfgAtcQB+ABd1cQB+\r\
  \nAAYAAAAFcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0AA5BUlJPV19JTkZJTklURXQADEFSUk9X\r\
  \nX0RBTUFHRXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ACFxAH4AInEAfgA4c3EAfgAOAAAAdnNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50\r\
  \ndAANQ09PS0VEX1JBQkJJVHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+\r\
  \nAAYAAAADcQB+AA1zcQB+AA4AAA50dAAFU1VHQVJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGQ09PS0lFcQB+ALtzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAAPTkVUSEVSSVRFX0JPT1RTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\r\
  \nAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ALVzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RS\r\
  \nSURFUnEAfgAzcQB+ALhxAH4AH3VxAH4ABgAAAARxAH4AInEAfgA4cQB+ALpxAH4AInNxAH4ADgAA\r\
  \nAA9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50dAASTkVUSEVSSVRFX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ALVzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nADNxAH4AuHEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ALpxAH4AInEAfgC7c3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVM\r\
  \nWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAG\r\
  \nAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAACcQB+ADNxAH4AH3VxAH4ABgAAAAJxAH4AOHEA\r\
  \nfgAicQB+ACJxAH4AIXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0ABBORVRIRVJJVEVfSEVMTUVUc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZcQB+ALVzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+ADNxAH4AuHEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+ALpxAH4AInEAfgC7c3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABdxAH4A83Vx\r\
  \nAH4ABgAAAARxAH4AGXEAfgD1c3EAfgAOAAAAW3EAfgGG\r\n"
xp: 1504.0
health: 26.0
hunger: 19
saturation: 0.0
location:
  world: world_nether
  x: 1635.1
  y: 48.0
  z: -4573.5
logType: WORLD_CHANGE
version: v1_20_R3
