inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAANTkVUSEVSSVRFX0hPRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHQACW1ldGEtdHlwZXQACGVuY2hhbnRzdAAGRGFtYWdldXEAfgAGAAAA\r\
  \nBHQACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4AA3VxAH4ABgAAAAN0AAlESUdfU1BFRUR0ABFM\r\
  \nT09UX0JPTlVTX0JMT0NLU3QACkRVUkFCSUxJVFl1cQB+AAYAAAADc3EAfgAOAAAABXNxAH4ADgAA\r\
  \nAANxAH4AInNxAH4ADgAAARRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX1NXT1JEc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnQAC3JlcGFpci1jb3N0dXEAfgAGAAAABHEAfgAZcQB+\r\
  \nABpzcQB+AAN1cQB+AAYAAAAGdAAJS05PQ0tCQUNLdAAPTE9PVF9CT05VU19NT0JTdAAHTUVORElO\r\
  \nR3QADURBTUFHRV9VTkRFQUR0AA1TV0VFUElOR19FREdFcQB+AB91cQB+AAYAAAAGc3EAfgAOAAAA\r\
  \nAnEAfgAic3EAfgAOAAAAAXEAfgAhcQB+ACJxAH4AInEAfgAic3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnQABmFtb3VudHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtDT09L\r\
  \nRURfQkVFRnNxAH4ADgAAAAxzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADxxAH4AC3VxAH4ABgAAAAVxAH4ADXNxAH4ADgAADnR0AA9GSVJFV09SS19ST0NLRVRzcQB+AA4A\r\
  \nAAAac3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAVwb3dlcnVxAH4ABgAAAANxAH4A\r\
  \nGXQACEZJUkVXT1JLcQB+ADhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nAAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAARTkVUSEVSSVRFX1BJQ0tBWEVzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEAfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgAa\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAdcQB+ADN0AApTSUxLX1RPVUNIcQB+AB91cQB+AAYAAAAEcQB+\r\
  \nACFxAH4AOHEAfgA4cQB+ACJxAH4AInNxAH4ADgAAAOhzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGQkFTQUxUc3EAfgAO\r\
  \nAAAABHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAZCVUNLRVRxAH4AInNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVUT1JDSHNxAH4ADgAAACpz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAALRklTSElOR19ST0RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEA\r\
  \nfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnNxAH4AA3VxAH4ABgAAAAN0AARMVUNLdAAETFVS\r\
  \nRXEAfgAfdXEAfgAGAAAAA3EAfgAicQB+ACJxAH4AInEAfgA4c3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABERJUlRxAH4A\r\
  \nN3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AAtFTkRFUl9QRUFSTHNxAH4ADgAAABBzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AG9zcQB+AA4A\r\
  \nAAAcc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNx\r\
  \nAH4ADgAADnR0AAxCQUtFRF9QT1RBVE9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVJST1dzcQB+AA4AAAAic3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAB09BS19MT0dzcQB+AA4AAAAVc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEVBSSVNNQVJJTkVfQlJJQ0tTc3EA\r\
  \nfgAOAAAAH3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4APHVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnRxAH4Ab3NxAH4ADgAAAEBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAaUE9MSVNIRURfQkxB\r\
  \nQ0tTVE9ORV9CUklDS1NzcQB+AA4AAAANc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx\r\
  \nAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAdGVVJOQUNFc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACUdVTlBP\r\
  \nV0RFUnEAfgCMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANx\r\
  \nAH4ADXNxAH4ADgAADnR0AAZDQVJST1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADx1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHUFVNUEtJTnEAfgA3c3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQACkNPT0tFRF9DT0RzcQB+AA4AAAAIc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADFJPVFRFTl9GTEVTSHEAfgBjc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAA\r\
  \nDnR0AAhMSUxZX1BBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVDSEVTVHNxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4A\r\
  \nCHEAfgAVdAAMZGlzcGxheS1uYW1ldAASUHVibGljQnVra2l0VmFsdWVzdAANYmxvY2tNYXRlcmlh\r\
  \nbHVxAH4ABgAAAAVxAH4AGXQAC1RJTEVfRU5USVRZdAAheyJ0ZXh0IjoiIiwiZXh0cmEiOlsiaXRl\r\
  \nbXNQYWNrIl19dAA6ewogICAgImZpc2hyZXdhcmRzOmV4YW1wbGVpdGVtc3BhY2siOiAiRXhhbXBs\r\
  \nZUl0ZW1zUGFjayIKfXEAfgDrc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABkVMWVRSQXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAAVxAH4ACHEAfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+\r\
  \nAAYAAAACcQB+ADNxAH4AH3VxAH4ABgAAAAJxAH4AOHEAfgAicQB+ACJxAH4A2XNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+AO90AAtza3Vs\r\
  \nbC1vd25lcnVxAH4ABgAAAARxAH4AGXQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRl\r\
  \neHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxp\r\
  \nbmVkIjpmYWxzZSwic3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6\r\
  \nZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRp\r\
  \nZXN1cQB+AAYAAAADdAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFl\r\
  \nNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAAB\r\
  \ndwQAAAABc3IAF2phdmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRl\r\
  \ncnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9s\r\
  \nZHhwP0AAAAAAAAx3CAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlho\r\
  \nMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVs\r\
  \nWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRP\r\
  \nR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZY\r\
  \nMD14AHhwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+\r\
  \nAA1zcQB+AA4AAA50dAAPRkxJTlRfQU5EX1NURUVMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgBTc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABpzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AB1xAH4AHnEAfgAzcQB+AB91cQB+AAYAAAAEcQB+ACFxAH4AInEAfgA4cQB+\r\
  \nACJzcQB+AA4AAADMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEA\r\
  \nfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+ABpzcQB+AAN1cQB+AAYAAAADdAAO\r\
  \nQVJST1dfSU5GSU5JVEV0AAxBUlJPV19EQU1BR0VxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgAhcQB+\r\
  \nACJxAH4AOHNxAH4ADgAAAHZzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEA\r\
  \nfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQADUNPT0tFRF9SQUJCSVRzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQABVNVR0FSc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA8dXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQABkNPT0tJRXNxAH4ADgAAAAdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPTkVUSEVSSVRFX0JPT1RTc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAtdXEAfgAGAAAABHEAfgAZdAAFQVJN\r\
  \nT1JzcQB+AAN1cQB+AAYAAAAEdAANREVQVEhfU1RSSURFUnEAfgAzdAAYUFJPVEVDVElPTl9FTlZJ\r\
  \nUk9OTUVOVEFMcQB+AB91cQB+AAYAAAAEcQB+ACJxAH4AOHEAfgBjcQB+ACJzcQB+AA4AAAAPc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQAEk5FVEhFUklURV9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEA\r\
  \nfgAVcQB+ABZxAH4ALXEAfgAXdXEAfgAGAAAABXEAfgAZcQB+AWFzcQB+AAN1cQB+AAYAAAADcQB+\r\
  \nADNxAH4BZXEAfgAfdXEAfgAGAAAAA3EAfgA4cQB+AGNxAH4AInEAfgFWcQB+ACJzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAUTkVUSEVSSVRFX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAFcQB+AAhxAH4AFXEA\r\
  \nfgAWcQB+AC1xAH4AF3VxAH4ABgAAAAVxAH4AGXEAfgFhc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+\r\
  \nAWVxAH4AH3VxAH4ABgAAAANxAH4AOHEAfgBjcQB+ACJxAH4BVnNxAH4ADgAAACRzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAQTkVUSEVSSVRFX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\r\
  \nAH4ALXVxAH4ABgAAAARxAH4AGXEAfgFhc3EAfgADdXEAfgAGAAAAA3EAfgAzcQB+AWVxAH4AH3Vx\r\
  \nAH4ABgAAAANxAH4AOHEAfgBjcQB+ACJxAH4BVnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTSElFTERzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAXcQB+APF1cQB+AAYAAAAEcQB+ABlxAH4A83NxAH4A\r\
  \nDgAAAFtxAH4BlQ==\r\n"
xp: 1509.0
health: 26.0
hunger: 17
saturation: 0.0
location:
  world: world
  x: 11418.6
  y: 65.0
  z: 207.1
logType: WORLD_CHANGE
version: v1_20_R3
