stats:
  ==: us.teaminceptus.novaconomy.api.player.PlayerStatistics
  player: 89b27bf7-0028-4579-954f-2c26d4632092
  highest_balance: 50.0
  products_purchased: 0
  money_added: 50.0
  total_withdrawn: 0.0
  total_bounties_created: 0
  total_bounties_had: 0
  transaction_history: []
  total_shares_purchased: 0
  total_money_spent: 0.0
  highest_balance_economy: e07e81c2-0cf5-335f-9225-765f0af81755
won_auctions: !!set {}
economies:
  gold:
    balance: 50.0
