inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAAiHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtc3EAfgAOAAAABXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AAp0AAZh\r\
  \nbW91bnR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMUk9UVEVOX0ZMRVNIcQB+ADBzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nCE9BS19CT0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQACk9BS19QTEFOS1NzcQB+AA4AAAAXc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACE9B\r\
  \nS19ET09ScQB+AC5zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA\r\
  \nA3EAfgANc3EAfgAOAAAOdHQAEFBIQU5UT01fTUVNQlJBTkVzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAQUFJJU01BUklO\r\
  \nRV9TSEFSRHNxAH4ADgAAAAZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+\r\
  \nADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElBTU9ORHEAfgAtc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACkdM\r\
  \nQVNTX1BBTkVxAH4AV3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEcQB+ABh0\r\
  \nAAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2Nh\r\
  \ndGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91\r\
  \nZ2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclBy\r\
  \nb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGls\r\
  \nLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlu\r\
  \na2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAF\r\
  \nB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQA\r\
  \nBG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0lu\r\
  \nVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21V\r\
  \ndk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4\r\
  \nTnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABEJFRUZz\r\
  \ncQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQADEJBS0VEX1BPVEFUT3NxAH4ADgAAACVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAG\r\
  \nUE9USU9Oc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABV0AAtwb3Rpb24tdHlwZXVxAH4A\r\
  \nBgAAAANxAH4AGHEAfgCWdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEA\r\
  \nfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AmnVxAH4ABgAAAANxAH4AGHEA\r\
  \nfgCWdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCWc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AmnVxAH4ABgAAAANxAH4AGHEAfgCWdAAbbWluZWNy\r\
  \nYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgA0dXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NDQUZGT0xESU5Hc3EAfgAOAAAAGnNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4A\r\
  \nAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EA\r\
  \nfgAIcQB+ABVxAH4AmnVxAH4ABgAAAANxAH4AGHEAfgCWdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJf\r\
  \nYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHEAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVx\r\
  \nAH4AmnVxAH4ABgAAAANxAH4AGHEAfgCWdAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5n\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AmnVxAH4A\r\
  \nBgAAAANxAH4AGHEAfgCWdAAPbWluZWNyYWZ0OndhdGVyc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NUT05FX1NXT1JE\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAAAANxAH4AGHEAfgAZ\r\
  \ncQB+AC5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50dAADQ09EcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAATUFJJU01BUklORV9DUllTVEFM\r\
  \nU3EAfgAuc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgA0dXEAfgAGAAAA\r\
  \nBHEAfgANc3EAfgAOAAAOdHQAEVBSSVNNQVJJTkVfQlJJQ0tTcQB+ADBzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALU0VB\r\
  \nX0xBTlRFUk5xAH4ALnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ANHVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtDT09LRURfQkVFRnNxAH4ADgAAAARzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAPQ09PS0VEX1BPUktDSE9QcQB+AQRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEA\r\
  \nfgAKcQB+ADR1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAFQVBQTEVzcQB+AA4AAAAIcHBwcHBw\r\
  \ncHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AApJUk9OX0JPT1RTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\r\
  \nAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAACdAAYUFJPVEVD\r\
  \nVElPTl9FTlZJUk9OTUVOVEFMcQB+ACt1cQB+AAYAAAACcQB+AQRxAH4ALXNxAH4ADgAAAFtzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+\r\
  \nAA4AAA50dAANSVJPTl9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+\r\
  \nACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgEcc3IAN2NvbS5nb29nbGUuY29tbW9uLmNvbGxlY3Qu\r\
  \nSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAFx\r\
  \nAH4AK3VxAH4ABgAAAAFxAH4ALXNxAH4ADgAAAF9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPSVJPTl9DSEVTVFBMQVRF\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAY\r\
  \ncQB+ARxzcQB+AAN1cQB+AAYAAAACcQB+AR9xAH4AK3VxAH4ABgAAAAJxAH4BBHEAfgAtc3EAfgAO\r\
  \nAAAAYHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtJUk9OX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgEcc3EAfgEsdXEAfgAGAAAAAXEAfgEfdXEA\r\
  \nfgAGAAAAAXEAfgEEc3EAfgAOAAAAiXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxE\r\n"
xp: 640.0
health: 20.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 9213.6
  y: 48.0
  z: 193.5
logType: JOIN
version: v1_20_R3
