inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBXQAAj09dAABdnQABHR5cGV0AAZhbW91bnR0AARtZXRhdXEAfgAGAAAABXQAHm9yZy5idWtraXQu\r\
  \naW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFs\r\
  \ndWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALUExBWUVSX0hFQURzcQB+\r\
  \nAA8AAAAHc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAknsidGV4dCI6\r\
  \nIiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGlj\r\
  \nIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6\r\
  \nInllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5p\r\
  \ncXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03\r\
  \nMDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2Gd\r\
  \nAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7\r\
  \nAgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRG\r\
  \nYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QA\r\
  \nBXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkw\r\
  \nWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZ\r\
  \nV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05X\r\
  \nRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4A\r\
  \nCnVxAH4ABgAAAANxAH4ADnNxAH4ADwAADnR0AAhPQUtfRE9PUnNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAGU0FERExFc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAP\r\
  \nAAAOdHQADFJPVFRFTl9GTEVTSHNxAH4ADwAAAApzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAALRElBTU9ORF9BWEVzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AF3QABkRhbWFnZXVxAH4ABgAAAANxAH4AG3QAClVO\r\
  \nU1BFQ0lGSUNzcQB+AA8AAAH7cHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAhDUk9TU0JPV3NxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAAZxAH4ACHEAfgAXdAAIZW5jaGFudHNxAH4AS3QAB2NoYXJnZWR0ABNjaGFyZ2VkLXByb2pl\r\
  \nY3RpbGVzdXEAfgAGAAAABnEAfgAbcQB+AFRzcQB+AAN1cQB+AAYAAAACdAAIUElFUkNJTkd0AApE\r\
  \nVVJBQklMSVRZdXEAfgAGAAAAAnNxAH4ADwAAAAFxAH4AYXNxAH4ADwAAAbVzcgARamF2YS5sYW5n\r\
  \nLkJvb2xlYW7NIHKA1Zz67gIAAVoABXZhbHVleHABc3EAfgAmAAAAAXcEAAAAAXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAAFQVJS\r\
  \nT1d4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEA\r\
  \nfgAOc3EAfgAPAAAOdHQADVNXRUVUX0JFUlJJRVNzcQB+AA8AAAAGc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAOdHQACUlST05f\r\
  \nRE9PUnEAfgATc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANx\r\
  \nAH4ADnNxAH4ADwAADnR0AAxXQVRFUl9CVUNLRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAERElSVHNxAH4ADwAAAAJz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5z\r\
  \ncQB+AA8AAA50dAAPRElBTU9ORF9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nABdxAH4AWHEAfgBLdXEAfgAGAAAABHEAfgAbcQB+AE1zcQB+AAN1cQB+AAYAAAAEdAAJRElHX1NQ\r\
  \nRUVEdAARTE9PVF9CT05VU19CTE9DS1N0AAdNRU5ESU5HcQB+AF91cQB+AAYAAAAEc3EAfgAPAAAA\r\
  \nA3EAfgCFcQB+AGFxAH4AlnEAfgCFcHNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50dAALRklSRV9DSEFSR0VzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50cQB+ABJz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AF3EAfgAYcQB+ABl1cQB+AAYAAAAEcQB+ABtx\r\
  \nAH4AHHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVk\r\
  \nIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2gi\r\
  \nOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+ACFxAH4AInVxAH4ABgAAAANxAH4AJHQAJGVkNTdlYmM1LTcwNGUtM2JhMS04\r\
  \nZTFhLTFlNzc0ZDg4NDUzM3NxAH4AJgAAAAF3BAAAAAFzcQB+ACg/QAAAAAAADHcIAAAAEAAAAAJx\r\
  \nAH4AK3QACHRleHR1cmVzcQB+AC10ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5WeWJD\r\
  \nSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2T0dS\r\
  \nall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhOelZq\r\
  \nTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFQlJFQURxAH4A\r\
  \nhXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDnNxAH4ADwAADnR0AApHTEFTU19QQU5FcQB+AHJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\r\
  \nAH4ACXEAfgAKcQB+AAx1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAANTkVUSEVSSVRFX0FYRXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAAVxAH4ACHEAfgAXcQB+AFh0AAtyZXBhaXItY29zdHEAfgBLdXEA\r\
  \nfgAGAAAABXEAfgAbcQB+AE1zcQB+AAN1cQB+AAYAAAADcQB+AJJ0AApTSUxLX1RPVUNIcQB+AF91\r\
  \ncQB+AAYAAAADc3EAfgAPAAAABXEAfgBhcQB+AJZxAH4AlnNxAH4ADwAAAIRzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAE\r\
  \nQkVFRnNxAH4ADwAAABJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAALU0VBX0xBTlRFUk5zcQB+AA8AAABAc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAOc3EAfgAPAAAO\r\
  \ndHQABVRPUkNIc3EAfgAPAAAAOHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AApPQUtfUExBTktTc3EAfgAPAAAAC3NxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50\r\
  \ndAAIT0FLX0JPQVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFU1RJQ0txAH4AhXNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnRxAH4A2XNxAH4ADwAA\r\
  \nABZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA5zcQB+AA8AAA50dAAGQ0FSUk9UcQB+ANpzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5zcQB+AA8AAA50dAAHRU1FUkFMRHNxAH4ADwAAAARz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5z\r\
  \ncQB+AA8AAA50cQB+AQBxAH4A2nNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AARDT0FMc3EAfgAPAAAAEHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA5zcQB+AA8AAA50cQB+AH5z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA5z\r\
  \ncQB+AA8AAA50dAALT0FLX1NBUExJTkdxAH4AhXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAdPQUtfTE9Hc3EAfgAPAAAA\r\
  \nFXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDnNxAH4ADwAADnR0AAxHTEFTU19CT1RUTEVxAH4AhXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnRxAH4AVHNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAXcQB+AEtxAH4AWXVxAH4ABgAAAARxAH4AG3EAfgBUc3EAfgAP\r\
  \nAAABdHNxAH4AYwBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA5zcQB+AA8AAA50dAAFU1VHQVJxAH4AhXNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA5TUFJVQ0VfU0FQ\r\
  \nTElOR3EAfgCWc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAMdXEAfgAG\r\
  \nAAAABHEAfgAOc3EAfgAPAAAOdHQACklST05fQk9PVFNzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4AF3EAfgBYcQB+AEt1cQB+AAYAAAAEcQB+ABt0AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAJ0\r\
  \nABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AX3VxAH4ABgAAAAJxAH4BB3EAfgCWc3EAfgAP\r\
  \nAAAAr3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARx\r\
  \nAH4ADnNxAH4ADwAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+ABdxAH4AWHEAfgBLdXEAfgAGAAAABHEAfgAbcQB+AU1zcgA3Y29tLmdvb2dsZS5jb21tb24u\r\
  \nY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgADdXEA\r\
  \nfgAGAAAAAXEAfgBfdXEAfgAGAAAAAXEAfgCWc3EAfgAPAAAAqXNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AApxAH4ADHVxAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AA9JUk9OX0NI\r\
  \nRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AF3EAfgBYcQB+AEt1cQB+AAYA\r\
  \nAAAEcQB+ABtxAH4BTXNxAH4AA3VxAH4ABgAAAAJxAH4BUHEAfgBfdXEAfgAGAAAAAnEAfgEHcQB+\r\
  \nAJZzcQB+AA8AAAC1cHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4ADHVx\r\
  \nAH4ABgAAAARxAH4ADnNxAH4ADwAADnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4AF3EAfgBLdAANYmxvY2tNYXRlcmlhbHVxAH4ABgAAAARxAH4AG3QAC1RJTEVfRU5USVRZ\r\
  \nc3EAfgAPAAAAMXEAfgF1\r\n"
xp: 1039.0
health: 24.0
hunger: 20
saturation: 0.0
location:
  world: world
  x: 11413.8
  y: 65.0
  z: 207.5
logType: JOIN
version: v1_20_R3
