inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAANHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADFJPVFRFTl9GTEVTSHNxAH4ADgAAACFzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nCE9BS19CT0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQABEJFRUZzcQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACE9BS19ET09S\r\
  \ncQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAN\r\
  \nc3EAfgAOAAAOdHQAEFBIQU5UT01fTUVNQlJBTkVwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAB0RJQU1PTkRxAH4ALXNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AM3VxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AApHTEFTU19QQU5Fc3EAfgAOAAAABnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3du\r\
  \nZXJ1cQB+AAYAAAAEcQB+ABh0AAVTS1VMTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0Ijoi\r\
  \nQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6\r\
  \nZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNl\r\
  \nfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEA\r\
  \nfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4\r\
  \nODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAA\r\
  \nAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgAR\r\
  \namF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9A\r\
  \nAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEps\r\
  \nY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmha\r\
  \nblF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpE\r\
  \nSXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHQACk9BS19QTEFOS1NzcQB+AA4AAAAZc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADEJBS0VEX1BPVEFU\r\
  \nT3NxAH4ADgAAACVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAGUE9USU9Oc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAI\r\
  \ncQB+ABV0AAtwb3Rpb24tdHlwZXVxAH4ABgAAAANxAH4AGHEAfgCQdAAbbWluZWNyYWZ0Omxvbmdf\r\
  \nbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCQc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+\r\
  \nABVxAH4AlHVxAH4ABgAAAANxAH4AGHEAfgCQdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9u\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgAN\r\
  \nc3EAfgAOAAAOdHEAfgCQc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AlHVxAH4A\r\
  \nBgAAAANxAH4AGHEAfgCQdAAbbWluZWNyYWZ0OmxvbmdfbmlnaHRfdmlzaW9uc3EAfgAAc3EAfgAD\r\
  \ndXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQA\r\
  \nC1NDQUZGT0xESU5Hc3EAfgAOAAAAGnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAMV0FURVJfQlVDS0VUc3EAfgAAc3EAfgADdXEA\r\
  \nfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCQ\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AlHVxAH4ABgAAAANxAH4AGHEAfgCQ\r\
  \ndAAebWluZWNyYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCQc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAAA3EAfgAIcQB+ABVxAH4AlHVxAH4ABgAAAANxAH4AGHEAfgCQdAAebWluZWNy\r\
  \nYWZ0Omxvbmdfd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHEAfgCQc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+ABVxAH4AlHVxAH4ABgAAAANxAH4AGHEAfgCQdAAebWluZWNyYWZ0Omxvbmdf\r\
  \nd2F0ZXJfYnJlYXRoaW5nc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAL\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1NUT05FX1NXT1JEc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+ABVxAH4AFnVxAH4ABgAAAANxAH4AGHEAfgAZcQB+AC5wcHBwcHBwcHBwcHBw\r\
  \ncHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AApJUk9OX0JPT1RTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\r\
  \nAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYdAAFQVJNT1JzcQB+AAN1cQB+AAYAAAACdAAYUFJPVEVD\r\
  \nVElPTl9FTlZJUk9OTUVOVEFMcQB+ACt1cQB+AAYAAAACc3EAfgAOAAAABHEAfgAtc3EAfgAOAAAA\r\
  \nSHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\r\
  \nDXNxAH4ADgAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nABVxAH4AJHEAfgAWdXEAfgAGAAAABHEAfgAYcQB+AOpzcgA3Y29tLmdvb2dsZS5jb21tb24uY29s\r\
  \nbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAAeHEAfgADdXEAfgAG\r\
  \nAAAAAXEAfgArdXEAfgAGAAAAAXEAfgAtc3EAfgAOAAAAUHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9JUk9OX0NIRVNU\r\
  \nUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAE\r\
  \ncQB+ABhxAH4A6nNxAH4AA3VxAH4ABgAAAAJxAH4A7XEAfgArdXEAfgAGAAAAAnEAfgDvcQB+AC1x\r\
  \nAH4A/3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtJUk9OX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAVcQB+ACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgDqc3EAfgD7dXEAfgAGAAAAAXEAfgDtdXEA\r\
  \nfgAGAAAAAXEAfgDvc3EAfgAOAAAAcnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+\r\
  \nAAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxE\r\n"
xp: 524.0
health: 18.797067642211914
hunger: 20
saturation: 0.0
location:
  world: world
  x: 9281.6
  y: 62.7
  z: 204.3
logType: JOIN
version: v1_20_R3
