inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AARtZXRhdXEAfgAGAAAABHQAHm9yZy5idWtraXQuaW52ZW50b3J5\r\
  \nLkl0ZW1TdGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2\r\
  \nYS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAA50dAALRElBTU9ORF9BWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAANHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXQACGVuY2hhbnRzcQB+ABZ1cQB+AAYAAAAEcQB+ABhx\r\
  \nAH4AGXNxAH4AA3VxAH4ABgAAAAR0AAlESUdfU1BFRUR0ABFMT09UX0JPTlVTX0JMT0NLU3QAB01F\r\
  \nTkRJTkd0AApEVVJBQklMSVRZdXEAfgAGAAAABHNxAH4ADgAAAANzcQB+AA4AAAACc3EAfgAOAAAA\r\
  \nAXEAfgAtcQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAGYW1vdW50\r\
  \ndXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADFJPVFRFTl9GTEVTSHNxAH4ADgAAACpzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQA\r\
  \nCE9BS19CT0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAG\r\
  \nAAAABHEAfgANc3EAfgAOAAAOdHQABEJFRUZzcQB+AA4AAAASc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACE9BS19ET09S\r\
  \ncQB+AC1zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAN\r\
  \nc3EAfgAOAAAOdHQAEFBIQU5UT01fTUVNQlJBTkVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx\r\
  \nAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQACkJJUkNIX0JPQVRwc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgAzdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQACkdMQVNTX1BBTkVzcQB+AA4AAAAGc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlx\r\
  \nAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+ABV0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVxAH4A\r\
  \nBgAAAARxAH4AGHQABVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFj\r\
  \nayIsIm9iZnVzY2F0ZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwi\r\
  \nc3RyaWtldGhyb3VnaCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1cQB+AAYAAAAD\r\
  \ndAANUGxheWVyUHJvZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3Ny\r\
  \nABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3IAF2ph\r\
  \ndmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0\r\
  \naWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3\r\
  \nCAAAABAAAAACdAAEbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRYSmxjeUk2ZXlK\r\
  \nVFMwbE9JanA3SW5WeWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYw\r\
  \nTDNSbGVIUjFjbVV2T0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpO\r\
  \nelU1T0dKa1ltUXhOelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ADN1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50dAAKT0FLX1BMQU5LU3NxAH4ADgAAABlzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+ADN1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMQkFLRURfUE9UQVRPc3EAfgAO\r\
  \nAAAAJXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAZQT1RJT05zcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXQA\r\
  \nC3BvdGlvbi10eXBldXEAfgAGAAAAA3EAfgAYcQB+AJB0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92\r\
  \naXNpb25zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\r\
  \ncQB+AA1zcQB+AA4AAA50cQB+AJBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCU\r\
  \ndXEAfgAGAAAAA3EAfgAYcQB+AJB0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25zcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AJBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCUdXEAfgAGAAAAA3EA\r\
  \nfgAYcQB+AJB0ABttaW5lY3JhZnQ6bG9uZ19uaWdodF92aXNpb25wc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0AAxXQVRFUl9CVUNL\r\
  \nRVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+\r\
  \nAA1zcQB+AA4AAA50cQB+AJBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCUdXEA\r\
  \nfgAGAAAAA3EAfgAYcQB+AJB0AB5taW5lY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhpbmdzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4A\r\
  \nAA50cQB+AJBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCUdXEAfgAGAAAAA3EA\r\
  \nfgAYcQB+AJB0AB5taW5lY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhpbmdzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50cQB+AJBz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgCUdXEAfgAGAAAAA3EAfgAYcQB+AJB0\r\
  \nAB5taW5lY3JhZnQ6bG9uZ193YXRlcl9icmVhdGhpbmdzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+\r\
  \nAAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALU1RPTkVfU1dPUkRz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AFXEAfgAWdXEAfgAGAAAAA3EAfgAYcQB+ABlx\r\
  \nAH4ALnBwcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACklST05fQk9PVFNzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABh0AAVBUk1PUnNxAH4AA3Vx\r\
  \nAH4ABgAAAAJ0ABhQUk9URUNUSU9OX0VOVklST05NRU5UQUxxAH4AK3VxAH4ABgAAAAJzcQB+AA4A\r\
  \nAAAEcQB+AC1zcQB+AA4AAABHc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEA\r\
  \nfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQADUlST05fTEVHR0lOR1NzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABhxAH4A43NyADdjb20u\r\
  \nZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUJpTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAA\r\
  \nAAACAAB4cQB+AAN1cQB+AAYAAAABcQB+ACt1cQB+AAYAAAABcQB+AC1zcQB+AA4AAABQc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAO\r\
  \nAAAOdHQAD0lST05fQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+\r\
  \nACRxAH4AFnVxAH4ABgAAAARxAH4AGHEAfgDjc3EAfgADdXEAfgAGAAAAAnEAfgDmcQB+ACt1cQB+\r\
  \nAAYAAAACcQB+AOhxAH4ALXNxAH4ADgAAAE9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALSVJPTl9IRUxNRVRzcQB+AABz\r\
  \ncQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAkcQB+ABZ1cQB+AAYAAAAEcQB+ABhxAH4A43Nx\r\
  \nAH4A9HVxAH4ABgAAAAFxAH4A5nVxAH4ABgAAAAFxAH4A6HNxAH4ADgAAAHFzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAOAAAOdHQABlNISUVM\r\
  \nRA==\r\n"
xp: 524.0
health: 1.621335744857788
hunger: 20
saturation: 0.0
location:
  world: world
  x: 9297.3
  y: 61.0
  z: 187.2
logType: JOIN
version: v1_20_R3
