inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRv\r\
  \ncnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBq\r\
  \nYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAZCQU1CT09zcQB+AA4AAAAMc3EAfgAA\r\
  \nc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADXNxAH4ADgAADnR0\r\
  \nAAtESUFNT05EX0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYA\r\
  \nAAADcQB+AA1zcQB+AA4AAA50dAAKSVJPTl9JTkdPVHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAA\r\
  \nAARxAH4ACHEAfgAJcQB+AAp0AARtZXRhdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1BMQVlF\r\
  \nUl9IRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIdAAJbWV0YS10eXBldAAMZGlzcGxheS1u\r\
  \nYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEdAAISXRlbU1ldGF0AAVTS1VMTHQAknsidGV4dCI6\r\
  \nIiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpmYWxzZSwiaXRhbGlj\r\
  \nIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZhbHNlLCJjb2xvciI6\r\
  \nInllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5p\r\
  \ncXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03\r\
  \nMDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2Gd\r\
  \nAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7\r\
  \nAgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRG\r\
  \nYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QA\r\
  \nBXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkw\r\
  \nWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZ\r\
  \nV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05X\r\
  \nRTVZVFF5WkROak9DSjlmWDA9eAB4cHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBzcQB+AABzcQB+\r\
  \nAAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ACJ1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50\r\
  \ndAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgApdAAIZW5jaGFudHN0\r\
  \nAAZEYW1hZ2V1cQB+AAYAAAAEcQB+AC10AAVBUk1PUnNxAH4AA3VxAH4ABgAAAAJ0ABhQUk9URUNU\r\
  \nSU9OX0VOVklST05NRU5UQUx0AApEVVJBQklMSVRZdXEAfgAGAAAAAnNxAH4ADgAAAARzcQB+AA4A\r\
  \nAAADc3EAfgAOAAAAMnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AInVx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA1JUk9OX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAG\r\
  \nAAAABHEAfgAIcQB+AClxAH4ASnEAfgBLdXEAfgAGAAAABHEAfgAtcQB+AE1zcgA3Y29tLmdvb2ds\r\
  \nZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxpemVkRm9ybQAAAAAAAAAAAgAA\r\
  \neHEAfgADdXEAfgAGAAAAAXEAfgBRdXEAfgAGAAAAAXEAfgBUc3EAfgAOAAAAOXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AInVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAA9JUk9OX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AKXEAfgBKcQB+\r\
  \nAEt1cQB+AAYAAAAEcQB+AC1xAH4ATXNxAH4AA3VxAH4ABgAAAAJxAH4AUHEAfgBRdXEAfgAGAAAA\r\
  \nAnEAfgBTcQB+AFRxAH4AZHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nInVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtJUk9OX0hFTE1FVHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgApcQB+AEpxAH4AS3VxAH4ABgAAAARxAH4ALXEAfgBNc3EAfgBgdXEAfgAG\r\
  \nAAAAAXEAfgBQdXEAfgAGAAAAAXEAfgBTc3EAfgAOAAAAT3NxAH4AAHNxAH4AA3VxAH4ABgAAAANx\r\
  \nAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AA1zcQB+AA4AAA50dAAGU0hJRUxE\r\n"
xp: 477.0
health: 20.0
hunger: 20
saturation: 2.6000001
location:
  world: world
  x: 11415.9
  y: 64.0
  z: 208.4
logType: JOIN
version: v1_20_R3
