Lesser Boundary Corner: world;11414;60;199
Greater Boundary Corner: world;11422;65;207
Owner: a9e84f2a-b34b-400f-b455-155f6a0231bf
Builders:
- a9e84f2a-b34b-400f-b455-155f6a0231bf
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false
