Lesser Boundary Corner: world;866;58;665
Greater Boundary Corner: world;874;63;673
Owner: 467920a1-80a9-465c-966c-5cbca4a84831
Builders: []
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false
