Lesser Boundary Corner: world;11976;71;196
Greater Boundary Corner: world;11984;76;204
Owner: 89b27bf7-0028-4579-954f-2c26d4632092
Builders: []
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false
