Lesser Boundary Corner: world;11433;-51;236
Greater Boundary Corner: world;11443;112;246
Owner: 6f0db270-ed9c-4b12-8689-f9f79958ca18
Builders: []
Containers: []
Accessors: []
Managers: []
Parent Claim ID: -1
inheritNothing: false
