inventory: "rO0ABXcEAAAAKXBwcHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAAD\r\
  \nbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11\r\
  \ndGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09i\r\
  \namVjdDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhw\r\
  \nAAAABHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZl\r\
  \nbnRvcnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhy\r\
  \nABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAVUT1JDSHNxAH4ADgAAAAxzcQB+\r\
  \nAABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAEbWV0YXVxAH4ABgAAAARxAH4ADXNx\r\
  \nAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAh0AAlt\r\
  \nZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0AApVTlNQRUNJRklDc3EAfgAO\r\
  \nAAAAMnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AFnVxAH4ABgAAAARx\r\
  \nAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0FYRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEA\r\
  \nfgAdcQB+AB51cQB+AAYAAAADcQB+ACBxAH4AIXNxAH4ADgAAAD1zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+ABZ1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALUExBWUVS\r\
  \nX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AHXQADGRpc3BsYXktbmFtZXQAC3Nr\r\
  \ndWxsLW93bmVydXEAfgAGAAAABHEAfgAgdAAFU0tVTEx0ABZ7InRleHQiOiLCp2VCYWNrcGFjayJ9\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAG\r\
  \nAAAAA3QADVBsYXllclByb2ZpbGV0ACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1\r\
  \nMzNzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNy\r\
  \nABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2\r\
  \nYS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAA\r\
  \nAAAMdwgAAAAQAAAAAnQABG5hbWV0AAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJ\r\
  \nNmV5SlRTMGxPSWpwN0luVnliQ0k2SW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1\r\
  \nYm1WMEwzUmxlSFIxY21Vdk9HUmpZelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdO\r\
  \nelF6TnpVNU9HSmtZbVF4TnpWak1tVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\r\
  \nfgAOAAAOdHQACFBPUktDSE9Qc3EAfgAOAAAACnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEA\r\
  \nfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtDT09LRURfQkVFRnNxAH4A\r\
  \nDgAAABRwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+AAlxAH4ACnEAfgAWdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNx\r\
  \nAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAdcQB+AB50AA1ibG9ja01hdGVyaWFsdXEAfgAG\r\
  \nAAAABHEAfgAgdAALVElMRV9FTlRJVFlzcQB+AA4AAACScQB+AGA=\r\n"
xp: 141.0
health: 17.330886840820312
hunger: 17
saturation: 0.0
location:
  world: world
  x: 709.3
  y: 37.0
  z: 686.4
logType: QUIT
version: v1_20_R3
