inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRv\r\
  \ncnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBq\r\
  \nYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAtDT0JCTEVTVE9ORXNxAH4ADgAAACFz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgANc3EAfgAO\r\
  \nAAAOdHQABkdSQVZFTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3Vx\r\
  \nAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAxMQVBJU19MQVpVTElzcQB+AA4AAAAEc3EAfgAAc3EA\r\
  \nfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAO\r\
  \ndHQABUFSUk9XcQB+AB9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKdAAEbWV0\r\
  \nYXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AA9ESUFNT05EX1BJQ0tBWEVzcQB+AABzcQB+AAN1\r\
  \ncQB+AAYAAAADcQB+AAh0AAltZXRhLXR5cGV0AAZEYW1hZ2V1cQB+AAYAAAADdAAISXRlbU1ldGF0\r\
  \nAApVTlNQRUNJRklDc3EAfgAOAAAAvXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAApxAH4AKXVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAtESUFNT05EX0FYRXNxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAANxAH4ACHEAfgAwcQB+ADF1cQB+AAYAAAADcQB+ADNxAH4ANHNxAH4ADgAAAHZz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+ACl1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAALUExBWUVSX0hFQURzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AMHQA\r\
  \nDGRpc3BsYXktbmFtZXQAC3NrdWxsLW93bmVydXEAfgAGAAAABHEAfgAzdAAFU0tVTEx0AJJ7InRl\r\
  \neHQiOiIiLCJleHRyYSI6W3sidGV4dCI6IkJhY2twYWNrIiwib2JmdXNjYXRlZCI6ZmFsc2UsIml0\r\
  \nYWxpYyI6ZmFsc2UsInVuZGVybGluZWQiOmZhbHNlLCJzdHJpa2V0aHJvdWdoIjpmYWxzZSwiY29s\r\
  \nb3IiOiJ5ZWxsb3ciLCJib2xkIjpmYWxzZX1dfXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQA\r\
  \nCHVuaXF1ZUlkdAAKcHJvcGVydGllc3VxAH4ABgAAAAN0AA1QbGF5ZXJQcm9maWxldAAkZWQ1N2Vi\r\
  \nYzUtNzA0ZS0zYmExLThlMWEtMWU3NzRkODg0NTMzc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdId\r\
  \nmcdhnQMAAUkABHNpemV4cAAAAAF3BAAAAAFzcgAXamF2YS51dGlsLkxpbmtlZEhhc2hNYXA0wE5c\r\
  \nEGzA+wIAAVoAC2FjY2Vzc09yZGVyeHIAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAAps\r\
  \nb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAADHcIAAAAEAAAAAJ0AARuYW1ldAAIdGV4dHVy\r\
  \nZXN0AAV2YWx1ZXQAtGV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2\r\
  \nTHk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZPR1JqWXpabFlqUXda\r\
  \nak5pWVdSaE5ERmxORE16T1RnNE9HUTJaREl3TnpRek56VTVPR0prWW1ReE56VmpNbVUzTXpFeE9U\r\
  \nRmtOV0U1WVRReVpETmpPQ0o5ZlgwPXgAeHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJ\r\
  \ncQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAhQT1JLQ0hPUHNxAH4ADgAAAApz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAALQ09PS0VEX0JFRUZzcQB+AA4AAAAIc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAEUNPQkJMRURfREVF\r\
  \nUFNMQVRFcQB+AGZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+\r\
  \nAAYAAAAEcQB+AA1zcQB+AA4AAA50dAAEVFVGRnNxAH4ADgAAAA1zcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElBTU9O\r\
  \nRHNxAH4ADgAAAAVwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARx\r\
  \nAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAVTVElDS3NxAH4A\r\
  \nDgAAAAxwcHBwcA==\r\n"
xp: 270.0
health: 20.0
hunger: 20
saturation: 12.8
location:
  world: world
  x: 697.0
  y: -20.0
  z: 815.7
logType: QUIT
version: v1_20_R3
