inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRv\r\
  \ncnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBq\r\
  \nYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAtDT0JCTEVTVE9ORXNxAH4ADgAAAD5z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAEQ09BTHNxAH4ADgAAAARzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElPUklURXNxAH4ADgAAAAJz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAFVE9SQ0hxAH4AGXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+\r\
  \nAAp0AARtZXRhdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAD0RJQU1PTkRfUElDS0FYRXNxAH4A\r\
  \nAHNxAH4AA3VxAH4ABgAAAANxAH4ACHQACW1ldGEtdHlwZXQABkRhbWFnZXVxAH4ABgAAAAN0AAhJ\r\
  \ndGVtTWV0YXQAClVOU1BFQ0lGSUNzcQB+AA4AAACFc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAI\r\
  \ncQB+AAlxAH4ACnEAfgAqdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0RJQU1PTkRfQVhFc3EA\r\
  \nfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+ADFxAH4AMnVxAH4ABgAAAANxAH4ANHEAfgA1c3EA\r\
  \nfgAOAAAAQ3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AKnVxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAtQTEFZRVJfSEVBRHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4A\r\
  \nCHEAfgAxdAAMZGlzcGxheS1uYW1ldAALc2t1bGwtb3duZXJ1cQB+AAYAAAAEcQB+ADR0AAVTS1VM\r\
  \nTHQAknsidGV4dCI6IiIsImV4dHJhIjpbeyJ0ZXh0IjoiQmFja3BhY2siLCJvYmZ1c2NhdGVkIjpm\r\
  \nYWxzZSwiaXRhbGljIjpmYWxzZSwidW5kZXJsaW5lZCI6ZmFsc2UsInN0cmlrZXRocm91Z2giOmZh\r\
  \nbHNlLCJjb2xvciI6InllbGxvdyIsImJvbGQiOmZhbHNlfV19c3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nA3EAfgAIdAAIdW5pcXVlSWR0AApwcm9wZXJ0aWVzdXEAfgAGAAAAA3QADVBsYXllclByb2ZpbGV0\r\
  \nACRlZDU3ZWJjNS03MDRlLTNiYTEtOGUxYS0xZTc3NGQ4ODQ1MzNzcgATamF2YS51dGlsLkFycmF5\r\
  \nTGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyABdqYXZhLnV0aWwuTGlua2VkSGFz\r\
  \naE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg\r\
  \n0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAnQABG5hbWV0\r\
  \nAAh0ZXh0dXJlc3QABXZhbHVldAC0ZXlKMFpYaDBkWEpsY3lJNmV5SlRTMGxPSWpwN0luVnliQ0k2\r\
  \nSW1oMGRIQTZMeTkwWlhoMGRYSmxjeTV0YVc1bFkzSmhablF1Ym1WMEwzUmxlSFIxY21Vdk9HUmpZ\r\
  \nelpsWWpRd1pqTmlZV1JoTkRGbE5ETXpPVGc0T0dRMlpESXdOelF6TnpVNU9HSmtZbVF4TnpWak1t\r\
  \nVTNNekV4T1RGa05XRTVZVFF5WkROak9DSjlmWDA9eAB4c3EAfgAAc3EAfgADdXEAfgAGAAAABHEA\r\
  \nfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQACFBPUktDSE9Qc3EA\r\
  \nfgAOAAAACnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAA\r\
  \nAARxAH4ADXNxAH4ADgAADnR0AAtDT09LRURfQkVFRnNxAH4ADgAAABJzcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHR1JB\r\
  \nTklURXNxAH4ADgAAAA9zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1\r\
  \ncQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAMUk9UVEVOX0ZMRVNIcQB+ACBwcHBwcHBwcHBwcHBw\r\
  \ncHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4A\r\
  \nKnVxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAZTSElFTERzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4AMXEAfgAydAANYmxvY2tNYXRlcmlhbHVxAH4ABgAAAARxAH4ANHQAC1RJTEVfRU5U\r\
  \nSVRZc3EAfgAOAAAApnEAfgCB\r\n"
xp: 155.0
health: 9.997552871704102
hunger: 20
saturation: 9.8
location:
  world: world
  x: 698.5
  y: 2.0
  z: 670.2
logType: QUIT
version: v1_20_R3
