inventory: "rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
  \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
  \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj\r\
  \ndDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA\r\
  \nBHQAAj09dAABdnQABHR5cGV0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRv\r\
  \ncnkuSXRlbVN0YWNrc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBq\r\
  \nYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAADnR0AAtDT0JCTEVTVE9ORXNxAH4ADgAAAD5z\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAEQ09BTHNxAH4ADgAAAARzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A\r\
  \nCXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAHRElPUklURXNxAH4ADgAAAAJz\r\
  \ncQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\r\
  \ncQB+AA4AAA50dAAFVE9SQ0hzcQB+AA4AAAAGc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+\r\
  \nAAlxAH4ACnQABG1ldGF1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAPRElBTU9ORF9QSUNLQVhF\r\
  \nc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAJbWV0YS10eXBldAAGRGFtYWdldXEAfgAGAAAA\r\
  \nA3QACEl0ZW1NZXRhdAAKVU5TUEVDSUZJQ3NxAH4ADgAAAIVzcQB+AABzcQB+AAN1cQB+AAYAAAAE\r\
  \ncQB+AAhxAH4ACXEAfgAKcQB+ACt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAALRElBTU9ORF9B\r\
  \nWEVzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4AMnEAfgAzdXEAfgAGAAAAA3EAfgA1cQB+\r\
  \nADZzcQB+AA4AAABDc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgArdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC1BMQVlFUl9IRUFEc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
  \nBHEAfgAIcQB+ADJ0AAxkaXNwbGF5LW5hbWV0AAtza3VsbC1vd25lcnVxAH4ABgAAAARxAH4ANXQA\r\
  \nBVNLVUxMdACSeyJ0ZXh0IjoiIiwiZXh0cmEiOlt7InRleHQiOiJCYWNrcGFjayIsIm9iZnVzY2F0\r\
  \nZWQiOmZhbHNlLCJpdGFsaWMiOmZhbHNlLCJ1bmRlcmxpbmVkIjpmYWxzZSwic3RyaWtldGhyb3Vn\r\
  \naCI6ZmFsc2UsImNvbG9yIjoieWVsbG93IiwiYm9sZCI6ZmFsc2V9XX1zcQB+AABzcQB+AAN1cQB+\r\
  \nAAYAAAADcQB+AAh0AAh1bmlxdWVJZHQACnByb3BlcnRpZXN1cQB+AAYAAAADdAANUGxheWVyUHJv\r\
  \nZmlsZXQAJGVkNTdlYmM1LTcwNGUtM2JhMS04ZTFhLTFlNzc0ZDg4NDUzM3NyABNqYXZhLnV0aWwu\r\
  \nQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABc3IAF2phdmEudXRpbC5MaW5r\r\
  \nZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0aWwuSGFzaE1hcAUH\r\
  \n2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAACdAAE\r\
  \nbmFtZXQACHRleHR1cmVzdAAFdmFsdWV0ALRleUowWlhoMGRYSmxjeUk2ZXlKVFMwbE9JanA3SW5W\r\
  \neWJDSTZJbWgwZEhBNkx5OTBaWGgwZFhKbGN5NXRhVzVsWTNKaFpuUXVibVYwTDNSbGVIUjFjbVV2\r\
  \nT0dSall6WmxZalF3WmpOaVlXUmhOREZsTkRNek9UZzRPR1EyWkRJd056UXpOelU1T0dKa1ltUXhO\r\
  \nelZqTW1VM016RXhPVEZrTldFNVlUUXlaRE5qT0NKOWZYMD14AHhzcQB+AABzcQB+AAN1cQB+AAYA\r\
  \nAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAA50dAAIUE9SS0NI\r\
  \nT1BzcQB+AA4AAAAKc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEA\r\
  \nfgAGAAAABHEAfgANc3EAfgAOAAAOdHQAC0NPT0tFRF9CRUVGc3EAfgAOAAAAE3NxAH4AAHNxAH4A\r\
  \nA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0\r\
  \nAAdHUkFOSVRFc3EAfgAOAAAAD3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApx\r\
  \nAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAADnR0AAxST1RURU5fRkxFU0hxAH4AIHBwcHBwcHBw\r\
  \ncHBwcHBwcHBwcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4A\r\
  \nCnEAfgArdXEAfgAGAAAABHEAfgANc3EAfgAOAAAOdHQABlNISUVMRHNxAH4AAHNxAH4AA3VxAH4A\r\
  \nBgAAAARxAH4ACHEAfgAycQB+ADN0AA1ibG9ja01hdGVyaWFsdXEAfgAGAAAABHEAfgA1dAALVElM\r\
  \nRV9FTlRJVFlzcQB+AA4AAACmcQB+AII=\r\n"
xp: 155.0
health: 5.8308868408203125
hunger: 20
saturation: 9.8
location:
  world: world
  x: 710.2
  y: 7.0
  z: 668.4
logType: QUIT
version: v1_20_R3
