player-help:
  - "&aСправка по плагину"
  - "&a /activity Справка по плагину"
  - "&a /activity open Откройте бонусный экран графического интерфейса!"
admin-help:
  - "&aСправка по подключаемому модулю администратора"
  - "&a /activity Справка по плагину"
  - "&a /activity open Откройте бонусный экран графического интерфейса!"
  - "&a /activity reload Перезагрузите плагин"
no—time: "&7Время прошло или время еще не пришло!"
no-reward: "&7Вы уже заявили об этом!"
reload: "&7Плагин был перегружен!"
gratis: "&7Получите бесплатно. %reward%"
money: "&7Вы потратили %money% монет, чтобы получить %reward%"
no-money: "&7У вас недостаточно монет %money%, чтобы претендовать на %reward%"
points: "&7Вы потратили %points% облигаций, чтобы получить %reward%"
no-points: "&7У вас недостаточно %points% облигаций для получения %reward%"
no-error: "&7В конфигурации есть ошибка, пожалуйста, проверьте конфигурацию"
no-join: "&7У вас нет разрешений activity.join, пожалуйста, свяжитесь с администратором!"
is: 'Включено.'
no_is: 'Не работает.'
info:
  - '-----------------------------'
  - '&eНазвание плагина.: %plugin_name%'
  - "&eавтор: %author%"
  - '&eверс: %version%'
  - '&eVault: %is_vault%'
  - '&ePoints: %is_Points%'
  - '-----------------------------'