#MESSAGES
only_players: '&e&lMyRedeem | &cThis command can only be used by players!'
no_permission: '&e&lMyRedeem | &cYou do not have permission to use this command!'
myredeem_usage: '&e&lMyRedeem | &f/myredeem <subcommand>'
no_codes_redeemed: '&e&lMyRedeem | &cThis player has not yet redeemed any codes.'
checkcodes_usage: '&e&lMyRedeem | &fUsage: /mr checkcodes <player>'
codes_header: '&e&lMyRedeem | &fAvailable codes:'
redeemed_codes_list: '&e&lMyRedeem | &fRedeemed Codes:'
no_codes: '&e&lMyRedeem | &fThere are no available codes.'
deletecode_usage: '&e&lMyRedeem | &fUsage: /mr deletecode <code>'
invalid_code: '&e&lMyRedeem | &cInvalid code.'
code_deleted: '&e&lMyRedeem | &fCode deleted.'
createcode_usage: '&e&lMyRedeem | &fUsage: /mr createcode <code> <uses> <reward> <expiration>'
invalid_item: '&e&lMyRedeem | &cInvalid item.'
invalid_data: '&e&lMyRedeem | &cInvalid data value for item.'
code_created: '&e&lMyRedeem | &fCode created.'
redeem_usage: '&e&lMyRedeem | &fUsage: /redeem <code>'
code_exists: '&e&lMyRedeem | &cThe code already exists'
expiration_invalid: '&e&lMyRedeem | &cThe duration is invalid'
already_redeemed: '&e&lMyRedeem | &fYou have already redeemed this code.'
invalid_reward: '&e&lMyRedeem | &cInvalid reward type for code.'
redeem_success: '&e&lMyRedeem | &fYou have successfully redeemed code.'
reload_success: '&e&lMyRedeem | &aPlugin Reloaded.'
error_reload: '&e&lMyRedeem | &cAn error occurred while reloading the plugin.'
createrandomcode_usage: '&e&lMyRedeem | &fUsage: /mr createrandomcode <uses> <reward> <expiration>'
random_code: '&e&lMyRedeem | &fRandom code: %s'
help_header: '&e&lMyRedeem | &fCommands:'
help_redeem: '&f/redeem <code> &7- Redeem a code.'
help_code_reset: '&f/mr reset &7- Reset an redeemed code from a player.'
help_listcodes: '&f/mr listcodes &7- List available codes.'
help_addreward: '&f/mr addreward &7- Add a reward for a code.'
help_createcode: '&f/mr createcode <code> <uses> <reward> <expiration> &7- Create a new code.'
help_deletecode: '&f/mr deletecode <code> &7- Delete a code.'
help_createrandomcode: '&f/mr createrandomcode <uses> <reward> <expiration> &7- Create a new random code.'
help_setuses: '&f/mr setuses <code> <uses> &7- Change the uses of a code.'
help_myredeemreload: '&f/mr reload &7- Reload the plugin.'
help_checkcodes: '&f/mr checkcodes <player> &7- Check which codes a player has redeemed.'
uses_invalid: '&7You must specify maximum uses
  of the code'
code_expired: '&e&lMyRedeem | &fCode expired'
setuses_usage: '&e&lMyRedeem | &fUsage: /mr setuses <code> <uses>'
uses_changed: '&e&lMyRedeem | &fYou have successfully changed the uses.'
addreward_usage: '&e&lMyRedeem | &fUsage: /mr addreward <code> <reward>'
reward_added: '&e&lMyRedeem | &fYou have successfully added the reward.'
reset_usage: '&e&lMyRedeem | &fUsage: /mr reset <player> <code>'
code_reset: '&e&lMyRedeem | &fSuccessfully reset the redeemed code for the player.'
invalid_reset: '&e&lMyRedeem | &cInvalid player or code.'